# Generated by Django 5.2.15 on 2026-06-09 01:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('body', models.TextField()),
                ('kind', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.clinic')),
            ],
            options={
                'db_table': 'sms_template',
            },
        ),
        migrations.CreateModel(
            name='SmsCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'draft'), ('scheduled', 'scheduled'), ('sending', 'sending'), ('done', 'done'), ('cancelled', 'cancelled')], default='draft', max_length=12)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('target_count', models.IntegerField(default=0)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.clinic')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='messaging.smstemplate')),
            ],
            options={
                'db_table': 'sms_campaign',
            },
        ),
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('to_number', models.TextField()),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'queued'), ('sent', 'sent'), ('delivered', 'delivered'), ('failed', 'failed'), ('simulated', 'simulated')], default='queued', max_length=12)),
                ('provider_message_id', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='messaging.smscampaign')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.clinic')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='patients.patient')),
            ],
            options={
                'db_table': 'sms_message',
                'indexes': [models.Index(fields=['clinic', 'status', '-created_at'], name='sms_message_clinic__a6dabf_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='smstemplate',
            index=models.Index(fields=['clinic', 'is_active'], name='sms_templat_clinic__ce8341_idx'),
        ),
        migrations.AddIndex(
            model_name='smscampaign',
            index=models.Index(fields=['clinic', 'status'], name='sms_campaig_clinic__3872e1_idx'),
        ),
    ]
