# Generated by Django 5.2.15 on 2026-06-09 01:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('trial', 'trial'), ('active', 'active'), ('suspended', 'suspended'), ('cancelled', 'cancelled')], default='trial', max_length=16)),
                ('province', models.TextField(blank=True, default='')),
                ('city', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'clinic',
            },
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.TextField()),
                ('password_hash', models.BinaryField()),
                ('role', models.CharField(choices=[('clinic_manager', 'clinic_manager'), ('doctor', 'doctor'), ('reception', 'reception'), ('nurse', 'nurse')], max_length=20)),
                ('full_name', models.TextField(blank=True, default='')),
                ('medical_license_no', models.TextField(blank=True, default='', help_text='شمارهٔ نظام\u200cپزشکی — gate for clinical modules')),
                ('is_active', models.BooleanField(default=True)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='identity.clinic')),
            ],
            options={
                'db_table': 'app_user',
            },
        ),
        migrations.CreateModel(
            name='UserShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift', models.CharField(choices=[('morning', 'morning'), ('evening', 'evening'), ('night', 'night')], max_length=10)),
                ('work_date', models.DateField()),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='identity.clinic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='identity.appuser')),
            ],
            options={
                'db_table': 'user_shift',
            },
        ),
        migrations.AddIndex(
            model_name='appuser',
            index=models.Index(fields=['clinic', 'username'], name='app_user_clinic__7ac51b_idx'),
        ),
        migrations.AddConstraint(
            model_name='appuser',
            constraint=models.UniqueConstraint(fields=('clinic', 'username'), name='uq_app_user_clinic_username'),
        ),
        migrations.AddIndex(
            model_name='usershift',
            index=models.Index(fields=['clinic', 'work_date', 'shift'], name='user_shift_clinic__a77429_idx'),
        ),
    ]
