# Generated by Django 5.2.15 on 2026-06-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='clinic',
            name='clinic_type',
            field=models.CharField(choices=[('polyclinic', 'درمانگاه'), ('clinic', 'کلینیک'), ('office', 'مطب')], default='polyclinic', max_length=16),
        ),
        migrations.AddField(
            model_name='clinic',
            name='phone',
            field=models.TextField(blank=True, default=''),
        ),
    ]
