# Generated by Django 5.2.15 on 2026-06-09 01:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField()),
                ('shift', models.CharField(choices=[('morning', 'morning'), ('evening', 'evening'), ('night', 'night')], max_length=10)),
                ('total_rial', models.BigIntegerField(default=0)),
                ('paid_rial', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'open'), ('paid', 'paid'), ('partial', 'partial'), ('void', 'void')], default='open', max_length=10)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.appuser')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='patients.patient')),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='Injection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('amount_rial', models.BigIntegerField(default=0)),
                ('work_date', models.DateField()),
                ('shift', models.CharField(choices=[('morning', 'morning'), ('evening', 'evening'), ('night', 'night')], max_length=10)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='injections', to='patients.patient')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='injections', to='accounting.invoice')),
            ],
            options={
                'db_table': 'injection',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItemPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_rial', models.BigIntegerField()),
                ('method', models.CharField(choices=[('cash', 'cash'), ('card', 'card'), ('wallet', 'wallet'), ('insurance', 'insurance')], default='cash', max_length=12)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.clinic')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounting.invoice')),
            ],
            options={
                'db_table': 'invoice_item_payment',
            },
        ),
        migrations.CreateModel(
            name='PayrollSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_rial', models.BigIntegerField(default=0)),
                ('share_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.clinic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.appuser')),
            ],
            options={
                'db_table': 'payroll_setting',
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('amount_rial', models.BigIntegerField(default=0)),
                ('work_date', models.DateField()),
                ('shift', models.CharField(choices=[('morning', 'morning'), ('evening', 'evening'), ('night', 'night')], max_length=10)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.clinic')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures', to='accounting.invoice')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedures', to='patients.patient')),
            ],
            options={
                'db_table': 'procedure',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('visit', 'visit'), ('service', 'service'), ('nursing', 'nursing'), ('procedure', 'procedure'), ('consumable', 'consumable'), ('injection', 'injection')], max_length=16)),
                ('name', models.TextField()),
                ('amount_rial', models.BigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.clinic')),
            ],
            options={
                'db_table': 'tariff',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_rial', models.BigIntegerField(default=0)),
                ('work_date', models.DateField()),
                ('shift', models.CharField(choices=[('morning', 'morning'), ('evening', 'evening'), ('night', 'night')], max_length=10)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.clinic')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.appuser')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='accounting.invoice')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='patients.patient')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.tariff')),
            ],
            options={
                'db_table': 'visit',
            },
        ),
        migrations.CreateModel(
            name='VisitItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('quantity', models.IntegerField(default=1)),
                ('amount_rial', models.BigIntegerField(default=0)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.clinic')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.visit')),
            ],
            options={
                'db_table': 'visit_item',
            },
        ),
        migrations.CreateModel(
            name='ConsumableLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('quantity', models.IntegerField(default=0)),
                ('amount_rial', models.BigIntegerField(default=0)),
                ('direction', models.CharField(choices=[('in', 'in'), ('out', 'out')], default='out', max_length=8)),
                ('work_date', models.DateField()),
                ('shift', models.CharField(choices=[('morning', 'morning'), ('evening', 'evening'), ('night', 'night')], max_length=10)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.clinic')),
            ],
            options={
                'db_table': 'consumable_ledger',
                'indexes': [models.Index(fields=['clinic', 'work_date', 'shift'], name='consumable__clinic__b5d641_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['clinic', 'work_date', 'shift'], name='invoice_clinic__6f7c2a_idx'),
        ),
        migrations.AddIndex(
            model_name='injection',
            index=models.Index(fields=['clinic', 'work_date', 'shift'], name='injection_clinic__0dc392_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitempayment',
            index=models.Index(fields=['clinic', 'invoice'], name='invoice_ite_clinic__30db99_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollsetting',
            index=models.Index(fields=['clinic', 'user'], name='payroll_set_clinic__b55db4_idx'),
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['clinic', 'work_date', 'shift'], name='procedure_clinic__67347c_idx'),
        ),
        migrations.AddIndex(
            model_name='tariff',
            index=models.Index(fields=['clinic', 'kind', 'is_active'], name='tariff_clinic__a100e2_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['clinic', 'work_date', 'shift'], name='visit_clinic__827122_idx'),
        ),
        migrations.AddIndex(
            model_name='visititem',
            index=models.Index(fields=['clinic', 'visit'], name='visit_item_clinic__466dfc_idx'),
        ),
    ]
