# Generated by Django 5.2.15 on 2026-06-09 10:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('identity', '0002_clinic_address_clinic_clinic_type_clinic_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='category',
            field=models.CharField(blank=True, choices=[('', '—'), ('drug', 'دارو'), ('supply', 'مصرفی عمومی')], default='', max_length=10),
        ),
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('is_supplementary', models.BooleanField(default=False)),
                ('patient_share_percent', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.clinic')),
            ],
            options={
                'db_table': 'insurance_plan',
                'indexes': [models.Index(fields=['clinic', 'is_active'], name='insurance_p_clinic__663b58_idx')],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'name'), name='uq_insurance_plan_clinic_name')],
            },
        ),
    ]
