# Generated by Django 5.2.15 on 2026-06-09 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_tariff_category_insuranceplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='injection',
            name='insurance_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.insuranceplan'),
        ),
        migrations.AddField(
            model_name='injection',
            name='patient_share_rial',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='procedure',
            name='insurance_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.insuranceplan'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='patient_share_rial',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visit',
            name='insurance_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.insuranceplan'),
        ),
        migrations.AddField(
            model_name='visit',
            name='patient_share_rial',
            field=models.BigIntegerField(default=0),
        ),
    ]
