-- ============================================================================
-- schema_pg_slice8_ddi.sql
-- برشِ ۸ — Drug-Drug Interaction (DDI) catalog
--
-- هدف:
--   جدولِ clinical.ddi_pairs را می‌سازد: کاتالوگِ تداخلاتِ دارویی بر اساسِ
--   class_a/class_b (کلاسِ فارماکولوژیک). این جدول mirror دقیقِ الگوی
--   clinical_rules است: tenant_id، RLSِ tenant_isolation + FORCE، GRANTها
--   عیناً همان‌اند.
--
-- قرارداد canonical:
--   CHECK (class_a < class_b) — جفت همیشه به ترتیبِ lexicographic ذخیره می‌شود.
--   lookup مستقل از ترتیب: tuple(sorted(class_a, class_b)) → یکتا.
--
-- seed: ۱۲ جفتِ بالینی curate‌شده توسطِ clinical-pharmacist-advisor
--   با ON CONFLICT (tenant_id, class_a, class_b) DO NOTHING (idempotent).
--   محتوای بالینی (پیام/منبع/severity) عیناً از فارماسیست — تغییر ندهید.
--
-- manager-editable: is_active=FALSE کردن یک جفت → از سرفیسِ DDI حذف می‌شود.
--
-- وابستگی: بعد از slice0 (رول‌ها + tenants) + slice5 (RLS).
-- idempotent: CREATE TABLE IF NOT EXISTS + ON CONFLICT DO NOTHING همه‌جا.
-- ============================================================================

-- ###########################################################################
-- ۱) ایجادِ جدولِ کاتالوگِ DDI
-- ###########################################################################
CREATE TABLE IF NOT EXISTS clinical.ddi_pairs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    class_a     TEXT   NOT NULL,
    class_b     TEXT   NOT NULL,
    severity    TEXT   NOT NULL CHECK (severity IN ('contraindicated','major','moderate','minor')),
    message_fa  TEXT   NOT NULL,
    evidence    TEXT,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- canonical order: class_a < class_b تضمین می‌کند lookup جهت‌مستقل است
    CONSTRAINT chk_ddi_canonical_order CHECK (class_a < class_b),
    -- UNIQUE مرکب با tenant_id (چندمستأجری)
    CONSTRAINT uq_ddi_pairs_tenant_class UNIQUE (tenant_id, class_a, class_b)
);

CREATE INDEX IF NOT EXISTS idx_ddi_pairs_tenant_active
    ON clinical.ddi_pairs (tenant_id, is_active)
    WHERE is_active = TRUE;

-- ###########################################################################
-- ۲) RLS — عیناً مثلِ clinical_rules (برشِ ۵ این را auto-detect می‌کند
--    چون جدول tenant_id دارد؛ اما ما صریح هم اعمال می‌کنیم برای idempotency)
-- ###########################################################################
ALTER TABLE clinical.ddi_pairs ENABLE ROW LEVEL SECURITY;
ALTER TABLE clinical.ddi_pairs FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON clinical.ddi_pairs;
CREATE POLICY tenant_isolation ON clinical.ddi_pairs
    FOR ALL
    USING      (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::bigint)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::bigint);

-- ###########################################################################
-- ۳) GRANTها — عیناً مثلِ siblingهای clinical
-- ###########################################################################
GRANT SELECT, INSERT, UPDATE, DELETE ON clinical.ddi_pairs TO clinical_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON clinical.ddi_pairs TO platform_app;

-- ###########################################################################
-- ۴) Seed idempotent — ۱۲ جفتِ curate‌شده توسطِ clinical-pharmacist-advisor
--    canonical order: class_a < class_b (اثبات: 'acei' < 'arb' → OK ...)
--    پیام و منبع عیناً از فارماسیست — تغییر ندهید.
-- ###########################################################################

-- ۴.۱ — ترتیبِ canonical همهٔ جفت‌ها:
--   acei    < arb          ✓
--   acei    < finerenone   ✓
--   acei    < mra          ✓
--   arb     < finerenone   ✓
--   arb     < mra          ✓
--   beta_blocker < su      ✓
--   fibrate < statin       ✓
--   finerenone < mra       ✓
--   glp1_ra < insulin_basal ✓ (g < i)
--   insulin_basal < su     ✓ (i < s)
--   loop_diuretic < sglt2i ✓ (l < s)
--   su < thiazide          ✓ (s < t)

INSERT INTO clinical.ddi_pairs
    (tenant_id, class_a, class_b, severity, message_fa, evidence, is_active)
VALUES

-- ۱. ACEI + ARB (contraindicated)
(1, 'acei', 'arb', 'contraindicated',
 'ترکیبِ دو بلاکرِ RAAS: خطرِ هایپرکالمی، AKI و هیپوتانسیونِ شدید — بدونِ سودِ اضافه بر مونوتراپی؛ جایگزین کنید',
 'ONTARGET 2008؛ ADA 2025 §CKD',
 TRUE),

-- ۲. ACEI + Finerenone (major)
(1, 'acei', 'finerenone', 'major',
 'فینرنون فقط روی پسِ‌زمینهٔ ACEI/ARB تک‌دارویی آزموده شد؛ پایشِ K+ لازم',
 'FIDELIO-DKD 2020',
 TRUE),

-- ۳. ACEI + MRA (major)
(1, 'acei', 'mra', 'major',
 'بلاکِ RAAS + نگهداری پتاسیم: خطرِ هایپرکالمی بالاتر، پایشِ K+ و Cr لازم؛ در CKD eGFR<45 احتیاطِ مضاعف',
 'KDIGO 2022؛ FIDELIO-DKD',
 TRUE),

-- ۴. ARB + Finerenone (major)
(1, 'arb', 'finerenone', 'major',
 'فینرنون فقط روی پسِ‌زمینهٔ ACEI/ARB تک‌دارویی آزموده شد؛ پایشِ K+ لازم',
 'FIDELIO-DKD 2020',
 TRUE),

-- ۵. ARB + MRA (major)
(1, 'arb', 'mra', 'major',
 'بلاکِ دوگانهٔ RAAS + MR: هایپرکالمی؛ خطر در CKD بیشتر است؛ پایشِ K+/Cr',
 'NDT meta-analysis 2023',
 TRUE),

-- ۶. Beta_blocker + SU (major)
(1, 'beta_blocker', 'su', 'major',
 'بتابلاکر علائمِ هیپوگلیسمی را می‌پوشاند؛ آموزشِ بیمار و پایش؛ ترجیحاً بتابلاکرِ کاردیوسلکتیو (بویژه با غیراختصاصی مثلِ پروپرانولول)',
 'Diabetes Care 2023',
 TRUE),

-- ۷. Fibrate + Statin (major)
(1, 'fibrate', 'statin', 'major',
 'خطرِ میوپاتی و رابدومیولیز؛ جم‌فیبروزیل بدتر از فنوفیبرات؛ CK پایش شود',
 'AHA Circ 2016؛ FDA FAERS',
 TRUE),

-- ۸. Finerenone + MRA (contraindicated)
(1, 'finerenone', 'mra', 'contraindicated',
 'دو آنتاگونیست MR همزمان: هایپرکالمی شدید، آریتمی، ایستِ قلب؛ هرگز ترکیب نکنید',
 'FIDELIO-DKD pharmacology',
 TRUE),

-- ۹. GLP1-RA + Insulin Basal (major)
(1, 'glp1_ra', 'insulin_basal', 'major',
 'افزایشِ خطرِ هیپوگلیسمی؛ دوزِ انسولین ~۲۰–۲۵٪ کاهش و پایشِ قند',
 'ADA 2025 §9',
 TRUE),

-- ۱۰. Insulin Basal + SU (major)
(1, 'insulin_basal', 'su', 'major',
 'هر دو خطرِ هیپوگلیسمیِ تجمیعی؛ دوزِ SU معمولاً باید کاهش یابد',
 'ADA Standards 2025 §9',
 TRUE),

-- ۱۱. Loop Diuretic + SGLT2i (moderate)
(1, 'loop_diuretic', 'sglt2i', 'moderate',
 'هر دو ادرارآور؛ خطرِ دهیدراسیون/هایپوولمی بویژه سالمند/CKD G3+؛ فشارِ وضعیتی و Cr پایش شود',
 'DAPA-HF؛ JACC HF 2023',
 TRUE),

-- ۱۲. SU + Thiazide (moderate)
(1, 'su', 'thiazide', 'moderate',
 'تیازید قند را بالا می‌برد (هیپوکالمی→مهارِ ترشحِ انسولین)؛ پایشِ FBS/HbA1c و تنظیمِ دوزِ SU',
 'Hypertension 2008 AHA',
 TRUE)

ON CONFLICT (tenant_id, class_a, class_b) DO NOTHING;

-- ============================================================================
-- معیارِ «انجام‌شدهٔ» برشِ ۸ (برای تستِ نگهبان):
--   ۱) clinical.ddi_pairs موجود است (CREATE TABLE IF NOT EXISTS).
--   ۲) CHECK (class_a < class_b) فعال است — INSERT با class_a > class_b رد می‌شود.
--   ۳) UNIQUE(tenant_id, class_a, class_b) — INSERT تکراری DO NOTHING.
--   ۴) RLS tenant_isolation + FORCE فعال است روی clinical.ddi_pairs.
--   ۵) clinical_app و platform_app GRANT INSERT/SELECT دارند.
--   ۶) شمارشِ seed = ۱۲ جفت برای tenant_id=1.
--   ۷) idempotency: اجرای مجددِ این برش بدونِ خطا (IF NOT EXISTS + ON CONFLICT).
-- ============================================================================
