-- ============================================================================
-- پلتفرمِ یکپارچه — برشِ ۲ (هستهٔ بالینی · schema clinical)  ·  PostgreSQL 13+
-- مرجع: ADR-0007 (هویتِ بیمار + مرزِ cross-schema + مدلِ داده) · ADR-0006 (ابریِ یکپارچه)
--        · ADR-0005 (Observation کانونیک) · ADR-0004 (کارتِ بیمار/توکن)
--
-- این برش، کلِ بدنهٔ schemaِ `clinical` را می‌سازد (برشِ ۰ از قبل سه schema + tenants
-- + users + accounting.patients + clinical.patient_links را ساخته است). همهٔ جداولِ اینجا
-- FK به `clinical.patient_links(id)` می‌زنند — همان قراردادِ `patient_link_id` در SQLite.
--
-- مبنای ترجمه = `specialist_clinic/src/adapters/sqlite/schema.sql` (منبعِ حقیقت)
--   + ستون‌های additive از `core.py::_run_migrations` که روی DBِ زنده وجود دارند ولی در
--     schema.sql نیستند (end_date/drug_class/source_rule/source_event/appointment_id/
--     fulfillment/record_section/event_type/is_custom/test_key). این فایل مدلِ *زنده* را
--     بازتاب می‌دهد، نه فقط schema.sql خام. هر یک با کامنتِ «(migration core.py)» علامت خورده.
--
-- تصمیم‌های قفل‌شده (ADR-0007 §۵ ضمیمه A):
--   * همه‌چیز در schema `clinical`؛ هر جدول `tenant_id BIGINT NOT NULL DEFAULT 1
--     REFERENCES platform.tenants(id)` (RLS موکول به T1 — اینجا فقط ساختار).
--   * AUTOINCREMENT → BIGINT GENERATED BY DEFAULT AS IDENTITY (همه‌جا BY DEFAULT —
--     ORM-friendly: Django bulk_create/fixtures می‌تواند id صریح بدهد؛ دیگر preserve-id ETL
--     محرّک نیست).
--   * پول/اعتبار (REAL/INTEGER) → NUMERIC(14,0) تومانِ صحیح (تصمیمِ مالک ۱۴۰۵/۰۳؛ literal کپی).
--   * بولی‌های INTEGER (is_active/is_paid/sms_opt_out/is_custom/…) → BOOLEAN (1→TRUE، 0→FALSE).
--     اپ Django-from-scratch است (نه کدِ Flaskِ legacy با `=1`)، پس منطقِ مؤجلِ فاز-۱ افتاد.
--   * *_json TEXT (trigger_json/action_params_json/items/options/standard_doses) → JSONB.
--   * زمان: لحظه‌ای (measured_at/taken_at/scheduled_at/issued_at/created_at/…) → TIMESTAMPTZ
--     NOT NULL DEFAULT now(). تاریخِ تقویمیِ متنی (onset_date/start_date/refill_due_date/
--     due_date/work_date/event_date/performed_on/…) → DATE (بدونِ timezone-shift).
--     ⚠️ استثناها صریحاً کامنت‌گذاری شده‌اند (پایین، در «تصمیم‌های مرزیِ DATE-vs-TIMESTAMPTZ»).
--   * UNIQUE(x) → UNIQUE(tenant_id, x)؛ کلیدهای idempotency مرکب با tenant_id.
--   * INSERT OR IGNORE → INSERT … ON CONFLICT DO NOTHING (روی کلیدِ یکتای صریح).
--   * لجرهای مرزی (processed_invoices/doctor_visit_log/campaign_audience): snapshotهای
--     accounting (accounting_invoice_id/national_id/full_name/total_amount) literal حفظ
--     می‌شوند، فعلاً بدونِ FK به accounting (بدنهٔ accounting در برشِ ۳ ساخته می‌شود).
--   * Observation کانونیک (ADR-0005): vital_readings + lab_results دو جدولِ جدا + یک
--     VIEW `clinical.observations` (UNION با کلیدِ مشترک COALESCE(test_key, type)).
--
-- ترتیبِ topological: catalogها/conditions (parent) → جداولِ patient (child) → لجرها → VIEW.
-- اعتبارسنجیِ واقعی روی Postgres بعداً (این یک artifactِ طراحیِ ساخت‌شدنی است).
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS clinical;

-- ###########################################################################
-- بخش ۱ — کاتالوگ‌ها و metadata (parentها؛ بدونِ FK به جداولِ patient)
-- ###########################################################################

-- ---------------------------------------------------------------------------
-- conditions — کاتالوگِ بیماری‌ها (ماژول‌های disease). id ثابتِ seed → BY DEFAULT.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical.conditions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    name           TEXT NOT NULL,
    code           TEXT,
    is_active      BOOLEAN NOT NULL DEFAULT TRUE,   -- بولی
    is_chronic     BOOLEAN NOT NULL DEFAULT TRUE,   -- نمایش به‌عنوان ماژولِ disease
    display_order  INTEGER NOT NULL DEFAULT 100,
    description    TEXT,                            -- خلاصهٔ سادهٔ صفحهٔ per-disease
    icon           TEXT,                            -- svg sprite id (مثل 'i-heart')
    color          TEXT,                            -- توکنِ رنگ (info|warn|danger|ok|violet)
    CONSTRAINT uq_conditions_tenant_name UNIQUE (tenant_id, name),
    -- Batch 2c: هدفِ FKِ مرکبِ care_protocols و patient_conditions (tenant-safe)
    CONSTRAINT uq_conditions_tenant_id UNIQUE (tenant_id, id)
);

-- ---------------------------------------------------------------------------
-- care_protocols — چک‌های دوره‌ایِ استانداردِ هر بیماری. id ثابتِ seed → BY DEFAULT.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical.care_protocols (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    -- Batch 2c: FKِ مرکب composite → cross-tenant reference ساختاراً غیرممکن
    condition_id     BIGINT,
    name             TEXT NOT NULL,
    interval_months  INTEGER NOT NULL,
    is_active        BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_care_protocols_condition FOREIGN KEY (tenant_id, condition_id)
        REFERENCES clinical.conditions (tenant_id, id)
);

-- ---------------------------------------------------------------------------
-- clinical_indicators — metadataِ اندیکاتورها (آستانه‌ها/اهداف). منبعِ زندهٔ thresholdها.
--   key یکتاست → UNIQUE(tenant_id, key). seed بر اساس key (نه id) → IDENTITY عادی.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical.clinical_indicators (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    key            TEXT NOT NULL,                       -- vital_readings.type key
    label          TEXT NOT NULL,
    unit           TEXT,
    category       TEXT NOT NULL DEFAULT 'other',       -- glycemic|bp|lipid|kidney|anthro|other
    direction      TEXT NOT NULL DEFAULT 'high',        -- high = بالاتر بدتر، low = پایین‌تر بدتر
    warn           REAL,                                -- آستانهٔ مرزی (NULL = بدونِ flag)
    danger         REAL,                                -- آستانهٔ red-flag (NULL = بدونِ flag)
    target         REAL,                                -- مقدارِ هدف (خطِ مرجعِ نمودار)
    goal_low       REAL,
    goal_high      REAL,
    conditions     TEXT NOT NULL DEFAULT 'all',         -- لیستِ comma از codeها، یا 'all'
    risk_weight    INTEGER NOT NULL DEFAULT 1,          -- سهم در امتیازِ وزن‌دارِ ریسک
    is_vital       BOOLEAN NOT NULL DEFAULT TRUE,         -- نمایش در ورودِ vital/داشبورد
    display_order  INTEGER NOT NULL DEFAULT 100,
    is_active      BOOLEAN NOT NULL DEFAULT TRUE,
    notes          TEXT,
    CONSTRAINT uq_indicators_tenant_key UNIQUE (tenant_id, key)
);

-- ---------------------------------------------------------------------------
-- clinical_rules — کاتالوگِ If/Then. trigger_json/action_params_json → JSONB.
--   ⚠️ خودِ ردیف‌های seed (انبوه، از clinical_rules_seed.py) اینجا منتقل نمی‌شوند —
--      «seed جداگانه» در ETL/بوت‌استرپِ پایتون، با ON CONFLICT (tenant_id, rule_code).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical.clinical_rules (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    rule_code           TEXT NOT NULL,
    title               TEXT NOT NULL,
    category            TEXT NOT NULL,                  -- diagnosis|target|medication|drug_safety|…
    condition_code      TEXT NOT NULL DEFAULT 'all',    -- ماژولِ صاحب: conditions.code یا 'all'
    trigger_json        JSONB,                          -- درختِ شرطِ ماشین‌خوان (NULL = اطلاعاتی/دستی)
    human_if            TEXT,
    recommendation      TEXT,                           -- «Then» نمایش‌داده به بالین
    dosage_titration    TEXT,
    monitoring          TEXT,
    contraindications   TEXT,
    evidence_level      TEXT,                           -- A|B|C|E
    action_type         TEXT NOT NULL DEFAULT 'educate',
    action_params_json  JSONB,
    severity            TEXT NOT NULL DEFAULT 'info',    -- info|warn|urgent
    priority            INTEGER NOT NULL DEFAULT 100,
    source_ref          TEXT,
    is_active           BOOLEAN NOT NULL DEFAULT TRUE,
    notes               TEXT,
    CONSTRAINT uq_clinical_rules_tenant_code UNIQUE (tenant_id, rule_code)
);
CREATE INDEX IF NOT EXISTS idx_clinical_rules_cat ON clinical.clinical_rules (tenant_id, category, priority);

-- ---------------------------------------------------------------------------
-- flag_catalog — کاتالوگِ ورودی‌های categorical/boolean بالینی (ADA §2).
--   options: "value|label,value|label,…" — قالبِ خاصِ کد، نه JSON → TEXT می‌ماند.
--   record_section: ستونِ additive از migration core.py.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical.flag_catalog (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    flag_key       TEXT NOT NULL,
    label          TEXT NOT NULL,
    flag_type      TEXT NOT NULL DEFAULT 'bool' CHECK (flag_type IN ('bool','enum','date','text')),        -- bool|enum|date|text
    options        TEXT,                                -- "value|label,…" (قالبِ خاصِ کد، نه JSON)
    category       TEXT NOT NULL DEFAULT 'other',       -- cardiac|renal|risk|hepatic|repro|lifestyle|…
    record_section TEXT,                                -- (migration core.py) بخشِ پرونده
    display_order  INTEGER NOT NULL DEFAULT 100,
    is_active      BOOLEAN NOT NULL DEFAULT TRUE,
    notes          TEXT,
    CONSTRAINT uq_flag_catalog_tenant_key UNIQUE (tenant_id, flag_key)
);

-- ---------------------------------------------------------------------------
-- drug_classes — نگاشتِ دارو به کلاسِ فارماکولوژیک. class_key یکتا.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical.drug_classes (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id         BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    class_key         TEXT NOT NULL,
    label             TEXT NOT NULL,
    glucose_lowering  BOOLEAN NOT NULL DEFAULT FALSE,      -- بولی
    display_order     INTEGER NOT NULL DEFAULT 100,
    is_active         BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_drug_classes_tenant_key UNIQUE (tenant_id, class_key)
);

-- ---------------------------------------------------------------------------
-- drug_catalog — نام داروها فیلتر‌شده با کلاس + دوزهای استاندارد.
--   standard_doses در کد رشتهٔ comma است؛ JSONB ایمن نیست → TEXT می‌ماند.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical.drug_catalog (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    generic_fa      TEXT NOT NULL,
    drug_class_key  TEXT,
    standard_doses  TEXT,                               -- رشتهٔ comma در کد، نه JSON
    is_active       BOOLEAN NOT NULL DEFAULT TRUE
);

-- ---------------------------------------------------------------------------
-- lab_test_catalog — کاتالوگِ آزمایش‌ها. PK طبیعیِ test_key (در SQLite TEXT PRIMARY KEY).
--   اینجا surrogate id + UNIQUE(tenant_id, test_key) تا چندمستأجری بشکند نخورد.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical.lab_test_catalog (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    test_key       TEXT NOT NULL,                       -- کلیدِ کانونیک (FK منطقی از lab_results.test_key)
    name_fa        TEXT NOT NULL,
    unit           TEXT,
    ref_low        REAL,
    ref_high       REAL,
    category       TEXT,
    display_order  INTEGER DEFAULT 100,
    is_active      BOOLEAN DEFAULT TRUE,
    CONSTRAINT uq_lab_test_catalog_tenant_key UNIQUE (tenant_id, test_key)
);

-- ---------------------------------------------------------------------------
-- condition_lab_tests — آزمایش‌های پرتکرارِ هر بیماری (PK مرکبِ طبیعی).
--   SQLite: PRIMARY KEY(condition_code, lab_test_key) → اینجا با tenant_id مرکب.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical.condition_lab_tests (
    tenant_id      BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    condition_code TEXT NOT NULL,
    lab_test_key   TEXT NOT NULL,
    display_order  INTEGER DEFAULT 100,
    PRIMARY KEY (tenant_id, condition_code, lab_test_key)
);

-- ---------------------------------------------------------------------------
-- engagement_events — جدولِ routingِ رویداد→کانال (manager-editable).
--   event_key یکتا. event_type/is_custom ستون‌های additive از migration core.py.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical.engagement_events (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    event_key      TEXT NOT NULL,
    label          TEXT NOT NULL,
    category       TEXT NOT NULL DEFAULT 'clinical' CHECK (category IN ('operational','clinical','marketing')),     -- operational|clinical|marketing
    channel        TEXT NOT NULL DEFAULT 'worklist' CHECK (channel IN ('sms','worklist','both','off')),     -- sms|worklist|both|off
    sms_template   TEXT,                                 -- placeholder {name}
    lead_days      INTEGER NOT NULL DEFAULT 0,           -- چند روز قبل از سررسید fire شود
    cooldown_days  INTEGER NOT NULL DEFAULT 30,          -- حداقل فاصلهٔ تکرار per patient
    source_action  TEXT,                                 -- action_type قاعده که این رویداد را می‌خوراند
    priority       INTEGER NOT NULL DEFAULT 100,
    event_type     TEXT,                                 -- (migration core.py)
    is_custom      BOOLEAN DEFAULT FALSE,                 -- (migration core.py) بولی
    is_active      BOOLEAN NOT NULL DEFAULT TRUE,
    notes          TEXT,
    CONSTRAINT uq_engagement_events_tenant_key UNIQUE (tenant_id, event_key)
);

-- ---------------------------------------------------------------------------
-- sms_templates — قالب‌های پیامک. id ثابتِ seed → BY DEFAULT.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical.sms_templates (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    name        TEXT NOT NULL,
    body        TEXT NOT NULL,                           -- پشتیبانیِ placeholder {name}
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- Batch 2c: هدفِ FKِ مرکبِ sms_campaigns.template_id (tenant-safe)
    CONSTRAINT uq_sms_templates_tenant_id UNIQUE (tenant_id, id)
);

-- ###########################################################################
-- بخش ۲ — جداولِ per-patient (FK به clinical.patient_links — از برشِ ۰)
-- ###########################################################################

-- ---------------------------------------------------------------------------
-- wallet_transactions — تراکنشِ کیف‌پول (پول → NUMERIC(14,0) تومان).
--   expires_at تاریخِ تقویمیِ متنیِ اختیاری → DATE.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical.wallet_transactions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    -- Batch 2c: FKِ مرکب composite → cross-tenant reference ساختاراً غیرممکن
    patient_link_id  BIGINT NOT NULL,
    amount           NUMERIC(14,0) NOT NULL,             -- + اعتبار افزوده، - استفاده (تومان)
    balance_after    NUMERIC(14,0) NOT NULL,
    reason           TEXT,                               -- campaign|manual|redeem|expire
    campaign_id      BIGINT,                             -- FK منطقی به sms_campaigns (nullable)
    note             TEXT,
    expires_at       DATE,                               -- تقویمی YYYY-MM-DD (اختیاری) → DATE
    created_by       TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_wallet_transactions_patient FOREIGN KEY (tenant_id, patient_link_id)
        REFERENCES clinical.patient_links (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS idx_wallet_tx_patient ON clinical.wallet_transactions (patient_link_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- patient_conditions — تشخیص‌ها. onset_date تقویمی → DATE. diagnosed_at لحظه → TIMESTAMPTZ.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical.patient_conditions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    -- Batch 2c: FKهای مرکب composite → cross-tenant reference ساختاراً غیرممکن
    patient_link_id  BIGINT NOT NULL,
    condition_id     BIGINT NOT NULL,
    stage            TEXT,
    onset_date       DATE,                               -- تقویمی YYYY-MM-DD
    notes            TEXT,
    is_active        BOOLEAN DEFAULT TRUE,
    diagnosed_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_patient_conditions_patient FOREIGN KEY (tenant_id, patient_link_id)
        REFERENCES clinical.patient_links (tenant_id, id),
    CONSTRAINT fk_patient_conditions_condition FOREIGN KEY (tenant_id, condition_id)
        REFERENCES clinical.conditions (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS idx_pc_patient ON clinical.patient_conditions (patient_link_id);

-- ---------------------------------------------------------------------------
-- patient_medications — داروها. start_date/refill_due_date/end_date تقویمی → DATE.
--   end_date و drug_class ستون‌های additive از migration core.py.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical.patient_medications (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    -- Batch 2c: FKِ مرکب composite → cross-tenant reference ساختاراً غیرممکن
    patient_link_id  BIGINT NOT NULL,
    drug_name        TEXT NOT NULL,
    dose             TEXT,
    schedule         TEXT,
    start_date       DATE,                               -- تقویمی YYYY-MM-DD
    refill_due_date  DATE,                               -- تقویمی YYYY-MM-DD
    end_date         DATE,                               -- (migration core.py) تقویمی YYYY-MM-DD
    drug_class       TEXT,                               -- (migration core.py) کلاسِ فارماکولوژیک
    is_active        BOOLEAN DEFAULT TRUE,
    notes            TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_patient_medications_patient FOREIGN KEY (tenant_id, patient_link_id)
        REFERENCES clinical.patient_links (tenant_id, id)
);

-- ---------------------------------------------------------------------------
-- medication_events — تایم‌لاینِ عینیِ شروع/قطع/تغییرِ دوز. event_date تقویمی → DATE.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical.medication_events (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    -- Batch 2c: FKِ مرکب composite → cross-tenant reference ساختاراً غیرممکن
    patient_link_id  BIGINT NOT NULL,
    medication_id    BIGINT,                             -- FK منطقی به patient_medications (nullable اگر حذف شود)
    drug_name        TEXT NOT NULL,
    event_type       TEXT NOT NULL,                      -- start|stop|dose_change
    dose             TEXT,                               -- دوزِ بعد از این رویداد
    event_date       DATE,                               -- تقویمی YYYY-MM-DD
    note             TEXT,
    created_by       TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_medication_events_patient FOREIGN KEY (tenant_id, patient_link_id)
        REFERENCES clinical.patient_links (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS idx_medevents_patient ON clinical.medication_events (patient_link_id, event_date);

-- ---------------------------------------------------------------------------
-- allergies — حساسیت‌ها.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical.allergies (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    -- Batch 2c: FKِ مرکب composite → cross-tenant reference ساختاراً غیرممکن
    patient_link_id  BIGINT NOT NULL,
    substance        TEXT NOT NULL,
    reaction         TEXT,
    severity         TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_allergies_patient FOREIGN KEY (tenant_id, patient_link_id)
        REFERENCES clinical.patient_links (tenant_id, id)
);

-- ---------------------------------------------------------------------------
-- vital_readings — اندازه‌گیری‌های حیاتی. measured_at لحظه‌ای → TIMESTAMPTZ.
--   نیمی از Observationِ کانونیک (ADR-0005؛ VIEW پایین).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical.vital_readings (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    -- Batch 2c: FKِ مرکب composite → cross-tenant reference ساختاراً غیرممکن
    patient_link_id  BIGINT NOT NULL,
    type             TEXT NOT NULL,
    value            REAL NOT NULL,
    unit             TEXT,
    measured_at      TIMESTAMPTZ NOT NULL DEFAULT now(),  -- لحظه‌ای (نه DATE)
    source           TEXT DEFAULT 'clinic',               -- clinic|self
    notes            TEXT,
    recorded_by      TEXT,
    CONSTRAINT fk_vital_readings_patient FOREIGN KEY (tenant_id, patient_link_id)
        REFERENCES clinical.patient_links (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS idx_vr_patient_type ON clinical.vital_readings (patient_link_id, type, measured_at DESC);

-- ---------------------------------------------------------------------------
-- lab_results — نتایجِ آزمایش. taken_at لحظه‌ای → TIMESTAMPTZ. test_key (additive، ADR-0005).
--   نیمی دیگرِ Observationِ کانونیک.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical.lab_results (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    -- Batch 2c: FKِ مرکب composite → cross-tenant reference ساختاراً غیرممکن
    patient_link_id  BIGINT NOT NULL,
    test_name        TEXT NOT NULL,
    test_key         TEXT,                                -- (migration core.py) کلیدِ کانونیکِ lab_test_catalog؛ NULL برای free-text/legacy (ADR-0005)
    value            REAL,
    unit             TEXT,
    ref_low          REAL,
    ref_high         REAL,
    taken_at         TIMESTAMPTZ NOT NULL DEFAULT now(),  -- لحظه‌ای (نه DATE)
    notes            TEXT,
    recorded_by      TEXT,
    CONSTRAINT fk_lab_results_patient FOREIGN KEY (tenant_id, patient_link_id)
        REFERENCES clinical.patient_links (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS idx_lab_patient ON clinical.lab_results (patient_link_id, taken_at DESC);

-- ---------------------------------------------------------------------------
-- patient_flags — مقادیرِ per-patient برای flag_catalog. UNIQUE(patient_link_id, flag_key) مرکب.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical.patient_flags (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    -- Batch 2c: FKِ مرکب composite → cross-tenant reference ساختاراً غیرممکن
    patient_link_id  BIGINT NOT NULL,
    flag_key         TEXT NOT NULL,
    value            TEXT,
    recorded_by      TEXT,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_patient_flags UNIQUE (tenant_id, patient_link_id, flag_key),
    CONSTRAINT fk_patient_flags_patient FOREIGN KEY (tenant_id, patient_link_id)
        REFERENCES clinical.patient_links (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS idx_patient_flags ON clinical.patient_flags (patient_link_id);

-- ---------------------------------------------------------------------------
-- appointments — نوبت‌ها.
--   ⚠️ scheduled_at: SQLite کامنت می‌گوید «gregorian datetime YYYY-MM-DD HH:MM:SS» — لحظهٔ
--      تقویمی با ساعت → TIMESTAMPTZ (نه DATE؛ ساعت معنادار است). NOT NULL، بدونِ DEFAULT.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical.appointments (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id              BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    -- Batch 2c: FKِ مرکب composite → cross-tenant reference ساختاراً غیرممکن
    patient_link_id        BIGINT NOT NULL,
    scheduled_at           TIMESTAMPTZ NOT NULL,            -- زمانِ نوبت (تاریخ+ساعت) → لحظه‌ای
    appt_type              TEXT,                            -- visit|lab|checkup
    status                 TEXT NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled','done','no_show','cancelled')), -- scheduled|done|no_show|cancelled
    recurrence_months      INTEGER,                         -- نوبت‌های دوره‌ایِ خودکار
    parent_appointment_id  BIGINT,                          -- FK منطقی به همین جدول (nullable)
    reminder_sent          BOOLEAN DEFAULT FALSE,           -- بولی
    notes                  TEXT,
    created_by             TEXT,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_appointments_patient FOREIGN KEY (tenant_id, patient_link_id)
        REFERENCES clinical.patient_links (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS idx_appt_sched ON clinical.appointments (scheduled_at);
CREATE INDEX IF NOT EXISTS idx_appt_patient ON clinical.appointments (patient_link_id);

-- ---------------------------------------------------------------------------
-- followup_tasks — worklist. due_date تقویمی → DATE. resolved_at لحظه → TIMESTAMPTZ.
--   source_rule/source_event/appointment_id/fulfillment ستون‌های additive از migration core.py.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical.followup_tasks (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    -- Batch 2c: FKِ مرکب composite → cross-tenant reference ساختاراً غیرممکن
    patient_link_id  BIGINT NOT NULL,
    due_date         DATE,                                -- تقویمی YYYY-MM-DD
    reason           TEXT,                                -- refill|uncontrolled|lapsed|visit_due|manual
    detail           TEXT,
    status           TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','done','dismissed')),         -- open|done|dismissed
    assigned_to      TEXT,
    call_log         TEXT,
    source_rule      TEXT,                                -- (migration core.py) قاعدهٔ مولد (dedupe)
    source_event     TEXT,                                -- (migration core.py) رویدادِ مولدِ تعامل
    appointment_id   BIGINT,                              -- (migration core.py) نوبتِ مرتبط
    fulfillment      TEXT DEFAULT 'in_person' CHECK (fulfillment IN ('in_person','remote')),            -- (migration core.py) in_person|remote
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    resolved_at      TIMESTAMPTZ,                         -- لحظه‌ای (nullable، بدونِ DEFAULT)
    CONSTRAINT fk_followup_tasks_patient FOREIGN KEY (tenant_id, patient_link_id)
        REFERENCES clinical.patient_links (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS idx_followup_status ON clinical.followup_tasks (status, due_date);

-- ---------------------------------------------------------------------------
-- suggestion_log — اقدامِ پزشک روی پیشنهادهای موتور. UNIQUE(patient_link_id, rule_code) مرکب.
--   acted_at/created_at لحظه‌ای → TIMESTAMPTZ (acted_at nullable، بدونِ DEFAULT).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical.suggestion_log (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    -- Batch 2c: FKِ مرکب composite → cross-tenant reference ساختاراً غیرممکن
    patient_link_id  BIGINT NOT NULL,
    rule_code        TEXT NOT NULL,
    suggestion_text  TEXT,
    evidence_level   TEXT,
    status           TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','accepted','dismissed')),      -- pending|accepted|dismissed
    acted_by         TEXT,
    acted_at         TIMESTAMPTZ,
    note             TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_suggestion_log UNIQUE (tenant_id, patient_link_id, rule_code),
    CONSTRAINT fk_suggestion_log_patient FOREIGN KEY (tenant_id, patient_link_id)
        REFERENCES clinical.patient_links (tenant_id, id)
);

-- ###########################################################################
-- بخش ۳ — رکوردِ ساختاریافته (پروندهٔ بیماری‌محور، Phase 1 record redesign)
-- ###########################################################################

-- ---------------------------------------------------------------------------
-- surgery_history — سابقهٔ جراحی. performed_on تقویمی → DATE. created_at لحظه → TIMESTAMPTZ.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical.surgery_history (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    -- Batch 2c: FKِ مرکب composite → cross-tenant reference ساختاراً غیرممکن
    patient_link_id  BIGINT NOT NULL,
    title            TEXT NOT NULL,
    performed_on     DATE,                                -- تقویمی YYYY-MM-DD
    note             TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_surgery_history_patient FOREIGN KEY (tenant_id, patient_link_id)
        REFERENCES clinical.patient_links (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS idx_surgery_history_patient ON clinical.surgery_history (patient_link_id);

-- ---------------------------------------------------------------------------
-- medical_history — سابقهٔ پزشکی/comorbidity. since تقویمی → DATE.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical.medical_history (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    -- Batch 2c: FKِ مرکب composite → cross-tenant reference ساختاراً غیرممکن
    patient_link_id  BIGINT NOT NULL,
    title            TEXT NOT NULL,
    note             TEXT,
    since            DATE,                                -- تقویمی YYYY-MM-DD
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_medical_history_patient FOREIGN KEY (tenant_id, patient_link_id)
        REFERENCES clinical.patient_links (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS idx_medical_history_patient ON clinical.medical_history (patient_link_id);

-- ---------------------------------------------------------------------------
-- clinical_notes — یادداشت‌های آزادِ پرونده. recorded_at لحظه → TIMESTAMPTZ.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical.clinical_notes (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    -- Batch 2c: FKِ مرکب composite → cross-tenant reference ساختاراً غیرممکن
    patient_link_id  BIGINT NOT NULL,
    kind             TEXT NOT NULL,                       -- symptom|exam|lifestyle|general
    body             TEXT,
    recorded_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    recorded_by      TEXT,
    CONSTRAINT fk_clinical_notes_patient FOREIGN KEY (tenant_id, patient_link_id)
        REFERENCES clinical.patient_links (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS idx_clinical_notes_patient ON clinical.clinical_notes (patient_link_id);

-- ---------------------------------------------------------------------------
-- prescriptions — لاگِ نسخه. items (لیستِ اقلام) → JSONB. issued_at لحظه → TIMESTAMPTZ.
--   mode ∈ free|insurance؛ portal_rx_id/insurer برای پلِ نسخه‌نویسی (Phase 6).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical.prescriptions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    -- Batch 2c: FKِ مرکب composite → cross-tenant reference ساختاراً غیرممکن
    patient_link_id     BIGINT NOT NULL,
    kind                TEXT NOT NULL,
    items               JSONB,                            -- لیستِ اقلام (*_json → JSONB)
    mode                TEXT DEFAULT 'free',              -- free|insurance
    insurer             TEXT,
    portal_rx_id        TEXT,
    prescriber_user_id  BIGINT,                           -- FK منطقی به platform.users (cross-schema؛ بعداً)
    followup_task_id    BIGINT,                           -- FK منطقی به followup_tasks (nullable)
    issued_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_prescriptions_patient FOREIGN KEY (tenant_id, patient_link_id)
        REFERENCES clinical.patient_links (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS idx_prescriptions_patient ON clinical.prescriptions (patient_link_id);

-- ---------------------------------------------------------------------------
-- patient_card_tokens — توکنِ کارتِ عمومیِ بیمار (ADR-0004).
--   ⚠️ expires_at: SQLite کامنت «Tehran local YYYY-MM-DD HH:MM:SS» (لحظه‌ای با ساعت) →
--      TIMESTAMPTZ، NOT NULL، بدونِ DEFAULT. issued_at لحظه‌ای → TIMESTAMPTZ DEFAULT now().
--      revoked_at لحظه‌ای nullable → TIMESTAMPTZ. national_id هرگز اینجا ذخیره نمی‌شود.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical.patient_card_tokens (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    -- Batch 2c: FKِ مرکب composite → cross-tenant reference ساختاراً غیرممکن
    patient_link_id  BIGINT NOT NULL,
    token            TEXT NOT NULL,                       -- secrets.token_urlsafe(32)
    issued_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at       TIMESTAMPTZ NOT NULL,                -- انقضای توکن (لحظه‌ای با ساعت)
    revoked_at       TIMESTAMPTZ,
    issued_by        TEXT,                                -- users.username صادرکننده
    CONSTRAINT uq_patient_card_token UNIQUE (tenant_id, token),
    CONSTRAINT fk_patient_card_tokens_patient FOREIGN KEY (tenant_id, patient_link_id)
        REFERENCES clinical.patient_links (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS idx_patient_card_token ON clinical.patient_card_tokens (token);

-- ###########################################################################
-- بخش ۴ — کمپین/پیامک و تعامل (engagement)
-- ###########################################################################

-- ---------------------------------------------------------------------------
-- sms_campaigns — کمپین‌های پیامکی. credit_amount → NUMERIC(14,0) (اعتبارِ تومان).
--   scheduled_at لحظه‌ای nullable → TIMESTAMPTZ. created_at → TIMESTAMPTZ DEFAULT now().
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical.sms_campaigns (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id            BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    name                 TEXT NOT NULL,
    -- Batch 2c: FKِ مرکب composite روی template_id (tenant-safe)
    template_id          BIGINT,
    body                 TEXT,
    segment              TEXT,                            -- all|diabetes|hypertension|uncontrolled|lapsed|refill_due
    campaign_type        TEXT NOT NULL DEFAULT 'info' CHECK (campaign_type IN ('info','wallet_credit','reminder')),     -- info|wallet_credit|reminder
    credit_amount        NUMERIC(14,0) DEFAULT 0,          -- اعتبارِ کیف‌پولِ هر گیرنده (تومان)
    credit_expires_days  INTEGER,                          -- انقضای اختیاریِ اعتبار
    holdout_percent      INTEGER NOT NULL DEFAULT 0 CHECK (holdout_percent BETWEEN 0 AND 100),        -- % گروهِ کنترلِ تصادفی (incrementality)
    status               TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','scheduled','sending','done','cancelled')),     -- draft|scheduled|sending|done|cancelled
    scheduled_at         TIMESTAMPTZ,
    total_recipients     INTEGER DEFAULT 0 CHECK (total_recipients >= 0),
    sent_count           INTEGER DEFAULT 0 CHECK (sent_count >= 0),
    failed_count         INTEGER DEFAULT 0 CHECK (failed_count >= 0),
    created_by           TEXT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- Batch 2c: UNIQUE(tenant_id, id) برای هدف‌گیریِ FKِ مرکبِ sms_messages و campaign_audience
    CONSTRAINT uq_sms_campaigns_tenant_id UNIQUE (tenant_id, id),
    CONSTRAINT fk_sms_campaigns_template FOREIGN KEY (tenant_id, template_id)
        REFERENCES clinical.sms_templates (tenant_id, id)
);

-- ---------------------------------------------------------------------------
-- sms_messages — لاگِ ارسالِ پیامک. sent_at لحظه‌ای nullable → TIMESTAMPTZ.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical.sms_messages (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    -- Batch 2c: FKهای مرکب composite → cross-tenant reference ساختاراً غیرممکن
    campaign_id      BIGINT,
    patient_link_id  BIGINT,                              -- nullable (ارسالِ بدونِ enrollment)
    recipient        TEXT NOT NULL,
    body             TEXT NOT NULL,
    status           TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','sent','failed')),      -- pending|sent|failed
    provider_msgid   TEXT,
    delivery_status  TEXT,
    error            TEXT,
    sent_at          TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_sms_messages_campaign FOREIGN KEY (tenant_id, campaign_id)
        REFERENCES clinical.sms_campaigns (tenant_id, id),
    CONSTRAINT fk_sms_messages_patient FOREIGN KEY (tenant_id, patient_link_id)
        REFERENCES clinical.patient_links (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS idx_sms_campaign ON clinical.sms_messages (campaign_id);

-- ---------------------------------------------------------------------------
-- campaign_audience — تقسیمِ treated/control (incrementality).
--   ⚠️ accounting_patient_id: snapshotِ عمدیِ denormalized (انتساب مستقل از منبع، ADR-0007 §۲.۲)
--      → literal کپی، فعلاً بدونِ FK به accounting.patients (بدنهٔ accounting در برشِ ۳).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical.campaign_audience (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id              BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    -- Batch 2c: FKهای مرکب composite → cross-tenant reference ساختاراً غیرممکن
    campaign_id            BIGINT NOT NULL,
    patient_link_id        BIGINT NOT NULL,
    accounting_patient_id  BIGINT,                         -- snapshotِ لینک (denormalized؛ FK مرکب در برشِ ۴)
    grp                    TEXT NOT NULL DEFAULT 'treated' CHECK (grp IN ('treated','control')), -- treated (sent) | control (held out)
    assigned_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_campaign_audience_campaign FOREIGN KEY (tenant_id, campaign_id)
        REFERENCES clinical.sms_campaigns (tenant_id, id),
    CONSTRAINT fk_campaign_audience_patient FOREIGN KEY (tenant_id, patient_link_id)
        REFERENCES clinical.patient_links (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS idx_campaign_audience ON clinical.campaign_audience (campaign_id, grp);

-- ---------------------------------------------------------------------------
-- engagement_dispatch — لجرِ idempotency/cooldown. UNIQUE مرکب با tenant_id.
--   period_key لحظهٔ زمانی نیست؛ یک bucket-keyِ متنی است → TEXT می‌ماند.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical.engagement_dispatch (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    -- Batch 2c: FKِ مرکب composite → cross-tenant reference ساختاراً غیرممکن
    patient_link_id  BIGINT NOT NULL,
    event_key        TEXT NOT NULL,
    period_key       TEXT NOT NULL,                       -- bucketِ dedupe (تاریخِ سررسید/ماه) — رشته، نه DATE
    channel          TEXT NOT NULL,                       -- sms|worklist
    ref_id           BIGINT,                              -- sms_messages.id یا followup_tasks.id
    status           TEXT NOT NULL DEFAULT 'done',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_engagement_dispatch UNIQUE (tenant_id, patient_link_id, event_key, period_key, channel),
    CONSTRAINT fk_engagement_dispatch_patient FOREIGN KEY (tenant_id, patient_link_id)
        REFERENCES clinical.patient_links (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS idx_engagement_dispatch ON clinical.engagement_dispatch (patient_link_id, event_key);

-- ---------------------------------------------------------------------------
-- engagement_approvals — صفِ تأییدِ پزشک (پیامک فقط پس از تأیید). UNIQUE مرکب.
--   due_date تقویمی → DATE. decided_at/sent_at لحظه‌ای → TIMESTAMPTZ. offer برای Phase 8.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical.engagement_approvals (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    -- Batch 2c: FKِ مرکب composite → cross-tenant reference ساختاراً غیرممکن
    patient_link_id  BIGINT NOT NULL,
    event_key        TEXT NOT NULL,
    channel          TEXT,
    due_date         DATE,                                -- تقویمی YYYY-MM-DD
    message          TEXT,
    offer            TEXT,                                -- رزرو برای قیمت‌گذاریِ Phase 8
    status           TEXT DEFAULT 'pending',
    period_key       TEXT,
    appointment_id   BIGINT,                              -- FK منطقی به appointments (nullable)
    decided_by       TEXT,
    decided_at       TIMESTAMPTZ,
    sent_at          TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_engagement_approvals UNIQUE (tenant_id, patient_link_id, event_key, period_key),
    CONSTRAINT fk_engagement_approvals_patient FOREIGN KEY (tenant_id, patient_link_id)
        REFERENCES clinical.patient_links (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS idx_engagement_approvals_patient ON clinical.engagement_approvals (patient_link_id);

-- ###########################################################################
-- بخش ۵ — لجرهای مرزی (clinical → accounting؛ snapshotهای denormalized)
--   ⚠️ ADR-0007 §۲.۲: accounting_invoice_id + snapshotها (national_id/full_name/
--      total_amount) کپیِ عمدیِ literal‌اند (انتساب مستقل از تغییرِ منبع). FK به
--      accounting.invoices پس از ساختِ بدنهٔ accounting در برشِ ۳ اضافه می‌شود.
-- ###########################################################################

-- ---------------------------------------------------------------------------
-- processed_invoices — لجرِ idempotentِ همگام‌سازیِ فاکتورهای CLOSED (read-only، ADR-0003).
--   total_amount پول → NUMERIC(14,0). work_date/closed_at: کامنتِ SQLite تقویمی (TEXT) ولی
--   closed_at معمولاً timestamp است؛ هر دو در کد به‌صورت رشتهٔ تقویمی مصرف می‌شوند —
--   work_date تقویمی → DATE؛ closed_at لحظه‌ای → TIMESTAMPTZ (لحظهٔ بسته‌شدن). outreach_done
--   additive از migration core.py.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical.processed_invoices (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id              BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    accounting_invoice_id  BIGINT NOT NULL,               -- کلیدِ idempotency (snapshot؛ FK مرکب در برشِ ۴)
    -- Batch 2c: FKِ مرکب composite روی patient_link_id → cross-tenant reference ساختاراً غیرممکن
    patient_link_id        BIGINT,                        -- NULL تا enroll شود
    national_id            TEXT,                          -- snapshot (denormalized عمدی)
    full_name              TEXT,                          -- snapshot (denormalized عمدی)
    work_date              DATE,                          -- تاریخِ کارِ تقویمی → DATE
    closed_at              TIMESTAMPTZ,                   -- لحظهٔ بسته‌شدن → TIMESTAMPTZ
    total_amount           NUMERIC(14,0),                 -- پول → تومانِ صحیح
    status                 TEXT NOT NULL DEFAULT 'applied' CHECK (status IN ('applied','pending_link')), -- applied | pending_link
    outreach_done          BOOLEAN NOT NULL DEFAULT FALSE,    -- (migration core.py) بولی
    processed_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_processed_invoices_acct UNIQUE (tenant_id, accounting_invoice_id),
    CONSTRAINT fk_processed_invoices_patient FOREIGN KEY (tenant_id, patient_link_id)
        REFERENCES clinical.patient_links (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS idx_processed_invoices_patient ON clinical.processed_invoices (patient_link_id);
CREATE INDEX IF NOT EXISTS idx_processed_invoices_status ON clinical.processed_invoices (status);

-- ---------------------------------------------------------------------------
-- doctor_visit_log — وضعیتِ صفِ ویزیتِ پزشک (snapshotِ مرزی + state محلی).
--   work_date تقویمی → DATE. started_at/done_at لحظه‌ای → TIMESTAMPTZ.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical.doctor_visit_log (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id              BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    accounting_invoice_id  BIGINT NOT NULL,               -- snapshot (FK مرکب در برشِ ۴)
    -- Batch 2c: FKِ مرکب composite روی patient_link_id → cross-tenant reference ساختاراً غیرممکن
    patient_link_id        BIGINT,
    national_id            TEXT,                          -- snapshot (denormalized عمدی)
    full_name              TEXT NOT NULL,                 -- snapshot (denormalized عمدی)
    work_date              DATE NOT NULL,                 -- تقویمی → DATE
    status                 TEXT NOT NULL DEFAULT 'waiting' CHECK (status IN ('waiting','in_progress','done')), -- waiting|in_progress|done
    started_at             TIMESTAMPTZ,
    done_at                TIMESTAMPTZ,
    physician_notes        TEXT,
    done_by                TEXT,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_doctor_visit_log_acct UNIQUE (tenant_id, accounting_invoice_id),
    CONSTRAINT fk_doctor_visit_log_patient FOREIGN KEY (tenant_id, patient_link_id)
        REFERENCES clinical.patient_links (tenant_id, id)
);
CREATE INDEX IF NOT EXISTS idx_doctor_visit_log_workdate ON clinical.doctor_visit_log (work_date, status);

-- ###########################################################################
-- بخش ۶ — Observationِ کانونیک (ADR-0005 §۲.۵): دو جدول + یک VIEW
--   UNION از vital_readings و lab_results با کلیدِ مشترک COALESCE(test_key, type).
--   نه ادغامِ فیزیکی (ریسکِ پایین، افزایشی). آیندهٔ Timescale: همین دو جدول hypertable،
--   VIEW دست‌نخورده.
-- ###########################################################################
CREATE OR REPLACE VIEW clinical.observations AS
    SELECT
        'vital'::text          AS source_table,
        v.id                   AS source_id,
        v.tenant_id            AS tenant_id,
        v.patient_link_id      AS patient_link_id,
        v.type                 AS obs_key,        -- کلیدِ مشترک: vital.type
        NULL::text             AS test_name,
        v.value                AS value,
        v.unit                 AS unit,
        NULL::real             AS ref_low,
        NULL::real             AS ref_high,
        v.measured_at          AS observed_at,    -- لحظهٔ مشاهده
        v.source               AS source,
        v.recorded_by          AS recorded_by
    FROM clinical.vital_readings v
    UNION ALL
    SELECT
        'lab'::text            AS source_table,
        l.id                   AS source_id,
        l.tenant_id            AS tenant_id,
        l.patient_link_id      AS patient_link_id,
        COALESCE(l.test_key, l.test_name) AS obs_key,  -- کلیدِ مشترک: COALESCE(test_key, test_name)
        l.test_name            AS test_name,
        l.value                AS value,
        l.unit                 AS unit,
        l.ref_low              AS ref_low,
        l.ref_high             AS ref_high,
        l.taken_at             AS observed_at,    -- لحظهٔ مشاهده
        'lab'::text            AS source,
        l.recorded_by          AS recorded_by
    FROM clinical.lab_results l;

-- ###########################################################################
-- بخش ۷ — Seedها (INSERT OR IGNORE → ON CONFLICT DO NOTHING)
--   منتقل‌شده: conditions, care_protocols, clinical_indicators, flag_catalog,
--             drug_classes, sms_templates, engagement_events.
--   رد‌شده (seed جداگانه در بوت‌استرپِ پایتون): clinical_rules (انبوه، از
--             clinical_rules_seed.py)، lab_test_catalog/drug_catalog/condition_lab_tests
--             (از lab_catalog_seed.py/drug_catalog_seed.py)، condition meta
--             (_seed_condition_meta — اینجا مستقیماً در درجِ conditions گنجانده شده).
-- ###########################################################################

-- conditions (id ثابت؛ شاملِ metadataِ disease-module)
INSERT INTO clinical.conditions (id, name, code, is_chronic, display_order, description, icon, color) VALUES
 (1, 'دیابت', 'diabetes', TRUE, 10, 'پایش قند، اهداف فردی، انتخاب دارو، غربالگری عوارض و واکسیناسیون.', 'i-activity', 'info'),
 (2, 'فشار خون', 'hypertension', TRUE, 20, 'کنترل فشار خون، انتخاب داروی ضدفشار، پایش کلیه/پتاسیم و هشدار بحران فشار.', 'i-heart', 'danger'),
 (3, 'چربی خون', 'hyperlipidemia', TRUE, 30, 'اهداف LDL، استاتین‌درمانی و پایش لیپید.', 'i-sigma', 'warn'),
 (4, 'بیماری کلیوی مزمن', 'ckd', TRUE, 40, 'مرحله‌بندی eGFR/آلبومینوری، داروهای محافظ کلیه و پایش.', 'i-clipboard', 'violet'),
 (5, 'تیروئید', 'thyroid', TRUE, 50, 'پایش TSH و تنظیم درمان تیروئید.', 'i-stethoscope', 'ok')
ON CONFLICT (tenant_id, name) DO NOTHING;

-- care_protocols (id ثابت)
INSERT INTO clinical.care_protocols (id, condition_id, name, interval_months) VALUES
 (1, 1, 'آزمایش HbA1c', 3),
 (2, 1, 'معاینه فوندوس چشم', 12),
 (3, 1, 'آزمایش عملکرد کلیه', 12),
 (4, 2, 'کنترل فشار خون', 1),
 (5, 2, 'نوار قلب (ECG)', 12)
ON CONFLICT DO NOTHING;  -- id IDENTITY؛ تضادِ PK جلوگیری از تکرار

-- clinical_indicators (بر اساس key؛ پیش‌فرض‌های ADA)
INSERT INTO clinical.clinical_indicators
  (key, label, unit, category, direction, warn, danger, target, goal_low, goal_high, conditions, risk_weight, display_order, notes) VALUES
  ('hba1c',        'HbA1c',              '%',          'glycemic', 'high', 7.0,  8.0,  7.0,  NULL, NULL, 'diabetes',                         3, 10, 'هدف اکثر بزرگسالان <۷٪؛ آسان‌گیرانه <۸٪'),
  ('fbs',          'قند ناشتا (FBS)',    'mg/dL',      'glycemic', 'high', 130,  180,  130,  80,   130,  'diabetes',                         2, 20, 'هدف ناشتا ۸۰–۱۳۰'),
  ('ppg',          'قند ۲ ساعت پس‌غذا',  'mg/dL',      'glycemic', 'high', 180,  250,  180,  NULL, NULL, 'diabetes',                         1, 25, 'اوج پس‌غذا <۱۸۰'),
  ('bp_systolic',  'فشار سیستول',        'mmHg',       'bp',       'high', 130,  140,  130,  NULL, NULL, 'diabetes,hypertension',            2, 30, 'هدف <۱۳۰/۸۰'),
  ('bp_diastolic', 'فشار دیاستول',       'mmHg',       'bp',       'high', 80,   90,   80,   NULL, NULL, 'diabetes,hypertension',            1, 40, 'هدف <۱۳۰/۸۰'),
  ('pulse',        'ضربان قلب',          'bpm',        'bp',       'high', 100,  120,  NULL, 60,   100,  'all',                              0, 110,'اطلاعاتی'),
  ('ldl',          'LDL کلسترول',        'mg/dL',      'lipid',    'high', 70,   100,  70,   NULL, NULL, 'diabetes,hypertension,hyperlipidemia', 2, 50, 'هدف فردی: <۷۰ پرخطر، <۵۵ ASCVD مستقر'),
  ('hdl',          'HDL کلسترول',        'mg/dL',      'lipid',    'low',  40,   35,   NULL, 40,   NULL, 'all',                              1, 60, 'هرچه بالاتر بهتر'),
  ('triglyceride', 'تری‌گلیسرید',        'mg/dL',      'lipid',    'high', 150,  500,  150,  NULL, NULL, 'diabetes,hypertension,hyperlipidemia', 1, 70, '≥۵۰۰ خطر پانکراتیت'),
  ('egfr',         'eGFR (عملکرد کلیه)', 'mL/min',     'kidney',   'low',  60,   30,   NULL, 60,   NULL, 'diabetes,hypertension,ckd',        3, 80, 'هرچه بالاتر بهتر؛ <۳۰ پرخطر'),
  ('uacr',         'UACR (آلبومین ادرار)','mg/g',      'kidney',   'high', 30,   300,  30,   NULL, NULL, 'diabetes,hypertension,ckd',        2, 90, '۳۰–۲۹۹ میکرو، ≥۳۰۰ ماکروآلبومینوری'),
  ('weight',       'وزن',                'kg',         'anthro',   'high', NULL, NULL, NULL, NULL, NULL, 'all',                              0, 100,'پایش روند'),
  ('bmi',          'BMI',                '',           'anthro',   'high', 25,   30,   NULL, NULL, 25,   'all',                              1, 105,'اضافه‌وزن ≥۲۵، چاقی ≥۳۰'),
  ('tsh',          'TSH (تیروئید)',      'mIU/L',      'other',    'high', 4.5,  10,   2.5,  0.4,  4.0,  'thyroid',                          1, 115,'بالا=کم‌کاری؛ پایین (<۰.۴)=پرکاری')
ON CONFLICT (tenant_id, key) DO NOTHING;

-- flag_catalog (ورودی‌های تصمیمِ ADA §2)
INSERT INTO clinical.flag_catalog (flag_key, label, flag_type, options, category, display_order) VALUES
 ('ascvd', 'سابقهٔ ASCVD (بیماری قلبی-عروقی آترواسکلروتیک)', 'bool', NULL, 'cardiac', 10),
 ('cvd_high_risk', 'ریسک بسیار بالای قلبی-عروقی (≥۵۵ سال + ≥۲ ریسک‌فاکتور)', 'bool', NULL, 'cardiac', 20),
 ('hf', 'نارسایی قلب (HF)', 'bool', NULL, 'cardiac', 30),
 ('hf_type', 'نوع نارسایی قلب', 'enum', 'HFrEF|EF کاهش‌یافته,HFpEF|EF حفظ‌شده,unknown|نامشخص', 'cardiac', 40),
 ('hf_symptomatic', 'نارسایی قلبِ علامت‌دار', 'bool', NULL, 'cardiac', 50),
 ('ckd_stage_g', 'مرحلهٔ CKD بر اساس eGFR', 'enum', 'G1|G1 (≥۹۰),G2|G2 (۶۰–۸۹),G3a|G3a (۴۵–۵۹),G3b|G3b (۳۰–۴۴),G4|G4 (۱۵–۲۹),G5|G5 (<۱۵)', 'renal', 60),
 ('ckd_stage_a', 'مرحلهٔ آلبومینوری', 'enum', 'A1|A1 (<۳۰),A2|A2 (۳۰–۲۹۹),A3|A3 (≥۳۰۰)', 'renal', 70),
 ('hypo_risk', 'ریسک هیپوگلیسمی', 'enum', 'low|پایین,atrisk|در معرض,high|بالا', 'risk', 80),
 ('masld', 'کبد چربِ متابولیک (MASLD)', 'bool', NULL, 'hepatic', 90),
 ('mash_biopsy', 'MASH اثبات‌شده / ریسک بالای فیبروز', 'bool', NULL, 'hepatic', 100),
 ('pregnancy', 'بارداری', 'bool', NULL, 'repro', 110),
 ('childbearing_no_contraception', 'توان بارداری بدون پیشگیری', 'bool', NULL, 'repro', 120),
 ('smoking', 'مصرف دخانیات/ویپ', 'enum', 'never|هرگز,former|ترک‌کرده,current|فعلی,vape|ویپ', 'lifestyle', 130),
 ('frailty', 'وضعیت سلامت/فراژیلیتی (سالمند)', 'enum', 'robust|سالم,intermediate|میانی,complex|پیچیده/فراژیل', 'functional', 140),
 ('metabolic_surgery', 'سابقهٔ جراحی متابولیک', 'bool', NULL, 'history', 150),
 ('monofilament', 'مونوفیلامان ۱۰گرمی (حس محافظتی پا)', 'enum', 'normal|طبیعی,impaired|مختل,not_done|انجام‌نشده', 'exam', 160),
 ('eye_exam_date', 'آخرین معاینهٔ چشم (ته‌چشم گشاد)', 'date', NULL, 'exam', 170),
 ('foot_exam_date', 'آخرین معاینهٔ جامع پا', 'date', NULL, 'exam', 180)
ON CONFLICT (tenant_id, flag_key) DO NOTHING;

-- drug_classes
INSERT INTO clinical.drug_classes (class_key, label, glucose_lowering, display_order) VALUES
 ('metformin', 'متفورمین', TRUE, 10),
 ('sglt2i', 'مهارکنندهٔ SGLT2', TRUE, 20),
 ('glp1_ra', 'آگونیست GLP-1', TRUE, 30),
 ('dual_gip_glp1', 'آگونیست دوگانهٔ GIP/GLP-1 (تیرزپاتاید)', TRUE, 40),
 ('dpp4i', 'مهارکنندهٔ DPP-4', TRUE, 50),
 ('tzd', 'پیوگلیتازون (TZD)', TRUE, 60),
 ('su', 'سولفونیل‌اوره', TRUE, 70),
 ('meglitinide', 'مگلیتینید', TRUE, 80),
 ('insulin_basal', 'انسولین پایه', TRUE, 90),
 ('insulin_bolus', 'انسولین پراندیال (بولوس)', TRUE, 100),
 ('acei', 'مهارکنندهٔ ACE', FALSE, 110),
 ('arb', 'ARB', FALSE, 120),
 ('ccb', 'کلسیم‌بلاکر', FALSE, 130),
 ('thiazide', 'دیورتیک تیازیدی', FALSE, 140),
 ('statin', 'استاتین', FALSE, 150),
 ('ezetimibe', 'ازتیمایب', FALSE, 160),
 ('finerenone', 'فینرنون (nsMRA)', FALSE, 170),
 ('aspirin', 'آسپرین', FALSE, 180),
 ('beta_blocker', 'بتابلاکر', FALSE, 190),
 ('loop_diuretic', 'دیورتیک لوپ', FALSE, 200),
 ('fibrate', 'فیبرات', FALSE, 210),
 ('mra', 'آنتاگونیست گیرنده مینرالوکورتیکوئید', FALSE, 220),
 ('thyroid_agent', 'داروی تیروئید/لووتیروکسین', FALSE, 230),
 ('antithyroid', 'ضدتیروئید', FALSE, 240),
 ('other', 'سایر', FALSE, 999)
ON CONFLICT (tenant_id, class_key) DO NOTHING;

-- sms_templates (id ثابت)
INSERT INTO clinical.sms_templates (id, name, body) VALUES
 (1, 'یادآوری نوبت', 'سلام {name} عزیز، یادآوری نوبت شما در کلینیک تخصصی. لطفاً در زمان مقرر مراجعه فرمایید.'),
 (2, 'یادآوری تجدید دارو', 'سلام {name} عزیز، داروی شما رو به اتمام است. جهت تمدید نسخه با کلینیک تماس بگیرید.'),
 (3, 'دعوت به چکاپ دوره‌ای', 'سلام {name} عزیز، زمان چکاپ دوره‌ای شما فرارسیده است. برای حفظ سلامتی نوبت بگیرید.')
ON CONFLICT DO NOTHING;

-- engagement_events (routingِ پیش‌فرضِ رویداد→کانال)
INSERT INTO clinical.engagement_events
  (event_key, label, category, channel, sms_template, lead_days, cooldown_days, source_action, priority) VALUES
  ('appointment_reminder','یادآوری نوبت','operational','sms','سلام {name} عزیز، یادآوری نوبت شما در کلینیک تخصصی. لطفاً در زمان مقرر مراجعه فرمایید.',1,1,NULL,10),
  ('refill_due','یادآوری تجدید دارو','operational','sms','سلام {name} عزیز، داروی شما رو به اتمام است. جهت تمدید نسخه با کلینیک تماس بگیرید.',7,25,NULL,20),
  ('monitoring_due','سررسید آزمایش پایش','clinical','sms','سلام {name} عزیز، زمان آزمایشِ پایشِ دوره‌ای شما فرارسیده است. لطفاً نوبت بگیرید.',0,60,'create_followup',30),
  ('screening_due','سررسید غربالگری','clinical','sms','سلام {name} عزیز، زمان غربالگریِ دوره‌ای شما فرارسیده است. برای حفظ سلامتی نوبت بگیرید.',0,180,'schedule_screening',40),
  ('vaccine_due','سررسید واکسن','clinical','sms','سلام {name} عزیز، یک واکسنِ توصیه‌شده برای شما سررسید شده است. لطفاً با کلینیک هماهنگ کنید.',0,180,'vaccine',50),
  ('lapsed','بدون مراجعه اخیر','clinical','both','سلام {name} عزیز، مدتی است شما را در کلینیک ندیده‌ایم. برای ادامهٔ مراقبت نوبت بگیرید.',0,60,NULL,60),
  ('uncontrolled','کنترل‌نشده','clinical','worklist',NULL,0,14,NULL,70),
  ('red_flag','هشدار فوری بالینی','clinical','worklist',NULL,0,1,'redflag',80),
  ('visit_invite','دعوت به نوبت (پیامکی)','operational','sms','سلام {name} عزیز، برای ادامهٔ روند درمان لطفاً جهت تعیینِ نوبتِ ویزیت با کلینیک تماس بگیرید.',0,7,NULL,15),
  ('thank_you','تشکر پس از مراجعه','operational','sms','سلام {name} عزیز، از مراجعه و اعتمادِ شما به کلینیک سپاسگزاریم. سلامت و تندرست باشید.',0,1,NULL,16),
  ('ear_wash_invite','پیگیریِ شستشوی گوش','operational','sms','سلام {name} عزیز، جهتِ پیگیریِ شستشوی گوش در صورتِ نیاز با کلینیک هماهنگ کنید. اگر درد، ترشح یا کاهشِ شنوایی داشتید زودتر تماس بگیرید.',0,30,NULL,17),
  ('wound_care_invite','دعوتِ پانسمان/کشیدن بخیه','operational','sms','سلام {name} عزیز، برای تعویضِ پانسمان یا کشیدنِ بخیه لطفاً طبقِ زمانِ توصیه‌شدهٔ پزشک مراجعه کنید. برای هماهنگیِ نوبت تماس بگیرید.',0,30,NULL,18),
  ('lab_consult_invite','دعوتِ آزمایش و مشاوره','operational','sms','سلام {name} عزیز، طبقِ توصیهٔ پزشک برای انجامِ آزمایش و مشاورهٔ پیگیری لطفاً جهتِ تعیینِ نوبت با کلینیک تماس بگیرید.',0,14,NULL,19),
  ('bp_glucose_invite','یادآوریِ قند و فشار','operational','sms','سلام {name} عزیز، برای اندازه‌گیریِ دوره‌ایِ قند و فشارِ خون لطفاً جهتِ هماهنگیِ نوبت با کلینیک تماس بگیرید.',0,14,NULL,19)
ON CONFLICT (tenant_id, event_key) DO NOTHING;

-- ============================================================================
-- GRANTهای مرز برای جداولِ این برش (ADR-0007 §۲.۳)
--   ⚠️ ضروری: «GRANT … ON ALL TABLES IN SCHEMA clinical» در برشِ ۰ پیش از ساختِ این
--   جداول اجرا می‌شود، پس آن‌ها را پوشش نمی‌دهد. هر برش باید گرنتِ جداولِ خودش را تکرار
--   کند — وگرنه رولِ clinical_app نمی‌تواند در جداولِ خودش بنویسد (با اجرای واقعی روی
--   Postgres اثبات شد: پیش از این اصلاح، ۱ از ۳۵ جدول گرنت داشت). idempotent است.
-- ============================================================================
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA clinical TO clinical_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA clinical TO clinical_app;

-- ============================================================================
-- معیارِ «انجام‌شدهٔ» برشِ ۲ (برای تستِ نگهبان):
--   ۱) این فایل روی Postgresِ خالی که برشِ ۰ روی آن اجرا شده، بدونِ خطا اجرا شود
--      (idempotent: اجرای دوم هم سبز — CREATE … IF NOT EXISTS + ON CONFLICT DO NOTHING).
--   ۲) همهٔ FKهای patient_link_id → clinical.patient_links(id) برقرار شوند؛ درجِ ردیف با
--      patient_link_id نامعتبر → خطای FK.
--   ۳) seedها idempotent: اجرای دومِ INSERTها هیچ ردیفِ تکراری نسازد.
--   ۴) VIEW clinical.observations روی هر دو جدول کوئری‌پذیر باشد (UNION با obs_key مشترک).
--   ۵) لجرهای مرزی (processed_invoices/doctor_visit_log/campaign_audience) بدونِ FK به
--      accounting قابلِ درج‌اند (snapshotهای literal)؛ FK پس از برشِ ۳ افزوده می‌شود.
-- ============================================================================
