-- ============================================================================
-- پلتفرمِ یکپارچه — برشِ ۰ (هستهٔ runnable)  ·  PostgreSQL 13+
-- مرجع: ADR-0007 (هویتِ بیمار + مرزِ cross-schema + مدلِ داده) · ADR-0006 (ابریِ یکپارچه)
--
-- این کمینه‌ترین مجموعه‌ای است که مرزِ cross-schema را اثبات می‌کند:
--   platform.tenants → platform.users → accounting.patients → clinical.patient_links
-- روی همین می‌توان migration + تستِ نگهبانِ مرز را زد، بدونِ ساختِ ۵۰ جدولِ دیگر.
--
-- تصمیم‌های قفل‌شده (ADR-0007):
--   * سه schema: platform (مشترک) · accounting (مالکِ هویت+پول) · clinical
--   * هویتِ بیمار = Registry+Enrollment: accounting.patients مالکِ دموگرافی؛
--     clinical.patient_links یک رکوردِ enrollmentِ نازک با FK (نه کپیِ دموگرافی).
--   * مرزِ یک‌طرفه: فقط clinical → accounting (FK + GRANT فقط-SELECT).
--   * tenant_id ساختاری NOT NULL DEFAULT 1 — RLS موکول به T1 (اینجا فقط ساختار).
--   * پول = NUMERIC(14,0) (تومانِ صحیح؛ تصمیمِ مالک ۱۴۰۵/۰۳).
--   * زمان = timestamptz (کلاستر/سشن روی Asia/Tehran)؛ تاریخِ تقویمی = DATE (بدون shift).
--   * idiomها: AUTOINCREMENT→IDENTITY · BLOB→BYTEA · full_name VIRTUAL→STORED.
--
-- ⚠️ بدنهٔ accounting (invoices/items/تعرفه‌ها) عمداً اینجا نیست — تا عددِ DEVI-04
--    روی DBِ تولیدی و گیتِ سه-oracle قفل نشود (ADR-0006 §۸).
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS platform;
CREATE SCHEMA IF NOT EXISTS accounting;
CREATE SCHEMA IF NOT EXISTS clinical;

-- ---------------------------------------------------------------------------
-- platform.tenants — تنها جدولِ بدونِ tenant_id خودش
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS platform.tenants (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- مستأجرِ پیش‌فرض (تک‌مستأجریِ امروز = tenant 1)
INSERT INTO platform.tenants (id, name) VALUES (1, 'پیش‌فرض')
    ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- platform.users — سوپرستِ users دو اپ (webapp + specialist)
--   webapp: role(admin/manager/reception) + staff_id ؛ specialist: role(manager/staff)
--   + api_token/api_token_expires_at (پلِ نسخه‌نویسی، SECU-05). ستونِ app منشأ را تفکیک می‌کند.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS platform.users (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id             BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    username              TEXT NOT NULL,
    password_hash         BYTEA NOT NULL,                 -- bcrypt (BLOB→BYTEA)
    role                  TEXT NOT NULL DEFAULT 'staff' CHECK (role IN ('admin','manager','reception','doctor','staff')),  -- admin|manager|reception|doctor|staff
    app                   TEXT NOT NULL DEFAULT 'platform' CHECK (app IN ('accounting','clinical','platform')), -- 'accounting'|'clinical'|'platform' (منشأ/حوزه)
    full_name             TEXT,
    staff_id              BIGINT,                         -- accounting: لینک به medical_staff (cross-context؛ بعداً FK)
    api_token             TEXT,                           -- پلِ نسخه‌نویسی (clinical)
    api_token_expires_at  TIMESTAMPTZ,                    -- TTL توکن (SECU-05)
    is_active             BOOLEAN NOT NULL DEFAULT TRUE,
    failed_attempts       INTEGER NOT NULL DEFAULT 0,
    locked_until          TIMESTAMPTZ,
    last_login            TIMESTAMPTZ,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_tenant_username UNIQUE (tenant_id, username)
);
CREATE INDEX IF NOT EXISTS idx_users_api_token ON platform.users (api_token) WHERE api_token IS NOT NULL;

-- ---------------------------------------------------------------------------
-- accounting.patients — مالکِ canonicalِ هویت/دموگرافی (همان نقشِ امروز)
--   national_id → UNIQUE(tenant_id, national_id) ؛ uuid surrogate برای URL/توکنِ بیمار
--   (ADR-0007 §۲.۴: national_id دیگر credential نیست) ؛ full_name VIRTUAL→STORED.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS accounting.patients (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- BY DEFAULT همه‌جا (ORM-friendly: Django bulk_create/fixtures می‌تواند id صریح بدهد)
    tenant_id        BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    uuid             UUID NOT NULL DEFAULT gen_random_uuid(),               -- شناسهٔ بیرونیِ امن (نه national_id)
    name             TEXT NOT NULL,
    family_name      TEXT NOT NULL,
    full_name        TEXT GENERATED ALWAYS AS (name || ' ' || family_name) STORED,
    national_id      TEXT,
    phone_number     TEXT,
    birthdate        DATE,                                                  -- تاریخِ تقویمی (بدون timezone-shift)
    gender           TEXT,
    insurance_type   TEXT,
    insurance_expiry DATE,
    address          TEXT,
    is_foreign       BOOLEAN NOT NULL DEFAULT FALSE,
    created_by       TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_patients_tenant_national UNIQUE (tenant_id, national_id),
    CONSTRAINT uq_patients_uuid UNIQUE (uuid)
);
CREATE INDEX IF NOT EXISTS idx_patients_tenant_name ON accounting.patients (tenant_id, family_name, name);

-- ---------------------------------------------------------------------------
-- clinical.patient_links — رکوردِ enrollmentِ نازک (نه کپیِ دموگرافی)
--   تنها FKِ cross-schema مجاز: → accounting.patients(id). دموگرافی از آنجا خوانده می‌شود.
--   ستون‌های mirror (national_id/full_name/phone/gender/birthdate/address) حذف شدند.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS clinical.patient_links (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    patient_id      BIGINT NOT NULL REFERENCES accounting.patients(id) ON DELETE RESTRICT,  -- جایگزینِ accounting_patient_id
    wallet_balance  NUMERIC(14,0) NOT NULL DEFAULT 0,   -- اعتبارِ کیف‌پول (تومان)
    sms_opt_out     BOOLEAN NOT NULL DEFAULT FALSE,     -- انصراف از پیامکِ خودکار (گاردریلِ تعامل)
    sms_consent     BOOLEAN NOT NULL DEFAULT FALSE,     -- رضایتِ صریحِ پیامک (SECU-14a؛ پیش از KYC لازم)
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    enrolled_by     TEXT,
    enrolled_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    notes           TEXT,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_patient_links_tenant_patient UNIQUE (tenant_id, patient_id)
);

-- ============================================================================
-- مرزِ یک‌طرفه (ADR-0007 §۲.۳) — لایهٔ دسترسی: GRANT فقط-SELECT برای رولِ بالینی روی accounting.
-- (لایهٔ FK بالا فقط clinical→accounting است؛ لایهٔ import-linter در کدِ پایتون.)
-- رول‌ها کلاستر-level‌اند؛ این بلوک idempotent است.
-- ============================================================================
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'clinical_app') THEN
        CREATE ROLE clinical_app NOLOGIN;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'accounting_app') THEN
        CREATE ROLE accounting_app NOLOGIN;
    END IF;
END$$;

-- بالینی: نوشتن روی clinical، فقط-خواندن روی accounting (AccountingReadPort در سطحِ DB قفل می‌شود).
GRANT USAGE ON SCHEMA clinical, accounting, platform TO clinical_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA clinical TO clinical_app;
GRANT SELECT ON ALL TABLES IN SCHEMA accounting TO clinical_app;   -- فقط خواندن — هرگز نوشتن
GRANT SELECT ON ALL TABLES IN SCHEMA platform   TO clinical_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA accounting GRANT SELECT ON TABLES TO clinical_app;
-- جداولِ آیندهٔ clinical (که در برش‌های بعدی توسطِ همین نقش ساخته می‌شوند) خودکار به
-- clinical_app گرنت شوند — مکملِ footerِ GRANTِ هر برش (که جداولِ موجود را می‌پوشاند).
ALTER DEFAULT PRIVILEGES IN SCHEMA clinical GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO clinical_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA clinical GRANT USAGE, SELECT ON SEQUENCES TO clinical_app;

-- حسابداری: نوشتن روی accounting؛ هیچ دسترسی به clinical (وابستگیِ یک‌طرفه).
GRANT USAGE ON SCHEMA accounting, platform TO accounting_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA accounting TO accounting_app;
GRANT SELECT ON ALL TABLES IN SCHEMA platform TO accounting_app;

-- ============================================================================
-- معیارِ «انجام‌شدهٔ» برشِ ۰ (برای تستِ نگهبان):
--   ۱) این فایل روی Postgresِ خالی بدونِ خطا اجرا شود (idempotent: اجرای دوم هم سبز).
--   ۲) درجِ patient_link با patient_id نامعتبر → خطای FK (یک‌طرفه‌بودن اثبات).
--   ۳) UPDATE روی accounting.* با رولِ clinical_app → خطای permission (read-only اثبات).
--   ۴) full_name خودکار از name||' '||family_name پر شود (STORED).
--   ۵) uuid خودکار و یکتا تولید شود.
-- ============================================================================
