-- ============================================================================
-- schema_pg_slice10_suggestion_events.sql
-- برشِ ۱۰ — جدولِ append-only رویدادهایِ پیشنهادِ بالینی
--
-- هدف:
--   ثبتِ تاریخچهٔ کاملِ هر accept/dismiss/fired_daily برای سنجشِ پیامد.
--   جدولِ موجودِ suggestion_log (state/UI) دست‌نخورده می‌ماند.
--   این جدول append-only است: REVOKE UPDATE, DELETE از رول‌های اپ.
--
-- طراحی (قفل‌شده با data-scientist):
--   - fired_daily: یک ردیف per (tenant, patient_link, rule_code) در روز
--     برای suggestionهای pending (بدون actor).
--   - accepted / dismissed: از suggestion_action endpoint هر بار اقدام می‌شود
--     یک ردیف تازه INSERT می‌شود (نه overwrite → دو ردیف accept+dismiss مجاز).
--   - acted_by: برای fired_daily = NULL.
--   - suggestion_text: snapshotِ لحظهٔ اقدام.
--
-- وابستگی: بعد از slice0 (رول‌ها + tenants) + slice2 (clinical schema) + slice5 (RLS).
-- idempotent: CREATE TABLE IF NOT EXISTS + DROP POLICY IF EXISTS + ON CONFLICT DO NOTHING.
-- ============================================================================

-- ###########################################################################
-- ۱) جدولِ clinical.suggestion_events
-- ###########################################################################
CREATE TABLE IF NOT EXISTS clinical.suggestion_events (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    tenant_id           BIGINT NOT NULL REFERENCES platform.tenants(id),
    patient_link_id     BIGINT NOT NULL,   -- FK منطقی به clinical.patient_links.id
    rule_code           TEXT   NOT NULL,

    event_type          TEXT   NOT NULL
                               CHECK (event_type IN ('accepted', 'dismissed', 'fired_daily')),

    -- کاربرِ اقدام‌کننده (برای fired_daily = NULL)
    acted_by            TEXT,

    -- متنِ پیشنهاد در لحظهٔ اقدام (snapshot) — اختیاری
    suggestion_text     TEXT,

    -- سطحِ شواهد در لحظهٔ اقدام (snapshot) — اختیاری
    evidence_level      TEXT,

    -- یادداشتِ اختیاریِ پزشک
    note                TEXT,

    -- زمانِ رویداد — بک‌اند ISO، نه جلالی دست‌ساز
    occurred_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ###########################################################################
-- ۲) ایندکس‌ها
-- ###########################################################################

-- کوئریِ آمارِ per-rule (لیستِ rule_code + event_type در بازه زمانی)
CREATE INDEX IF NOT EXISTS idx_sug_events_rule_stats
    ON clinical.suggestion_events (tenant_id, rule_code, event_type, occurred_at DESC);

-- کوئریِ per-patient (تاریخچهٔ بیمار)
CREATE INDEX IF NOT EXISTS idx_sug_events_patient
    ON clinical.suggestion_events (tenant_id, patient_link_id, occurred_at DESC);

-- ###########################################################################
-- ۳) RLS — عیناً الگویِ sibling‌ها (slice5) + FORCE
-- ###########################################################################
ALTER TABLE clinical.suggestion_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE clinical.suggestion_events FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation ON clinical.suggestion_events;
CREATE POLICY tenant_isolation ON clinical.suggestion_events
    FOR ALL
    USING      (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::bigint)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::bigint);

-- ###########################################################################
-- ۴) GRANT — append-only: SELECT + INSERT فقط، هیچ UPDATE/DELETE
--    این خطِ قرمزِ طراحی است؛ تغییر ندهید.
--
--    نکتهٔ فنی: slice0 با ALTER DEFAULT PRIVILEGES UPDATE+DELETE به platform_app
--    برای جداولِ آیندهٔ clinical می‌دهد. برای override صریح از دو مسیر استفاده
--    می‌کنیم: REVOKE روی جدول + REVOKE DEFAULT PRIVILEGES.
-- ###########################################################################
GRANT SELECT, INSERT
    ON clinical.suggestion_events
    TO clinical_app, platform_app;

-- REVOKE روی این جدولِ خاص — تنها مکانیزمِ append-only (عیناً الگوی activity_logs
-- در slice2). این REVOKE بعد از CREATE + GRANTِ صریح + DEFAULT PRIVILEGEهای slice0
-- اجرا می‌شود و آن‌ها را پس می‌گیرد. **شرطِ درست‌کارکردن: slice10 باید بعد از slice2
-- اعمال شود** (slice2 یک GRANT بلنکتِ `ON ALL TABLES IN SCHEMA clinical` دارد که اگر
-- بعد از slice10 اجرا شود این REVOKE را خنثی می‌کند). ترتیبِ اعمالِ برش‌ها numeric است
-- (apply_schema/conftest/test_pg_schema با کلیدِ (major,suffix)) تا slice10 آخر بیاید.
--
-- توجه: از `ALTER DEFAULT PRIVILEGES ... REVOKE` استفاده نمی‌کنیم — آن یک side-effectِ
-- سراسری دارد (UPDATE/DELETE را از *همهٔ جداولِ آیندهٔ* clinical می‌گیرد، نه فقط این جدول).
REVOKE UPDATE, DELETE
    ON clinical.suggestion_events
    FROM clinical_app, platform_app;

-- ============================================================================
-- معیارِ «انجام‌شدهٔ» برشِ ۱۰ (برای تستِ نگهبان):
--   ۱) جدولِ clinical.suggestion_events وجود دارد با ستون‌های صحیح.
--   ۲) RLS فعال است با policy tenant_isolation + FORCE.
--   ۳) GRANT SELECT, INSERT به clinical_app و platform_app — بدونِ UPDATE/DELETE.
--   ۴) ایندکس‌های idx_sug_events_rule_stats و idx_sug_events_patient وجود دارند.
--   ۵) idempotency: اجرای مجدد بدونِ خطا.
-- ============================================================================
