-- ============================================================================
-- پلتفرمِ یکپارچه — برشِ ۳ (بدنهٔ حسابداری · schema accounting)  ·  PostgreSQL 13+
-- مرجع: ADR-0007 (هویتِ بیمار + مرزِ cross-schema + مدلِ داده) · ADR-0006 (ابریِ یکپارچه)
--        · ADR-0003 (پلِ read-only حسابداری → بالینی)
--
-- این برش، کلِ بدنهٔ schemaِ `accounting` را می‌سازد (برشِ ۰ از قبل سه schema + tenants
-- + users + accounting.patients + clinical.patient_links را ساخته است). همهٔ جداولِ مالی
-- اینجا به accounting.patients(id) / accounting.invoices(id) / accounting.medical_staff(id)
-- FK می‌زنند — همان قراردادِ patient_id/invoice_id/doctor_id/nurse_id در SQLite.
--
-- مبنای ترجمه = `webapp/src/adapters/sqlite/schema.sql` (منبعِ حقیقتِ حسابداری؛ خطوط ۱–۳۶۳).
--   جداولِ patients و users اینجا *دوباره ساخته نمی‌شوند* — patients در برشِ ۰ (accounting)
--   و users به‌صورتِ سوپرستِ دو اپ در برشِ ۰ (platform.users) ساخته شده‌اند.
--
-- تصمیم‌های قفل‌شده (ADR-0007 §۵ ضمیمه A — هم‌خانوادهٔ برشِ ۲):
--   * همه‌چیز در schema `accounting`؛ هر جدول `tenant_id BIGINT NOT NULL DEFAULT 1
--     REFERENCES platform.tenants(id)` به‌عنوانِ ستونِ دوم (RLS موکول به T1 — اینجا فقط ساختار).
--   * AUTOINCREMENT → BIGINT GENERATED BY DEFAULT AS IDENTITY (BY DEFAULT: preserve-id در
--     ETL با setval — همگام با accounting.patients در برشِ ۰).
--   * پول (REAL/INTEGER) → NUMERIC(14,0) تومانِ صحیح (تصمیمِ مالک ۱۴۰۵/۰۳؛ literal کپی).
--     ⚠️ هر ستونِ پولی تبدیل می‌شود، نه فقط ستون‌های آشکار (شاملِ unit_price/patient_amount/
--     insurance_amount/price_at_time/base_price/default_price/nursing_tariff/payroll و …).
--   * درصدها در payroll_settings (injection/procedure/tax/nursing/nurse_procedure_percent)
--     → NUMERIC(6,3) (درصدند، نه تومان — هرگز NUMERIC(14,0) نشوند).
--   * بولی‌های INTEGER (is_active/is_supplementary/is_base_tariff/nursing_covers/is_foreign/
--     covered_by_insurance/patient_provided/is_exception/is_paid) → BOOLEAN (1→TRUE، 0→FALSE).
--     اپ Django-from-scratch است (نه کدِ Flaskِ legacy با `=1`)، پس منطقِ مؤجلِ فاز-۱ افتاد؛
--     همان تصمیمِ برشِ ۲.
--   * زمان: لحظه‌ای (opened_at/closed_at/visit_date/injection_date/procedure_date/usage_date/
--     last_login/locked_until/shift_started_at/created_at/updated_at) → TIMESTAMPTZ DEFAULT
--     now() (جایی که منبع به‌صورتِ تهران-time پیش‌فرض داشت). تاریخِ تقویمیِ متنی (work_date/
--     birthdate/insurance_expiry) → DATE (بدونِ timezone-shift؛ TEXT 'YYYY-MM-DD' در SQLite).
--   * shift: TEXT و NULLABLE می‌ماند — بدونِ CHECK enum (شیفت‌ها per-clinic‌اند؛ تصمیمِ generality).
--   * UNIQUE(x) تک‌ستونیِ منبع → UNIQUE(tenant_id, x) (insurance_type/service_name/type_name/
--     name/staff_id/key). PKهای مرکب با tenant_id prefix می‌شوند.
--   * item_type/service_type/staff_type/performer_type → TEXT با CHECK (نه enum typeِ pg —
--     همان روشِ برشِ ۲). ⚠️ نامتقارنیِ منبع: services.service_type کامنت فقط 'visit'/'procedure'/
--     'consumable' دارد، ولی invoice_item_payments.item_type یک 'injection' هم اضافه می‌کند —
--     هرجا item_type است CHECK را به هر چهار مقدار یکپارچه می‌کنیم.
--   * INSERT OR IGNORE → INSERT … ON CONFLICT DO NOTHING (روی کلیدِ یکتای صریح).
--
-- ترتیبِ topological: medical_staff/insurance_schemes (parent) → invoices → visits/items →
-- کاتالوگ‌ها/لجرهای آیتمی → payroll/activity/shift/settings → indexes → seed.
-- اعتبارسنجیِ واقعی روی Postgres بعداً (این یک artifactِ طراحیِ ساخت‌شدنی است).
--
-- ⚠️ عمداً اینجا نیست (طبقِ ADR-0007):
--   * FKِ platform.users.staff_id → accounting.medical_staff (برشِ ۰ آن را soft-link گذاشت تا
--     وابستگیِ platform → accounting ساخته نشود).
--   * FKهای مرزِ clinical → accounting (processed_invoices/doctor_visit_log/campaign_audience
--     → accounting.invoices/patients): جداگانه در برشِ پیوندِ مرز افزوده می‌شوند.
--   * هیچ ALTERی روی accounting.patients (مالکِ هویت، در برشِ ۰ قفل شد).
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS accounting;

-- ###########################################################################
-- بخش ۱ — parentها (کادر درمان + کاتالوگِ بیمه؛ بدونِ FK به جداولِ تراکنشی)
-- ###########################################################################

-- ---------------------------------------------------------------------------
-- medical_staff — پزشکان و پرستاران. staff_type با CHECK محدود به doctor|nurse.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS accounting.medical_staff (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- BY DEFAULT: preserve-id در ETL
    tenant_id   BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    full_name   TEXT NOT NULL,
    staff_type  TEXT NOT NULL CHECK (staff_type IN ('doctor','nurse')),  -- doctor|nurse
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,                        -- بولی
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- insurance_schemes — کاتالوگِ بیمه‌های per-tenant (جدولِ جدید؛ در منبعِ SQLite نیست).
--   لیستِ عمومیِ بیمه‌ها؛ visit_tariffs به‌صورتِ forward-link به اینجا اشاره می‌کند.
--   code یکتا per-tenant → UNIQUE(tenant_id, code).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS accounting.insurance_schemes (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id         BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    code              TEXT NOT NULL,                       -- کلیدِ ماشین‌خوان (مثلِ 'free')
    name              TEXT NOT NULL,                       -- نامِ نمایشی (مثلِ 'آزاد')
    is_supplementary  BOOLEAN NOT NULL DEFAULT FALSE,      -- بیمهٔ تکمیلی؟ (بولی)
    is_base           BOOLEAN NOT NULL DEFAULT FALSE,      -- تعرفهٔ پایه/آزاد؟ (بولی)
    is_active         BOOLEAN NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_insurance_schemes_tenant_code UNIQUE (tenant_id, code)
);

-- ---------------------------------------------------------------------------
-- visit_tariffs — قیمت‌گذاریِ ویزیت per نوعِ بیمه. insurance_type یکتا → UNIQUE(tenant_id, …).
--   ⚠️ insurance_scheme_id: forward-link به insurance_schemes (NULLABLE — بدونِ NOT NULL،
--      تا ETL/مهاجرت بتواند بعداً پر کند).
--   ⚠️ باگِ پرستاری *عمداً حفظ می‌شود*: nursing_covers و nursing_tariff هر دو NOT NULL
--      DEFAULT 0 (نه nullable، نه "اصلاح‌شده") — رفتارِ منبع literal کپی شد.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS accounting.visit_tariffs (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id            BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    insurance_type       TEXT NOT NULL,                   -- نامِ تاریخیِ بیمه (یکتا per-tenant)
    insurance_scheme_id  BIGINT REFERENCES accounting.insurance_schemes(id),  -- forward-link (nullable)
    tariff_price         NUMERIC(14,0) NOT NULL DEFAULT 0,  -- پول → تومانِ صحیح
    nursing_tariff       NUMERIC(14,0) NOT NULL DEFAULT 0,  -- تعرفهٔ پرستاری (۰=رایگان) — باگ حفظ‌شده (NOT NULL)
    nursing_covers       BOOLEAN NOT NULL DEFAULT FALSE,    -- آیا پرستاری پوشش دارد؟ — باگ حفظ‌شده (NOT NULL)
    is_active            BOOLEAN NOT NULL DEFAULT TRUE,      -- بولی
    is_supplementary     BOOLEAN NOT NULL DEFAULT FALSE,     -- بولی
    is_base_tariff       BOOLEAN NOT NULL DEFAULT FALSE,     -- تعرفهٔ پایه/آزاد؟ (بولی)
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_visit_tariffs_tenant_insurance UNIQUE (tenant_id, insurance_type)
);

-- ###########################################################################
-- بخش ۲ — فاکتورها و ویزیت‌ها (ظرفِ اصلیِ صورتحساب)
-- ###########################################################################

-- ---------------------------------------------------------------------------
-- invoices — فاکتورها (ظرفِ اصلیِ صورتحسابِ بیمار). FK patient_id → patients،
--   doctor_id/nurse_id → medical_staff. total_amount ستونِ ذخیره‌شدهٔ ساده است (نه generated).
--   insurance_type/supplementary_insurance به‌عنوانِ snapshotِ تاریخی TEXT می‌مانند (بدونِ FK).
--   ⚠️ UNIQUE(tenant_id, id): لازم تا لجرهای مرزِ بالینی بعداً بتوانند با (tenant_id, id)
--      به این جدول FK بزنند (FKِ مرکب نیازِ کلیدِ یکتای مرکب دارد).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS accounting.invoices (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id                BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    patient_id               BIGINT NOT NULL REFERENCES accounting.patients(id),
    doctor_id                BIGINT REFERENCES accounting.medical_staff(id),
    nurse_id                 BIGINT REFERENCES accounting.medical_staff(id),
    status                   TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','closed')),  -- open|closed
    insurance_type           TEXT,                          -- snapshotِ تاریخی (بدونِ FK)
    supplementary_insurance  TEXT,                          -- snapshotِ تاریخی (بدونِ FK)
    total_amount             NUMERIC(14,0) NOT NULL DEFAULT 0,  -- پول → تومان (ستونِ ساده، نه generated)
    work_date                DATE,                          -- تاریخِ کارِ تقویمی (دستی)
    shift                    TEXT,                          -- per-clinic (بدونِ CHECK enum)
    opened_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    closed_at                TIMESTAMPTZ,
    opened_by                TEXT,
    opened_by_name           TEXT,
    closed_by                TEXT,
    closed_by_name           TEXT,
    CONSTRAINT uq_invoices_tenant_id UNIQUE (tenant_id, id)  -- هدفِ FKِ مرکبِ لجرهای بالینی
);

-- ---------------------------------------------------------------------------
-- visits — ویزیت‌ها (وابسته به فاکتور). price → NUMERIC(14,0). visit_date لحظه → TIMESTAMPTZ.
--   work_date تقویمی → DATE. UNIQUE(tenant_id, id) برای FKِ مرکبِ احتمالیِ بعدی.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS accounting.visits (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id                BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    patient_id               BIGINT NOT NULL REFERENCES accounting.patients(id),
    doctor_name              TEXT,
    visit_date               TIMESTAMPTZ NOT NULL DEFAULT now(),  -- لحظه‌ای
    shift                    TEXT,                          -- per-clinic (بدونِ CHECK enum)
    work_date                DATE,                          -- تاریخِ کارِ تقویمی (دستی)
    insurance_type           TEXT,
    supplementary_insurance  TEXT,
    status                   TEXT NOT NULL DEFAULT 'pending',
    price                    NUMERIC(14,0) NOT NULL DEFAULT 0,  -- پول → تومان
    payment_status           TEXT NOT NULL DEFAULT 'unpaid' CHECK (payment_status IN ('unpaid','paid')), -- unpaid|paid
    reception_user           TEXT,
    notes                    TEXT,
    invoice_id               BIGINT REFERENCES accounting.invoices(id),
    doctor_id                BIGINT REFERENCES accounting.medical_staff(id),
    nurse_id                 BIGINT REFERENCES accounting.medical_staff(id),
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_visits_tenant_id UNIQUE (tenant_id, id)
);

-- ---------------------------------------------------------------------------
-- services — کاتالوگِ خدمات/آیتم‌ها (تعرفه‌ها). base_price → NUMERIC(14,0).
--   service_type با CHECK یکپارچه‌شده به هر چهار مقدار (هم‌خوان با item_type؛ بالا را ببین).
--   ⚠️ منبع unique ندارد → اینجا هم بدونِ UNIQUE می‌ماند (طبقِ ground-ruleِ برش).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS accounting.services (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    name          TEXT NOT NULL,
    base_price    NUMERIC(14,0) NOT NULL,                  -- پول → تومان
    service_type  TEXT NOT NULL CHECK (service_type IN ('visit','injection','procedure','consumable'))
);

-- ---------------------------------------------------------------------------
-- visit_items — اقلامِ یک ویزیت. FK visit_id → visits، service_id → services.
--   price_at_time → NUMERIC(14,0) (snapshotِ قیمتِ لحظهٔ ثبت).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS accounting.visit_items (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    visit_id       BIGINT NOT NULL REFERENCES accounting.visits(id),
    service_id     BIGINT NOT NULL REFERENCES accounting.services(id),
    quantity       INTEGER NOT NULL DEFAULT 1,
    price_at_time  NUMERIC(14,0) NOT NULL                  -- پول → تومان (snapshotِ قیمت)
);

-- ###########################################################################
-- بخش ۳ — کاتالوگ‌ها و لجرهای پرستاری/تزریق/پروسیجر/مصرفی
-- ###########################################################################

-- ---------------------------------------------------------------------------
-- nursing_services — کاتالوگِ خدماتِ پرستاری. service_name یکتا → UNIQUE(tenant_id, …).
--   unit_price → NUMERIC(14,0).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS accounting.nursing_services (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    service_name  TEXT NOT NULL,
    unit_price    NUMERIC(14,0) NOT NULL DEFAULT 0,        -- پول → تومان
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,           -- بولی
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_nursing_services_tenant_name UNIQUE (tenant_id, service_name)
);

-- ---------------------------------------------------------------------------
-- injection_types — کاتالوگِ انواعِ تزریق. type_name یکتا → UNIQUE(tenant_id, …).
--   base_price → NUMERIC(14,0).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS accounting.injection_types (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    type_name   TEXT NOT NULL,
    base_price  NUMERIC(14,0) NOT NULL DEFAULT 0,          -- پول → تومان
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,             -- بولی
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_injection_types_tenant_name UNIQUE (tenant_id, type_name)
);

-- ---------------------------------------------------------------------------
-- injections — تزریقات/خدماتِ پرستاری. FK patient_id، service_id → nursing_services،
--   invoice_id → invoices، doctor_id/nurse_id → medical_staff. injection_date لحظه → TIMESTAMPTZ.
--   work_date تقویمی → DATE. همهٔ ستون‌های پولی → NUMERIC(14,0). covered_by_insurance → BOOLEAN.
--   ⚠️ patient_amount/insurance_amount در منبع DEFAULT NULL دارند (تفکیکِ "محاسبه‌نشده") — حفظ شد.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS accounting.injections (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id             BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    patient_id            BIGINT NOT NULL REFERENCES accounting.patients(id),
    injection_type        TEXT NOT NULL,
    service_id            BIGINT REFERENCES accounting.nursing_services(id),
    injection_date        TIMESTAMPTZ NOT NULL DEFAULT now(),  -- لحظه‌ای
    shift                 TEXT,                            -- per-clinic (بدونِ CHECK enum)
    work_date             DATE,                            -- تاریخِ کارِ تقویمی (دستی)
    count                 INTEGER NOT NULL DEFAULT 1,
    unit_price            NUMERIC(14,0) NOT NULL DEFAULT 0,  -- پول → تومان
    total_price           NUMERIC(14,0) NOT NULL DEFAULT 0,  -- پول → تومان
    patient_amount        NUMERIC(14,0) DEFAULT NULL,        -- سهمِ بیمار (NULL=محاسبه‌نشده) → تومان
    insurance_amount      NUMERIC(14,0) DEFAULT NULL,        -- سهمِ بیمه (NULL=محاسبه‌نشده) → تومان
    covered_by_insurance  BOOLEAN NOT NULL DEFAULT FALSE,    -- بولی
    reception_user        TEXT,
    notes                 TEXT,
    invoice_id            BIGINT REFERENCES accounting.invoices(id),
    doctor_id             BIGINT REFERENCES accounting.medical_staff(id),
    nurse_id              BIGINT REFERENCES accounting.medical_staff(id)
);

-- ---------------------------------------------------------------------------
-- procedures — کارهای عملی (پانسمان و …). FK patient_id، invoice_id، doctor_id/nurse_id.
--   procedure_date لحظه → TIMESTAMPTZ. work_date تقویمی → DATE. price → NUMERIC(14,0).
--   ⚠️ performer_id polymorphic است (doctor یا nurse) → بدونِ FK (همان منبع). performer_type TEXT.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS accounting.procedures (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    patient_id      BIGINT NOT NULL REFERENCES accounting.patients(id),
    procedure_type  TEXT NOT NULL,
    procedure_date  TIMESTAMPTZ NOT NULL DEFAULT now(),    -- لحظه‌ای
    shift           TEXT,                                  -- per-clinic (بدونِ CHECK enum)
    work_date       DATE,                                  -- تاریخِ کارِ تقویمی (دستی)
    price           NUMERIC(14,0) NOT NULL DEFAULT 0,      -- پول → تومان
    reception_user  TEXT,
    notes           TEXT,
    invoice_id      BIGINT REFERENCES accounting.invoices(id),
    performer_type  TEXT CHECK (performer_type IN ('doctor','nurse')),  -- doctor|nurse (polymorphic)
    performer_id    BIGINT,                                -- بدونِ FK (polymorphic: doctor یا nurse)
    doctor_id       BIGINT REFERENCES accounting.medical_staff(id),
    nurse_id        BIGINT REFERENCES accounting.medical_staff(id)
);

-- ---------------------------------------------------------------------------
-- procedure_tariffs — کاتالوگِ تعرفهٔ کارهای عملی. name یکتا → UNIQUE(tenant_id, …).
--   unit_price → NUMERIC(14,0).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS accounting.procedure_tariffs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    name        TEXT NOT NULL,
    unit_price  NUMERIC(14,0) NOT NULL DEFAULT 0,          -- پول → تومان
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,             -- بولی
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_procedure_tariffs_tenant_name UNIQUE (tenant_id, name)
);

-- ---------------------------------------------------------------------------
-- consumables_ledger — دفترِ مصرفی‌ها/داروها. FK patient_id، invoice_id، doctor_id/nurse_id.
--   usage_date لحظه → TIMESTAMPTZ. work_date تقویمی → DATE. unit_price/total_cost → NUMERIC(14,0).
--   patient_provided/is_exception → BOOLEAN. category TEXT (drug|supply).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS accounting.consumables_ledger (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id         BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    patient_id        BIGINT REFERENCES accounting.patients(id),
    item_name         TEXT NOT NULL,
    category          TEXT CHECK (category IN ('drug','supply')),  -- drug|supply
    quantity          NUMERIC(14,3) NOT NULL DEFAULT 1,    -- تعداد (REAL منبع — کسری ممکن: ۰.۵ ویال؛ scale=3 برای وفاداری)
    unit_price        NUMERIC(14,0) NOT NULL DEFAULT 0,    -- پول → تومان
    total_cost        NUMERIC(14,0) NOT NULL DEFAULT 0,    -- پول → تومان
    patient_provided  BOOLEAN NOT NULL DEFAULT FALSE,      -- بولی (بیمار خودش آورده)
    is_exception      BOOLEAN NOT NULL DEFAULT FALSE,      -- بولی (قلمِ استثنا/تعریف‌نشده)
    usage_date        TIMESTAMPTZ NOT NULL DEFAULT now(),  -- لحظه‌ای
    shift             TEXT,                                -- per-clinic (بدونِ CHECK enum)
    work_date         DATE,                                -- تاریخِ کارِ تقویمی (دستی)
    reception_user    TEXT,
    notes             TEXT,
    invoice_id        BIGINT REFERENCES accounting.invoices(id),
    doctor_id         BIGINT REFERENCES accounting.medical_staff(id),
    nurse_id          BIGINT REFERENCES accounting.medical_staff(id)
);

-- ---------------------------------------------------------------------------
-- consumable_tariffs — تعرفهٔ یکپارچهٔ مصرفی‌ها و داروها. name یکتا → UNIQUE(tenant_id, …).
--   default_price → NUMERIC(14,0). category TEXT (supply|drug).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS accounting.consumable_tariffs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    name           TEXT NOT NULL,
    default_price  NUMERIC(14,0) NOT NULL DEFAULT 0,       -- پول → تومان
    category       TEXT NOT NULL CHECK (category IN ('supply','drug')),  -- supply|drug
    is_active      BOOLEAN NOT NULL DEFAULT TRUE,          -- بولی
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_consumable_tariffs_tenant_name UNIQUE (tenant_id, name)
);

-- ---------------------------------------------------------------------------
-- insurance_nursing_exclusions — استثناهای بیمه برای خدماتِ پرستاری.
--   FK nursing_service_id → nursing_services. insurance_type TEXT می‌ماند (snapshotِ تاریخی).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS accounting.insurance_nursing_exclusions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    insurance_type      TEXT NOT NULL,                     -- نامِ بیمه (snapshot؛ بدونِ FK)
    nursing_service_id  BIGINT NOT NULL REFERENCES accounting.nursing_services(id),
    note                TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ###########################################################################
-- بخش ۴ — پرداختِ آیتمی، حقوق، لاگ، شیفت و تنظیمات
-- ###########################################################################

-- ---------------------------------------------------------------------------
-- invoice_item_payments — وضعیتِ پرداختِ هر آیتمِ فاکتور. FK invoice_id → invoices.
--   surrogate id (BIGINT IDENTITY PK — Django ORM با PKِ مرکب ناسازگار است)؛ کلیدِ طبیعیِ
--   منبع (tenant_id, invoice_id, item_type, item_id) اکنون به‌صورتِ CONSTRAINT UNIQUE حفظ
--   می‌شود. is_paid → BOOLEAN. item_type با CHECK یکپارچه‌شده (هر چهار مقدار).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS accounting.invoice_item_payments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    invoice_id    BIGINT NOT NULL REFERENCES accounting.invoices(id),
    item_type     TEXT NOT NULL CHECK (item_type IN ('visit','injection','procedure','consumable')),
    item_id       BIGINT NOT NULL,
    payment_type  TEXT,                                    -- cash|card|insurance
    is_paid       BOOLEAN NOT NULL DEFAULT FALSE,          -- بولی
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_invoice_item_payments UNIQUE (tenant_id, invoice_id, item_type, item_id)
);

-- ---------------------------------------------------------------------------
-- payroll_settings — تنظیماتِ حقوقِ کادر درمان. FK staff_id → medical_staff (یکتا per-tenant).
--   ⚠️ مهاجرتِ literal: هر ۹ ستونِ نام‌دار عیناً نگه داشته می‌شوند —
--      پولی (base_morning/base_evening/base_night/visit_fee) → NUMERIC(14,0)؛
--      درصدی (injection/procedure/tax/nursing/nurse_procedure_percent) → NUMERIC(6,3).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS accounting.payroll_settings (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id                BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    staff_id                 BIGINT NOT NULL REFERENCES accounting.medical_staff(id),
    base_morning             NUMERIC(14,0) NOT NULL DEFAULT 0,  -- پول → تومان
    base_evening             NUMERIC(14,0) NOT NULL DEFAULT 0,  -- پول → تومان
    base_night               NUMERIC(14,0) NOT NULL DEFAULT 0,  -- پول → تومان
    visit_fee                NUMERIC(14,0) NOT NULL DEFAULT 0,  -- پول → تومان
    injection_percent        NUMERIC(6,3) NOT NULL DEFAULT 0 CHECK (injection_percent BETWEEN 0 AND 100),   -- درصد (نه تومان)
    procedure_percent        NUMERIC(6,3) NOT NULL DEFAULT 0 CHECK (procedure_percent BETWEEN 0 AND 100),   -- درصد
    tax_percent              NUMERIC(6,3) NOT NULL DEFAULT 0 CHECK (tax_percent BETWEEN 0 AND 100),   -- درصد
    nursing_percent          NUMERIC(6,3) NOT NULL DEFAULT 0 CHECK (nursing_percent BETWEEN 0 AND 100),   -- درصد
    nurse_procedure_percent  NUMERIC(6,3) NOT NULL DEFAULT 0 CHECK (nurse_procedure_percent BETWEEN 0 AND 100),   -- درصد
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_payroll_settings_tenant_staff UNIQUE (tenant_id, staff_id)
);

-- ---------------------------------------------------------------------------
-- activity_logs — لاگِ فعالیتِ کاربران. user_id → platform.users (cross-schema به platform مجاز)،
--   invoice_id → invoices، patient_id → patients. amount → NUMERIC(14,0). created_at لحظه → TIMESTAMPTZ.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS accounting.activity_logs (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    user_id          BIGINT REFERENCES platform.users(id),  -- cross-schema به platform (مجاز)
    username         TEXT,
    action_type      TEXT NOT NULL,
    action_category  TEXT NOT NULL,
    description      TEXT,
    target_type      TEXT,
    target_id        BIGINT,
    target_name      TEXT,
    invoice_id       BIGINT REFERENCES accounting.invoices(id),
    patient_id       BIGINT REFERENCES accounting.patients(id),
    patient_name     TEXT,
    amount           NUMERIC(14,0) NOT NULL DEFAULT 0,      -- پول → تومان
    old_value        TEXT,
    new_value        TEXT,
    ip_address       TEXT,
    user_agent       TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- user_active_shift — شیفتِ فعالِ کاربر (تغییرِ دستیِ مستقل از ساعت).
--   ⚠️ منبع PKِ user_id دارد؛ اینجا برای tenant_id به (id IDENTITY PK + UNIQUE(tenant_id,
--      user_id)) بازنویسی شد. user_id → platform.users. active_shift TEXT NOT NULL.
--      work_date تقویمی → DATE. shift_started_at لحظه → TIMESTAMPTZ.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS accounting.user_active_shift (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id         BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    user_id           BIGINT NOT NULL REFERENCES platform.users(id),  -- cross-schema به platform (مجاز)
    active_shift      TEXT NOT NULL,                       -- per-clinic (بدونِ CHECK enum)
    work_date         DATE NOT NULL,                       -- تاریخِ کارِ تقویمی
    shift_started_at  TIMESTAMPTZ NOT NULL DEFAULT now(),  -- لحظه‌ای
    CONSTRAINT uq_user_active_shift_tenant_user UNIQUE (tenant_id, user_id)
);

-- ---------------------------------------------------------------------------
-- settings — تنظیماتِ سیستمِ حسابداری. key یکتا → UNIQUE(tenant_id, key).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS accounting.settings (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    key         TEXT NOT NULL,
    value       TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_settings_tenant_key UNIQUE (tenant_id, key)
);

-- ###########################################################################
-- بخش ۵ — ایندکس‌های کارایی (بازسازیِ schema.sql خطوط ۳۲۶–۳۶۲ با tenant_id پیشرو)
-- ###########################################################################

-- invoices: فیلترِ پرتکرار بر status/work_date/shift (tenant_id پیشرو جایی که طبیعی است)
CREATE INDEX IF NOT EXISTS idx_invoices_status ON accounting.invoices (tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_invoices_work_date ON accounting.invoices (tenant_id, work_date);
CREATE INDEX IF NOT EXISTS idx_invoices_patient_id ON accounting.invoices (patient_id);
CREATE INDEX IF NOT EXISTS idx_invoices_status_opened_at ON accounting.invoices (tenant_id, status, opened_at DESC);

-- visits: join/فیلتر بر invoice_id/work_date/patient_id
CREATE INDEX IF NOT EXISTS idx_visits_invoice_id ON accounting.visits (invoice_id);
CREATE INDEX IF NOT EXISTS idx_visits_work_date ON accounting.visits (tenant_id, work_date);
CREATE INDEX IF NOT EXISTS idx_visits_patient_id ON accounting.visits (patient_id);

-- injections: join/فیلتر بر invoice_id/work_date/patient_id
CREATE INDEX IF NOT EXISTS idx_injections_invoice_id ON accounting.injections (invoice_id);
CREATE INDEX IF NOT EXISTS idx_injections_work_date ON accounting.injections (tenant_id, work_date);
CREATE INDEX IF NOT EXISTS idx_injections_patient_id ON accounting.injections (patient_id);

-- procedures: join/فیلتر بر invoice_id/work_date/patient_id
CREATE INDEX IF NOT EXISTS idx_procedures_invoice_id ON accounting.procedures (invoice_id);
CREATE INDEX IF NOT EXISTS idx_procedures_work_date ON accounting.procedures (tenant_id, work_date);
CREATE INDEX IF NOT EXISTS idx_procedures_patient_id ON accounting.procedures (patient_id);

-- consumables: join/فیلتر بر invoice_id/work_date
CREATE INDEX IF NOT EXISTS idx_consumables_invoice_id ON accounting.consumables_ledger (invoice_id);
CREATE INDEX IF NOT EXISTS idx_consumables_work_date ON accounting.consumables_ledger (tenant_id, work_date);

-- activity logs: فیلترِ پرتکرار بر تاریخ/کاربر/فاکتور
CREATE INDEX IF NOT EXISTS idx_activity_logs_created_at ON accounting.activity_logs (tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_activity_logs_user_id ON accounting.activity_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_activity_logs_invoice_id ON accounting.activity_logs (invoice_id);

-- medical staff: فیلتر بر نوع و وضعیتِ فعال
CREATE INDEX IF NOT EXISTS idx_medical_staff_type_active ON accounting.medical_staff (tenant_id, staff_type, is_active);

-- payments: کوئریِ پرتکرار بر invoice_id
CREATE INDEX IF NOT EXISTS idx_payments_invoice_id ON accounting.invoice_item_payments (invoice_id);

-- ============================================================================
-- GRANTهای مرز برای جداولِ این برش (ADR-0007 §۲.۳)
--   ⚠️ ضروری: «GRANT … ON ALL TABLES IN SCHEMA accounting» در برشِ ۰ پیش از ساختِ این
--   جداول اجرا می‌شود، پس آن‌ها را پوشش نمی‌دهد — هر برش باید گرنتِ جداولِ خودش را تکرار
--   کند (همان درسِ برشِ ۲). مرزِ یک‌طرفه: accounting_app می‌نویسد، clinical_app فقط می‌خواند.
--   idempotent است.
-- ============================================================================
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA accounting TO accounting_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA accounting TO accounting_app;
GRANT SELECT ON ALL TABLES IN SCHEMA accounting TO clinical_app;   -- فقط خواندنِ یک‌طرفه

-- ============================================================================
-- بخش ۶ — Seedِ بوت‌استرپ (فقط راه‌اندازی — هیچ دادهٔ Sib)
--   ⚠️ دقیقاً یک ردیفِ خنثیٰ idempotent: بیمهٔ «آزاد» به‌عنوانِ پایه. هیچ تعرفه/کاتالوگ/
--      بیمهٔ واقعی اینجا seed نمی‌شود — همه per-tenant config‌اند و در زمانِ اجرا ساخته
--      می‌شوند. (اسکریپتِ قدیمیِ webapp/scripts/seed_clinic_data.py مخصوصِ Sib است و عمداً
--      منتقل نشد — دادهٔ یک کلینیکِ خاص در schemaِ یکپارچهٔ چندمستأجری جا ندارد.)
-- ============================================================================
INSERT INTO accounting.insurance_schemes (tenant_id, code, name, is_base)
    VALUES (1, 'free', 'آزاد', TRUE)
    ON CONFLICT (tenant_id, code) DO NOTHING;

-- ============================================================================
-- معیارِ «انجام‌شدهٔ» برشِ ۳ (برای تستِ نگهبان):
--   ۱) این فایل روی Postgresِ خالی که برشِ ۰ روی آن اجرا شده، بدونِ خطا اجرا شود
--      (idempotent: اجرای دوم هم سبز — CREATE … IF NOT EXISTS + ON CONFLICT DO NOTHING
--      + CREATE INDEX IF NOT EXISTS).
--   ۲) هر ستونِ پولی NUMERIC(14,0) باشد (هیچ REAL/INTEGERِ پول نماند)؛ درصدهای payroll
--      NUMERIC(6,3) باشند (نه تومان).
--   ۳) همهٔ UNIQUEهای تک‌ستونیِ منبع به UNIQUE(tenant_id, …) مرکب تبدیل شده باشند؛
--      invoice_item_payments دارای surrogate id (IDENTITY PK) باشد و کلیدِ طبیعیِ
--      (tenant_id, invoice_id, item_type, item_id) به‌صورتِ CONSTRAINT UNIQUE حفظ شده باشد.
--   ۴) باگِ پرستاریِ visit_tariffs حفظ شده باشد: nursing_covers و nursing_tariff هر دو
--      NOT NULL DEFAULT 0 (نه nullable، نه "اصلاح‌شده").
--   ۵) accounting.invoices دارای UNIQUE(tenant_id, id) باشد (هدفِ FKِ مرکبِ لجرهای بالینی).
--   ۶) seed فقط یک ردیفِ بیمهٔ 'free' بسازد؛ اجرای دوم ردیفِ تکراری نسازد (هیچ دادهٔ Sib).
--   ۷) درجِ ردیف با patient_id/invoice_id/staff_id نامعتبر → خطای FK (یکپارچگیِ مرجع اثبات).
--   ۸) UPDATE روی accounting.* با رولِ clinical_app → خطای permission (read-only اثبات).
--
-- 📌 یادداشتِ ETL (مهاجرتِ داده): چند ستون که در SQLite ضمنی nullable بودند، اینجا NOT NULL
--    سخت شده‌اند (invoices.total_amount, invoices.status, visits.status/payment_status,
--    visit_tariffs.nursing_covers/nursing_tariff). ETL باید پیش از درج، NULLِ ردیف‌های قدیمی
--    را به DEFAULT (۰ یا مقدارِ پیش‌فرض) coerce کند تا درج نشکند. (یافتهٔ code-review.)
-- ============================================================================
