-- ============================================================================
-- پلتفرمِ یکپارچه — Batch 4b (domain model additions — clinical model)
-- PostgreSQL 13+
--
-- پیش‌نیاز: برش‌های ۰ / ۲_clinical / ۲b_fk_catalog / ۳_accounting / ۴_boundary / ۴a_domain_polish
--           پیش از این فایل اعمال شده باشند (ترتیبِ sorted name).
--           پس از اجرا، accounting.* و clinical.* کاملاً موجودند.
--
-- تغییرات:
--   ۱) clinical.encounters  — جدولِ جدیدِ ویزیت/ارتباطِ بالینی
--      * FKهای مرکبِ tenant-safe به: patient_links، appointments، medical_staff، invoices
--      * FKِ cross-schema clinical→accounting (جهتِ مجاز): doctor_id و accounting_invoice_id
--      * DEFERRABLE INITIALLY DEFERRED برای accounting_invoice_id (همانِ الگوی slice4)
--      * updated_at trigger (از تابعِ clinical.set_updated_at که slice4a ساخته)
--      * UNIQUE(tenant_id, id) برای هدف‌گیریِ FKِ مرکبِ childها
--
--   ۲) اضافهٔ encounter_id (nullable) به جداولِ زیر:
--      * clinical.vital_readings     — FKِ مرکب → encounters(tenant_id, id)
--      * clinical.lab_results        — FKِ مرکب → encounters(tenant_id, id)
--      * clinical.clinical_notes     — FKِ مرکب → encounters(tenant_id, id)
--      * clinical.prescriptions      — FKِ مرکب → encounters(tenant_id, id)
--      * clinical.doctor_visit_log   — FKِ soft (nullable BIGINT، بدونِ FK واقعی — توضیح پایین)
--
--   ۳) ستون‌های structured dose به clinical.patient_medications:
--      dose_value NUMERIC(10,3), dose_unit TEXT, frequency TEXT با CHECK،
--      route TEXT با CHECK — همه nullable (additive، ایمنِ re-run)
--
--   ۴) clinical.prescription_items — جدولِ جدیدِ اقلامِ نسخه
--      * UNIQUE(tenant_id, id) روی clinical.prescriptions (پیش‌نیازِ FKِ مرکب)
--      * drug_class FKِ soft (nullable + ON DELETE SET NULL) — دلیل: drug_catalog seedها
--        پیش از این slice از Python bootstrap وارد می‌شوند؛ FK واقعی ریسک orphan دارد.
--
--   ۵) doctor_id + chief_complaint به clinical.appointments
--      * FKِ مرکب cross-schema (tenant_id, doctor_id) → accounting.medical_staff(tenant_id, id)
--        ON DELETE SET NULL (جهتِ مجازِ clinical→accounting)
--
-- idempotency:
--   * CREATE TABLE IF NOT EXISTS
--   * ALTER TABLE … ADD COLUMN IF NOT EXISTS   (Pg13+)
--   * DO $$ IF NOT EXISTS (pg_constraint) …    برای CHECKها و FK
--   * DROP TRIGGER IF EXISTS → CREATE TRIGGER  برای triggerها
-- ============================================================================

-- ###########################################################################
-- ۱) UNIQUE(tenant_id, id) روی clinical.prescriptions
--    پیش‌نیازِ FKِ مرکبِ prescription_items → prescriptions (Batch 4b §۴)
-- ###########################################################################
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'clinical.prescriptions'::regclass
          AND conname   = 'uq_prescriptions_tenant_id'
    ) THEN
        ALTER TABLE clinical.prescriptions
            ADD CONSTRAINT uq_prescriptions_tenant_id
            UNIQUE (tenant_id, id);
    END IF;
END$$;

-- ###########################################################################
-- ۲) clinical.encounters — جدولِ جدیدِ ویزیت/ارتباطِ بالینی
-- ###########################################################################
CREATE TABLE IF NOT EXISTS clinical.encounters (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id               BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    -- FK مرکب composite → cross-tenant reference ساختاراً غیرممکن
    patient_link_id         BIGINT NOT NULL,
    -- doctor_id: cross-schema FKِ مجاز (clinical → accounting)
    doctor_id               BIGINT,                              -- nullable؛ ON DELETE SET NULL
    encounter_type          TEXT NOT NULL DEFAULT 'visit'
                            CHECK (encounter_type IN ('visit','follow_up','phone','remote')),
    encounter_at            TIMESTAMPTZ NOT NULL,
    chief_complaint         TEXT,
    status                  TEXT NOT NULL DEFAULT 'open'
                            CHECK (status IN ('open','completed','cancelled')),
    completed_at            TIMESTAMPTZ,                         -- nullable، بدونِ DEFAULT
    summary_note            TEXT,
    -- appointment_id: FKِ مرکب به appointments (nullable)
    appointment_id          BIGINT,                              -- ON DELETE SET NULL
    -- accounting_invoice_id: cross-schema FKِ مجاز (clinical → accounting) DEFERRABLE
    accounting_invoice_id   BIGINT,                              -- nullable snapshot؛ DEFERRABLE
    created_by              TEXT,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Tenant-safety: UNIQUE(tenant_id, id) برای هدفِ FKِ مرکبِ childها
    CONSTRAINT uq_encounters_tenant_id UNIQUE (tenant_id, id),

    -- FK مرکب به patient_links (cross-tenant rejection)
    CONSTRAINT fk_encounters_patient FOREIGN KEY (tenant_id, patient_link_id)
        REFERENCES clinical.patient_links (tenant_id, id),

    -- FK مرکب به appointments (اختیاری؛ SET NULL هنگامِ حذفِ نوبت)
    -- appointments.uq_appointments_tenant_id موجود است (slice2b) ✓
    CONSTRAINT fk_encounters_appointment FOREIGN KEY (tenant_id, appointment_id)
        REFERENCES clinical.appointments (tenant_id, id)
        ON DELETE SET NULL,

    -- FK مرکب cross-schema: doctor_id → accounting.medical_staff (جهتِ مجاز)
    -- accounting.medical_staff.uq_medical_staff_tenant_id موجود است (slice3) ✓
    CONSTRAINT fk_encounters_doctor FOREIGN KEY (tenant_id, doctor_id)
        REFERENCES accounting.medical_staff (tenant_id, id)
        ON DELETE SET NULL,

    -- FK مرکب cross-schema: accounting_invoice_id → accounting.invoices (جهتِ مجاز)
    -- DEFERRABLE INITIALLY DEFERRED: همانِ الگوی slice4 (ETL می‌تواند ردیفِ بالینی را
    -- پیش از ردیفِ accounting در همان تراکنش درج کند؛ بررسی فقط در commit)
    -- accounting.invoices.uq_invoices_tenant_id موجود است (slice3) ✓
    CONSTRAINT fk_encounters_invoice FOREIGN KEY (tenant_id, accounting_invoice_id)
        REFERENCES accounting.invoices (tenant_id, id)
        ON DELETE SET NULL
        DEFERRABLE INITIALLY DEFERRED
);

-- Index: جستجوی پروندهٔ بیمار به ترتیبِ نزولِ زمان (شایع‌ترین query)
CREATE INDEX IF NOT EXISTS idx_encounters_patient_at
    ON clinical.encounters (patient_link_id, encounter_at DESC);

-- Index: صفِ وضعیت + زمان (برای worklist و Control Room)
CREATE INDEX IF NOT EXISTS idx_encounters_tenant_status_at
    ON clinical.encounters (tenant_id, status, encounter_at DESC);

-- updated_at auto-trigger (تابعِ clinical.set_updated_at() از slice4a)
DROP TRIGGER IF EXISTS trg_encounters_updated_at ON clinical.encounters;
CREATE TRIGGER trg_encounters_updated_at
    BEFORE UPDATE ON clinical.encounters
    FOR EACH ROW EXECUTE FUNCTION clinical.set_updated_at();

-- ###########################################################################
-- ۳) اضافهٔ encounter_id (nullable) به جداولِ بالینی
--    FK مرکب (tenant_id, encounter_id) → clinical.encounters(tenant_id, id) ON DELETE SET NULL
--    ADD COLUMN IF NOT EXISTS (Pg13+؛ idempotent)
--    گاردِ DO $$ برای FKها (اجرای دوم بی‌اثر)
-- ###########################################################################

-- ---------------------------------------------------------------------------
-- ۳a: clinical.vital_readings ← encounter_id
-- ---------------------------------------------------------------------------
ALTER TABLE clinical.vital_readings
    ADD COLUMN IF NOT EXISTS encounter_id BIGINT;                -- nullable

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_vital_readings_encounter'
    ) THEN
        ALTER TABLE clinical.vital_readings
            ADD CONSTRAINT fk_vital_readings_encounter
            FOREIGN KEY (tenant_id, encounter_id)
            REFERENCES clinical.encounters (tenant_id, id)
            ON DELETE SET NULL;
    END IF;
END$$;

-- ---------------------------------------------------------------------------
-- ۳b: clinical.lab_results ← encounter_id
-- ---------------------------------------------------------------------------
ALTER TABLE clinical.lab_results
    ADD COLUMN IF NOT EXISTS encounter_id BIGINT;                -- nullable

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_lab_results_encounter'
    ) THEN
        ALTER TABLE clinical.lab_results
            ADD CONSTRAINT fk_lab_results_encounter
            FOREIGN KEY (tenant_id, encounter_id)
            REFERENCES clinical.encounters (tenant_id, id)
            ON DELETE SET NULL;
    END IF;
END$$;

-- ---------------------------------------------------------------------------
-- ۳c: clinical.clinical_notes ← encounter_id
-- ---------------------------------------------------------------------------
ALTER TABLE clinical.clinical_notes
    ADD COLUMN IF NOT EXISTS encounter_id BIGINT;                -- nullable

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_clinical_notes_encounter'
    ) THEN
        ALTER TABLE clinical.clinical_notes
            ADD CONSTRAINT fk_clinical_notes_encounter
            FOREIGN KEY (tenant_id, encounter_id)
            REFERENCES clinical.encounters (tenant_id, id)
            ON DELETE SET NULL;
    END IF;
END$$;

-- ---------------------------------------------------------------------------
-- ۳d: clinical.prescriptions ← encounter_id
-- ---------------------------------------------------------------------------
ALTER TABLE clinical.prescriptions
    ADD COLUMN IF NOT EXISTS encounter_id BIGINT;                -- nullable

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_prescriptions_encounter'
    ) THEN
        ALTER TABLE clinical.prescriptions
            ADD CONSTRAINT fk_prescriptions_encounter
            FOREIGN KEY (tenant_id, encounter_id)
            REFERENCES clinical.encounters (tenant_id, id)
            ON DELETE SET NULL;
    END IF;
END$$;

-- ---------------------------------------------------------------------------
-- ۳e: clinical.doctor_visit_log ← encounter_id (soft — بدونِ FK واقعی)
--
--   ⚠️ soft رها شد: doctor_visit_log یک لجرِ مرزیِ accounting-snapshot است. این جدول
--   از accounting.invoices ساخته می‌شود (FK DEFERRABLE در slice4). اضافه‌کردنِ FK واقعی
--   از doctor_visit_log → encounters ریسکِ circular-dependency در ETL دارد
--   (هر encounters ممکن است از doctor_visit_log ساخته شود و بالعکس). همچنین
--   doctor_visit_log.tenant_id همیشه NOT NULL است اما encounters ممکن است بعد از
--   doctor_visit_log ساخته شود؛ DEFERRABLE روی این FK هم ریسکِ deadlock ایجاد می‌کند.
--   → encounter_id در doctor_visit_log به‌عنوانِ soft reference (nullable BIGINT بدونِ FK)
--   اضافه می‌شود. ORM/service-layer مسئولِ ثبتِ صحیحِ آن است.
--   نیازمندِ تأییدِ معمارِ داده قبل از تبدیل به FK واقعی.
-- ---------------------------------------------------------------------------
ALTER TABLE clinical.doctor_visit_log
    ADD COLUMN IF NOT EXISTS encounter_id BIGINT;                -- soft ref، بدونِ FK

-- ###########################################################################
-- ۴) ستون‌های structured dose به clinical.patient_medications
--    همه nullable (additive؛ ردیف‌های قدیمی NULL می‌مانند)
-- ###########################################################################

ALTER TABLE clinical.patient_medications
    ADD COLUMN IF NOT EXISTS dose_value  NUMERIC(10,3);          -- مقدارِ عددیِ دوز

ALTER TABLE clinical.patient_medications
    ADD COLUMN IF NOT EXISTS dose_unit   TEXT;                   -- 'mg','mcg','IU','unit',…

ALTER TABLE clinical.patient_medications
    ADD COLUMN IF NOT EXISTS frequency   TEXT;                   -- CHECK پایین (DO $$)

ALTER TABLE clinical.patient_medications
    ADD COLUMN IF NOT EXISTS route       TEXT;                   -- CHECK پایین (DO $$)

-- frequency CHECK (nullable → IS NULL OR IN (...))
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'clinical.patient_medications'::regclass
          AND conname   = 'chk_medications_frequency'
    ) THEN
        ALTER TABLE clinical.patient_medications
            ADD CONSTRAINT chk_medications_frequency
            CHECK (frequency IS NULL OR frequency IN (
                'od','bid','tid','qid','qod','weekly','monthly','prn',
                'with_meal','bedtime','other'
            ));
    END IF;
END$$;

-- route CHECK (nullable → IS NULL OR IN (...))
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'clinical.patient_medications'::regclass
          AND conname   = 'chk_medications_route'
    ) THEN
        ALTER TABLE clinical.patient_medications
            ADD CONSTRAINT chk_medications_route
            CHECK (route IS NULL OR route IN (
                'oral','sublingual','sc','im','iv','topical','inhaled','other'
            ));
    END IF;
END$$;

-- ###########################################################################
-- ۵) clinical.prescription_items — اقلامِ ساختاریافتهٔ نسخه
--    prescriptions.items JSONB (raw payload) دست‌نخورده می‌ماند.
--    این جدول structured‌ترِ همان payload است.
-- ###########################################################################
CREATE TABLE IF NOT EXISTS clinical.prescription_items (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
    -- FK مرکب → prescriptions (tenant-safe؛ uq_prescriptions_tenant_id ساخته شد بالا)
    prescription_id  BIGINT NOT NULL,
    drug_name        TEXT NOT NULL,
    -- drug_class: FKِ soft (nullable + ON DELETE SET NULL)
    --   ⚠️ soft رها شد: drug_catalog seedها از Python bootstrap وارد می‌شوند (نه inline SQL).
    --   drug_classes.class_key در slice2 seed شده؛ اما prescription_items.drug_class
    --   ممکن است مقادیرِ free-text داشته باشد که در drug_classes نیستند (کلاسِ جدید،
    --   دارویِ ترکیبی، یا کلاسِ خارج از seed). FK واقعی باعثِ FK violation در این موارد
    --   می‌شود و ریسکِ orphan دارد. → soft soft-reference: nullable TEXT.
    --   نیازمندِ تأییدِ معمارِ داده قبل از تبدیل به FK واقعی.
    drug_class       TEXT,                                       -- soft ref به drug_classes.class_key
    dose_value       NUMERIC(10,3),
    dose_unit        TEXT,
    frequency        TEXT
                     CHECK (frequency IS NULL OR frequency IN (
                         'od','bid','tid','qid','qod','weekly','monthly','prn',
                         'with_meal','bedtime','other'
                     )),
    route            TEXT
                     CHECK (route IS NULL OR route IN (
                         'oral','sublingual','sc','im','iv','topical','inhaled','other'
                     )),
    quantity         INTEGER CHECK (quantity IS NULL OR quantity > 0),
    duration_days    INTEGER CHECK (duration_days IS NULL OR duration_days > 0),
    instructions     TEXT,

    -- FK مرکب به prescriptions (tenant-safe)
    CONSTRAINT fk_prescription_items_prescription FOREIGN KEY (tenant_id, prescription_id)
        REFERENCES clinical.prescriptions (tenant_id, id)
        ON DELETE CASCADE                                        -- حذفِ نسخه → حذفِ اقلامش
);

CREATE INDEX IF NOT EXISTS idx_prescription_items_prescription
    ON clinical.prescription_items (prescription_id);

-- ###########################################################################
-- ۶) clinical.appointments — اضافهٔ doctor_id + chief_complaint
--    doctor_id: FKِ cross-schema مجاز (clinical → accounting)، ON DELETE SET NULL
-- ###########################################################################

ALTER TABLE clinical.appointments
    ADD COLUMN IF NOT EXISTS doctor_id        BIGINT;            -- nullable؛ FK cross-schema

ALTER TABLE clinical.appointments
    ADD COLUMN IF NOT EXISTS chief_complaint  TEXT;              -- nullable

-- FK مرکب cross-schema: (tenant_id, doctor_id) → accounting.medical_staff(tenant_id, id)
-- accounting.medical_staff.uq_medical_staff_tenant_id موجود است (slice3) ✓
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'clinical.appointments'::regclass
          AND conname   = 'fk_appointments_doctor'
    ) THEN
        ALTER TABLE clinical.appointments
            ADD CONSTRAINT fk_appointments_doctor
            FOREIGN KEY (tenant_id, doctor_id)
            REFERENCES accounting.medical_staff (tenant_id, id)
            ON DELETE SET NULL;
    END IF;
END$$;

-- ###########################################################################
-- GRANTهای مرز
--   clinical_app باید به encounters و prescription_items (جداولِ جدید) دسترسی کامل داشته باشد.
--   الگوی شناخته‌شده (slice2 / slice2b): GRANT … ON ALL TABLES + REVOKE فقط activity_logs.
--   idempotent (GRANT مکرر no-op است).
-- ###########################################################################
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA clinical TO clinical_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA clinical TO clinical_app;

-- Finding 3b: بلنکتِ GRANT بالا UPDATE/DELETE را روی activity_logs دوباره اعطا می‌کند.
-- همین‌جا دوباره REVOKE می‌کنیم تا append-only بودنِ جدول حفظ شود (idempotent).
REVOKE UPDATE, DELETE ON clinical.activity_logs FROM clinical_app;

-- ============================================================================
-- ریسک‌ها / RLS-TODO / موارد موکول‌شده (نیازمندِ تأییدِ معمارِ داده):
--
--   1. doctor_visit_log.encounter_id: soft reference (BIGINT nullable، بدونِ FK واقعی).
--      FK واقعی ریسکِ circular-dependency در ETL (doctor_visit_log ↔ encounters) دارد.
--      قبل از T1/RLS باید معمارِ داده تأیید کند جهتِ وابستگی یک‌طرفه است.
--
--   2. prescription_items.drug_class: soft reference (TEXT nullable، بدونِ FK به drug_classes).
--      seed drug_classes در Python bootstrap است؛ free-text ممکن است FK را نقض کند.
--      اگر معمارِ داده تأیید کند drug_class همیشه از catalog است، می‌توان FK واقعی زد.
--
--   3. RLS-TODO: encounters، prescription_items مانندِ همهٔ جداولِ بالینی هنوز بدونِ
--      فیلترِ tenant هستند. فعال‌سازیِ کاملِ RLS موکول به T1 (ADR-0006 / موکولِ T1).
--
--   4. clinical.observations VIEW: با اضافه‌شدنِ encounter_id به vital_readings و
--      lab_results، VIEW تغییر نمی‌کند (فقط ستون‌های SELECT-ای موجود، نه *).
--      اگر encounter_id در VIEW لازم شد، معمارِ داده باید تأیید کند.
--
--   5. GRANT doctor_id (accounting.medical_staff) به clinical_app:
--      Batch 3 SECU-06 medical_staff را از دسترسِ clinical_app حذف کرده (SELECT نه).
--      FK از encounters.doctor_id به medical_staff ساختاری است (DDL/constraint check)؛
--      clinical_app برای INSERT/UPDATE به encounters نیازی به SELECT روی medical_staff
--      ندارد — FK توسطِ Postgres خودکار بررسی می‌شود. این سازگار با SECU-06 است.
-- ============================================================================

-- ============================================================================
-- معیارِ «انجام‌شدهٔ» Batch 4b (برای تستِ نگهبان):
--   ۱) این فایل روی Postgresی که برش‌های ۰/۲/۲b/۳/۴/۴a اجرا شده‌اند بدونِ خطا اجرا شود.
--   ۲) idempotent: اجرای دوم هم سبز.
--   ۳) clinical.encounters وجود دارد + FKهایش (patient_links، appointments، medical_staff،
--      invoices).
--   ۴) vital_readings با encounter_id نامعتبر → ForeignKeyViolation.
--   ۵) cross-tenant encounter FK رد می‌شود.
--   ۶) prescription_items.prescription_id نامعتبر → ForeignKeyViolation.
--   ۷) appointments.doctor_id FK وجود دارد.
--   ۸) patient_medications.frequency مقدارِ نامعتبر → CheckViolation.
--   ۹) clinical_app روی encounters و prescription_items گرنتِ INSERT دارد.
-- ============================================================================
