-- RETIRED DESIGN ARTEFACT — DO NOT EXECUTE.
--
-- This file originally described the additive dual-run schema proposed before the
-- Clinical Engine v2 implementation was hardened. It referenced the retired
-- `clinical_rules` and `suggestion_log` tables and is intentionally no longer SQL.
--
-- The authoritative database contract is now:
--
--   specialist_clinic/src/adapters/sqlite/schema.sql
--   specialist_clinic/src/adapters/sqlite/clinical_engine_runtime_schema.py
--   specialist_clinic/src/adapters/sqlite/clinical_reconciliation_schema.py
--
-- Schema changes must be implemented through the application migration boundary and
-- covered by fresh-database and copied-database tests. Copying historical DDL from the
-- research directory into an installed database is unsupported.
