-- ============================================================================
-- Synchronize PostgreSQL identity sequences after explicit-id seeds/imports.
--
-- Several translated SQLite catalogs intentionally preserve stable seed IDs
-- (for example clinical.conditions ids 1..5).  GENERATED BY DEFAULT identities
-- do not advance when an explicit id is inserted, so the first ordinary INSERT
-- could otherwise reuse id=1 and fail with a primary-key violation.
--
-- This slice is idempotent and never moves a sequence backwards.  It covers all
-- identity-backed `id` columns in the three application schemas, including
-- existing installations where earlier slices have already been applied.
-- ============================================================================

DO $$
DECLARE
    r              RECORD;
    sequence_name  TEXT;
    sequence_oid   REGCLASS;
    maximum_id     BIGINT;
    current_value  BIGINT;
    sequence_used  BOOLEAN;
BEGIN
    FOR r IN
        SELECT table_schema, table_name, column_name
        FROM information_schema.columns
        WHERE table_schema IN ('platform', 'accounting', 'clinical')
          AND column_name = 'id'
          AND is_identity = 'YES'
        ORDER BY table_schema, table_name
    LOOP
        sequence_name := pg_get_serial_sequence(
            format('%I.%I', r.table_schema, r.table_name),
            r.column_name
        );
        IF sequence_name IS NULL THEN
            CONTINUE;
        END IF;

        sequence_oid := sequence_name::regclass;
        EXECUTE format(
            'SELECT COALESCE(MAX(%I), 0)::bigint FROM %I.%I',
            r.column_name,
            r.table_schema,
            r.table_name
        ) INTO maximum_id;
        EXECUTE format(
            'SELECT last_value::bigint, is_called FROM %s',
            sequence_oid
        ) INTO current_value, sequence_used;

        IF maximum_id > current_value
           OR (
               maximum_id = current_value
               AND maximum_id > 0
               AND NOT sequence_used
           )
        THEN
            PERFORM setval(sequence_oid, maximum_id, TRUE);
        END IF;
    END LOOP;
END
$$;
