-- ==========================================================================
-- Specialist-clinic patient-record import ledger.
--
-- Source SQLite row IDs are meaningful only inside one source database. This
-- tenant-scoped ledger gives the ETL a stable idempotency key and stores the
-- transformed payload digest, so reruns can distinguish an exact replay from a
-- source row that changed after an earlier import.
--
-- ``target_key`` is always present. ``target_row_id`` is optional because a few
-- target tables (for example condition_lab_tests) use only a composite natural
-- key. A target is intentionally NOT unique in this ledger: independent source
-- databases may legitimately resolve the same catalogue row or patient link.
-- ==========================================================================

CREATE TABLE IF NOT EXISTS clinical.record_import_ledger (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id         BIGINT NOT NULL REFERENCES platform.tenants(id),
    source_id         TEXT NOT NULL,
    source_table      TEXT NOT NULL,
    source_row_id     BIGINT NOT NULL,
    target_table      TEXT NOT NULL,
    target_row_id     BIGINT,
    target_key        TEXT NOT NULL,
    payload_sha256    TEXT NOT NULL,
    imported_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    imported_by       TEXT,
    CONSTRAINT uq_record_import_source
        UNIQUE (tenant_id, source_id, source_table, source_row_id),
    CONSTRAINT chk_record_import_source_id_not_blank
        CHECK (btrim(source_id) <> ''),
    CONSTRAINT chk_record_import_table_names_not_blank
        CHECK (btrim(source_table) <> '' AND btrim(target_table) <> ''),
    CONSTRAINT chk_record_import_target_key_not_blank
        CHECK (btrim(target_key) <> ''),
    CONSTRAINT chk_record_import_hash_hex
        CHECK (payload_sha256 ~ '^[0-9a-f]{64}$')
);

CREATE INDEX IF NOT EXISTS idx_record_import_source_lookup
    ON clinical.record_import_ledger
       (tenant_id, source_id, source_table, source_row_id);
CREATE INDEX IF NOT EXISTS idx_record_import_target_lookup
    ON clinical.record_import_ledger
       (tenant_id, target_table, target_key);

ALTER TABLE clinical.record_import_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE clinical.record_import_ledger FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON clinical.record_import_ledger;
CREATE POLICY tenant_isolation ON clinical.record_import_ledger
    FOR ALL
    USING (
        tenant_id = NULLIF(
            current_setting('app.current_tenant', true), ''
        )::bigint
    )
    WITH CHECK (
        tenant_id = NULLIF(
            current_setting('app.current_tenant', true), ''
        )::bigint
    );

-- ETL uses the normal application connection under the tenant GUC. The ledger
-- is append-only for that role: it may read and insert, never rewrite history.
GRANT SELECT, INSERT ON clinical.record_import_ledger
    TO clinical_app, platform_app;
GRANT USAGE, SELECT ON SEQUENCE clinical.record_import_ledger_id_seq
    TO clinical_app, platform_app;
REVOKE UPDATE, DELETE, TRUNCATE ON clinical.record_import_ledger
    FROM clinical_app, platform_app;

COMMENT ON TABLE clinical.record_import_ledger IS
    'Append-only idempotency and reconciliation ledger for specialist SQLite record imports.';
