-- ============================================================================
-- schema_pg_slice9_population_thresholds.sql
-- برشِ ۹ — آستانه‌های گرید به‌ازایِ جمعیت (Population-specific threshold overrides)
--
-- هدف:
--   امکانِ آستانه‌های متفاوت برای زیرجمعیت‌های بالینی خاص (سالمندِ شکننده،
--   ریسکِ بالایِ هیپوگلیسمی، جوانِ کم‌ریسک). همهٔ override‌ها با
--   approval_status='draft' وارد می‌شوند و فقط پس از تأیید پزشک
--   (approval_status='approved') زنده می‌شوند.
--
-- اصل ایمنی (قفل‌شده):
--   draft هرگز روی رفتارِ engine اعمال نمی‌شود.
--   تأییدِ پزشک جعل نمی‌شود.
--   رفتارِ فعلیِ red-flag بدون تغییر است تا یک ردیف approved نشده باشد.
--
-- مقادیرِ seed: verbatim از هیئتِ مشاوران (endocrinology-advisor + cardiology-advisor).
--   محتوای بالینی (مقادیر/منبع/rationale) را تغییر ندهید.
--
-- population_key‌ها و gate‌هایشان (اعمال‌شده در population_service.py):
--   frail        : frailty='complex' OR age>=75
--   hypo_high    : hypo_risk='high'
--   young_lowrisk: age<45 AND frailty IN (NULL,'robust') AND hypo_risk IN (NULL,'low')
--
-- bound:
--   'high' = آستانه برای مقادیرِ بالا (direction=high) — فعلاً eval می‌شود.
--   'low'  = آستانه برای مقادیرِ پایین (هیپوتانسیون) — فقط داده؛ eval موکول.
--
-- الگو: mirror دقیقِ clinical_rules (tenant_id، RLS tenant_isolation+FORCE، GRANTها).
--
-- وابستگی: بعد از slice0 (رول‌ها + tenants) + slice5 (RLS).
-- idempotent: CREATE TABLE IF NOT EXISTS + ON CONFLICT DO NOTHING همه‌جا.
-- ============================================================================

-- ###########################################################################
-- ۱) ایجادِ جدولِ population_thresholds
-- ###########################################################################
CREATE TABLE IF NOT EXISTS clinical.population_thresholds (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),

    -- indicator_key: کلیدِ بیان در clinical_indicators (مثلِ 'hba1c', 'fbs')
    indicator_key   TEXT   NOT NULL,

    -- population_key: کلیدِ زیرجمعیت ('frail', 'hypo_high', 'young_lowrisk', …)
    population_key  TEXT   NOT NULL,

    -- bound: جهتِ این override ('high'=مقادیرِ بالا / 'low'=مقادیرِ پایین)
    bound           TEXT   NOT NULL DEFAULT 'high'
                           CHECK (bound IN ('high', 'low')),

    -- آستانه‌های override (فقط فیلدهای non-null اعمال می‌شوند):
    warn            REAL,
    danger          REAL,
    target          REAL,
    goal_low        REAL,
    goal_high       REAL,

    -- مستندات بالینی:
    rationale       TEXT,
    evidence        TEXT,

    -- وضعیتِ تأیید — فقط 'approved' فعال می‌شود؛ seed همیشه 'draft':
    approval_status TEXT   NOT NULL DEFAULT 'draft'
                           CHECK (approval_status IN ('draft', 'approved')),

    -- اطلاعاتِ تأیید (توسطِ workflow قدمِ بعد پر می‌شود):
    approved_by     TEXT,
    approved_at     TIMESTAMPTZ,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- یکتایی: هر ترکیبِ (tenant, indicator, population, bound) یک override دارد
    CONSTRAINT uq_pop_thresholds_tenant_ind_pop_bound
        UNIQUE (tenant_id, indicator_key, population_key, bound)
);

-- ایندکسِ کارآمد برای کوئریِ سرویس (indicator_key + approved آن)
CREATE INDEX IF NOT EXISTS idx_pop_thresholds_tenant_pop
    ON clinical.population_thresholds (tenant_id, population_key, approval_status);

-- ###########################################################################
-- ۲) RLS — عیناً مثلِ clinical_rules / ddi_pairs (برشِ ۵ این را auto-detect
--    می‌کند چون جدول tenant_id دارد؛ اما ما صریح هم اعمال می‌کنیم برای idempotency)
-- ###########################################################################
ALTER TABLE clinical.population_thresholds ENABLE ROW LEVEL SECURITY;
ALTER TABLE clinical.population_thresholds FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation ON clinical.population_thresholds;
CREATE POLICY tenant_isolation ON clinical.population_thresholds
    FOR ALL
    USING      (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::bigint)
    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::bigint);

-- ###########################################################################
-- ۳) GRANT — عیناً مثلِ sibling‌ها (clinical_app + platform_app)
-- ###########################################################################
GRANT SELECT, INSERT, UPDATE, DELETE
    ON clinical.population_thresholds
    TO clinical_app, platform_app;

-- ###########################################################################
-- ۴) Seed idempotent — همه 'draft' (verbatim از هیئتِ مشاوران)
--    ON CONFLICT DO NOTHING: اجرای مجدد بی‌خطر است
-- ###########################################################################

-- ── ۴a) frail + bound='high' (ADA 2026 §13 / Endocrine Society Geriatric) ──
--   gate در کد: frailty='complex' OR age>=75
INSERT INTO clinical.population_thresholds
    (tenant_id, indicator_key, population_key, bound,
     warn, danger, target, goal_low, goal_high,
     rationale, evidence, approval_status)
VALUES
    -- HbA1c سالمندِ شکننده: هدفِ آسان‌گیرانه‌تر برای پیشگیری از هیپوگلیسمی
    (1, 'hba1c', 'frail', 'high',
     8.0, 9.0, 8.0, 7.5, 8.5,
     'هدفِ آسان‌گیرانه‌تر برای سالمندِ شکننده؛ پیشگیری از هیپوگلیسمی اولویت دارد',
     'ADA 2026 §13',
     'draft'),

    -- FBS سالمندِ شکننده: آستانه‌های بالاتر
    (1, 'fbs', 'frail', 'high',
     160, 200, NULL, 100, NULL,
     'آستانهٔ بالاتر برای سالمندِ شکننده؛ goal_low=100 برای پیشگیری از هیپو',
     'ADA §13/Endocrine Society Geriatric',
     'draft'),

    -- PPG سالمندِ شکننده: آستانه‌های بالاتر
    (1, 'ppg', 'frail', 'high',
     220, 280, NULL, NULL, NULL,
     'آستانهٔ پس‌غذایِ آسان‌گیر برای سالمندِ شکننده',
     'expert (Evidence E)',
     'draft'),

    -- BP Systolic سالمندِ شکننده: آستانه‌های بالاتر (HYVET)
    (1, 'bp_systolic', 'frail', 'high',
     140, 160, 140, NULL, NULL,
     'هدفِ فشارِ سیستولِ بالاتر برای سالمندِ شکننده؛ ریسکِ افتادن/هیپوتانسیون',
     'ESC/ESH 2023، HYVET',
     'draft')

ON CONFLICT (tenant_id, indicator_key, population_key, bound) DO NOTHING;

-- ── ۴b) hypo_high + bound='high' (ADA 2026 Table 6.5) ──
--   gate در کد: hypo_risk='high'
INSERT INTO clinical.population_thresholds
    (tenant_id, indicator_key, population_key, bound,
     warn, danger, target, goal_low, goal_high,
     rationale, evidence, approval_status)
VALUES
    -- FBS با ریسکِ بالایِ هیپو: هدفِ پایینِ شل‌تر
    (1, 'fbs', 'hypo_high', 'high',
     150, NULL, NULL, 110, NULL,
     'goal_low بالاتر برای بیمار با ریسکِ بالایِ هیپوگلیسمی',
     'ADA 2026 Table 6.5',
     'draft'),

    -- HbA1c با ریسکِ بالایِ هیپو: target و goal_low شل‌تر
    (1, 'hba1c', 'hypo_high', 'high',
     NULL, NULL, 7.5, 7.0, NULL,
     'هدفِ A1c بالاتر برای بیمارِ در معرضِ هیپو؛ ایمنی اولویت دارد',
     'ADA §6/§13',
     'draft')

ON CONFLICT (tenant_id, indicator_key, population_key, bound) DO NOTHING;

-- ── ۴c) young_lowrisk + bound='high' (ADA §6.1) ──
--   gate در کد: age<45 AND frailty IN (NULL,'robust') AND hypo_risk IN (NULL,'low')
INSERT INTO clinical.population_thresholds
    (tenant_id, indicator_key, population_key, bound,
     warn, danger, target, goal_low, goal_high,
     rationale, evidence, approval_status)
VALUES
    -- HbA1c جوانِ کم‌ریسک: آستانهٔ تنگ‌تر
    (1, 'hba1c', 'young_lowrisk', 'high',
     6.5, NULL, 6.5, 6.0, NULL,
     'هدفِ تنگ‌تر برای جوانِ سالم بدونِ ریسکِ هیپو',
     'ADA §6.1',
     'draft'),

    -- FBS جوانِ کم‌ریسک: آستانهٔ تنگ‌تر
    (1, 'fbs', 'young_lowrisk', 'high',
     120, NULL, NULL, NULL, 120,
     'آستانهٔ تنگ‌تر برای جوانِ کم‌ریسک؛ goal_high=120',
     'ADA §6.1',
     'draft')

ON CONFLICT (tenant_id, indicator_key, population_key, bound) DO NOTHING;

-- ── ۴d) frail + bound='low' (هیپوتانسیون) ──
--   داده‌یِ draft؛ eval در این برش سیم‌کشی نمی‌شود (موکولِ قدمِ بعد؛
--   نیازمندِ مسیرِ eval دوجهته).
--   gate در کد: همانِ frail
INSERT INTO clinical.population_thresholds
    (tenant_id, indicator_key, population_key, bound,
     warn, danger, target, goal_low, goal_high,
     rationale, evidence, approval_status)
VALUES
    -- BP Systolic: هیپوتانسیون در سالمندِ شکننده
    (1, 'bp_systolic', 'frail', 'low',
     110, 100, NULL, NULL, NULL,
     'هشدار برای افتِ فشار در سالمندِ شکننده؛ ریسکِ سقوط/ایسکمی',
     'AGS، NICE NG136',
     'draft'),

    -- BP Diastolic: هیپوتانسیون دیاستولیک
    (1, 'bp_diastolic', 'frail', 'low',
     60, 55, NULL, NULL, NULL,
     'J-curve: دیاستولِ خیلی پایین → ریسکِ قلبی در سالمندِ شکننده',
     'J-curve، ESC/ESH 2023',
     'draft')

ON CONFLICT (tenant_id, indicator_key, population_key, bound) DO NOTHING;

-- ============================================================================
-- معیارِ «انجام‌شدهٔ» برشِ ۹ (برای تستِ نگهبان):
--   ۱) جدولِ clinical.population_thresholds وجود دارد با ستون‌های صحیح.
--   ۲) RLS فعال است با policy tenant_isolation + FORCE.
--   ۳) GRANT به clinical_app و platform_app انجام شده.
--   ۴) ۱۲ ردیفِ seed با approval_status='draft' وجود دارد.
--   ۵) idempotency: اجرای مجدد بدونِ خطا (ON CONFLICT DO NOTHING).
--   ۶) هیچ ردیفِ 'approved' در seed وجود ندارد.
-- ============================================================================
