-- ============================================================================
-- Append-only ledger for SQLite accounting-history migration.
-- ============================================================================

CREATE TABLE IF NOT EXISTS accounting.accounting_import_ledger (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           BIGINT NOT NULL REFERENCES platform.tenants(id),
    source_id           TEXT NOT NULL,
    source_table        TEXT NOT NULL,
    source_pk           BIGINT NOT NULL,
    target_table        TEXT NOT NULL,
    target_pk           BIGINT,
    target_key          TEXT,
    source_sha256       CHAR(64) NOT NULL,
    target_sha256       CHAR(64),
    imported_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    imported_by         TEXT NOT NULL,
    CONSTRAINT uq_accounting_import_source_row
        UNIQUE (tenant_id, source_id, source_table, source_pk),
    CONSTRAINT chk_accounting_import_source_id
        CHECK (length(btrim(source_id)) BETWEEN 3 AND 180),
    CONSTRAINT chk_accounting_import_source_table
        CHECK (source_table ~ '^[a-z_][a-z0-9_]*$'),
    CONSTRAINT chk_accounting_import_target_table
        CHECK (target_table ~ '^accounting\.[a-z_][a-z0-9_]*$'),
    CONSTRAINT chk_accounting_import_source_digest
        CHECK (source_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT chk_accounting_import_target_digest
        CHECK (target_sha256 IS NULL OR target_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT chk_accounting_import_target_identity
        CHECK (target_pk IS NOT NULL OR target_key IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS idx_accounting_import_source
    ON accounting.accounting_import_ledger
       (tenant_id, source_id, source_table, source_pk);
CREATE INDEX IF NOT EXISTS idx_accounting_import_target
    ON accounting.accounting_import_ledger
       (tenant_id, target_table, target_pk);

ALTER TABLE accounting.accounting_import_ledger ENABLE ROW LEVEL SECURITY;
ALTER TABLE accounting.accounting_import_ledger FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS accounting_import_tenant_policy
    ON accounting.accounting_import_ledger;
CREATE POLICY accounting_import_tenant_policy
    ON accounting.accounting_import_ledger
    USING (
        tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::bigint
    )
    WITH CHECK (
        tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::bigint
    );

GRANT SELECT, INSERT ON accounting.accounting_import_ledger TO accounting_app;
GRANT USAGE, SELECT ON SEQUENCE accounting.accounting_import_ledger_id_seq
    TO accounting_app;
GRANT SELECT ON accounting.accounting_import_ledger TO platform_app;
REVOKE UPDATE, DELETE, TRUNCATE ON accounting.accounting_import_ledger
    FROM accounting_app, platform_app, clinical_app;
REVOKE ALL ON accounting.accounting_import_ledger FROM clinical_app;

COMMENT ON TABLE accounting.accounting_import_ledger IS
    'Append-only evidence binding each legacy SQLite accounting row to one Halqe target.';
