-- ==========================================================================
-- Accounting shift staff — source of truth for staff attached to new items.
--
-- The production Flask accounting app treats doctor/nurse assignment as a
-- property of (work_date, shift), not of an invoice. Existing item rows retain
-- the staff IDs captured at creation time.
-- ==========================================================================

CREATE TABLE IF NOT EXISTS accounting.shift_staff (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT NOT NULL REFERENCES platform.tenants(id),
    work_date   DATE NOT NULL,
    shift       TEXT NOT NULL,
    doctor_id   BIGINT,
    nurse_id    BIGINT,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_shift_staff_context UNIQUE (tenant_id, work_date, shift),
    CONSTRAINT chk_shift_staff_has_member
        CHECK (doctor_id IS NOT NULL OR nurse_id IS NOT NULL),
    CONSTRAINT fk_shift_staff_doctor FOREIGN KEY (tenant_id, doctor_id)
        REFERENCES accounting.medical_staff (tenant_id, id),
    CONSTRAINT fk_shift_staff_nurse FOREIGN KEY (tenant_id, nurse_id)
        REFERENCES accounting.medical_staff (tenant_id, id)
);

CREATE INDEX IF NOT EXISTS idx_shift_staff_context
    ON accounting.shift_staff (tenant_id, work_date, shift);

GRANT SELECT, INSERT, UPDATE, DELETE ON accounting.shift_staff TO accounting_app;
GRANT USAGE, SELECT ON SEQUENCE accounting.shift_staff_id_seq TO accounting_app;

-- Deliberately no grant to platform_app/clinical_app: staff configuration is an
-- accounting write concern and is exposed only through the accounting API.
