# Generated by Django 5.2.15 on 2026-06-09 01:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generic_name', models.TextField()),
                ('irc_code', models.TextField(blank=True, default='')),
                ('atc_code', models.TextField(blank=True, default='')),
                ('form', models.TextField(blank=True, default='')),
                ('strength', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'drug',
                'indexes': [models.Index(fields=['generic_name'], name='drug_generic_a77f69_idx'), models.Index(fields=['irc_code'], name='drug_irc_cod_ac3d21_idx')],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurer', models.CharField(choices=[('tamin', 'tamin'), ('ihio', 'ihio'), ('armed', 'armed')], max_length=10)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('submitted', 'submitted'), ('registered', 'registered'), ('failed', 'failed')], default='draft', max_length=12)),
                ('tracking_code', models.TextField(blank=True, default='')),
                ('channel', models.CharField(choices=[('webview', 'webview'), ('api', 'api')], default='webview', max_length=10)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.appuser')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient')),
            ],
            options={
                'db_table': 'prescription',
            },
        ),
        migrations.CreateModel(
            name='InsurerLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurer', models.TextField(blank=True, default='')),
                ('action', models.TextField(blank=True, default='')),
                ('status', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.clinic')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='rx.prescription')),
            ],
            options={
                'db_table': 'insurer_log',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('drug', 'drug'), ('paraclinical', 'paraclinical'), ('service', 'service')], default='drug', max_length=16)),
                ('item_name', models.TextField(blank=True, default='')),
                ('dose', models.TextField(blank=True, default='')),
                ('count', models.IntegerField(blank=True, null=True)),
                ('instruction', models.TextField(blank=True, default='')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.clinic')),
                ('drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='rx.drug')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rx.prescription')),
            ],
            options={
                'db_table': 'prescription_item',
            },
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['clinic', 'patient', '-created_at'], name='prescriptio_clinic__bdb71f_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['clinic', 'status'], name='prescriptio_clinic__dc5020_idx'),
        ),
        migrations.AddIndex(
            model_name='insurerlog',
            index=models.Index(fields=['clinic', '-created_at'], name='insurer_log_clinic__95cafa_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionitem',
            index=models.Index(fields=['clinic', 'prescription'], name='prescriptio_clinic__36d9fd_idx'),
        ),
    ]
