# Generated by Django 5.2.15 on 2026-06-09 01:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('national_id', models.TextField(blank=True, null=True)),
                ('first_name', models.TextField(blank=True, default='')),
                ('last_name', models.TextField(blank=True, default='')),
                ('phone_number', models.TextField(blank=True, default='')),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='', max_length=10)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, default='')),
                ('insurance_type', models.TextField(blank=True, default='')),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('is_foreign', models.BooleanField(default=False)),
                ('wallet_balance', models.BigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.clinic')),
            ],
            options={
                'db_table': 'patient',
                'indexes': [models.Index(fields=['clinic', 'national_id'], name='patient_clinic__2ad038_idx'), models.Index(fields=['clinic', 'last_name', 'first_name'], name='patient_clinic__1ba7b4_idx')],
                'constraints': [models.UniqueConstraint(fields=('clinic', 'national_id'), name='uq_patient_clinic_national_id')],
            },
        ),
    ]
