# Generated by Django 5.2.15 on 2026-06-09 06:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rls_phase2'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_username', models.TextField(blank=True, default='')),
                ('action', models.TextField(help_text="stable machine key, e.g. 'suggestion.acknowledge'")),
                ('summary', models.TextField(blank=True, default='')),
                ('entity_type', models.TextField(blank=True, default='')),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.appuser')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.clinic')),
            ],
            options={
                'db_table': 'activity_log',
                'indexes': [models.Index(fields=['clinic', '-created_at'], name='activity_lo_clinic__b80e60_idx'), models.Index(fields=['clinic', 'action'], name='activity_lo_clinic__f09734_idx')],
            },
        ),
    ]
