"""
clinical models — managed=False (schema owned by SQL slices).

All clinical tables FK to clinical.patient_links(id) via patient_link_id.
Cross-schema FK to accounting.patients is expressed as BigIntegerField
(db_constraint=False) — the real composite FK lives in the SQL.

PatientLink: thin enrollment record (ADR-0007 §2.1 — no demographic mirror).
VitalReading: the vitals half of the canonical Observation (ADR-0005).
Condition: disease-module catalog (clinical.conditions).
PatientCondition: per-patient diagnosis (clinical.patient_conditions).
PatientMedication: per-patient medication list (clinical.patient_medications).
ClinicalRule: clinical_rules catalog — trigger_json DSL rows (JSONB in PG).
ClinicalIndicator: clinical_indicators — live threshold/target metadata.
PatientFlag: patient_flags — per-patient categorical/bool decision inputs.
"""
from django.db import models


class PatientLink(models.Model):
    """
    clinical.patient_links — enrollment record linking to accounting.patients.

    patient_id is a BigIntegerField (no ORM FK) because the real constraint
    is a composite FK across schemas, which Django cannot represent.
    """

    tenant_id = models.BigIntegerField(default=1)
    # Cross-schema FK expressed as plain int — DB enforces it
    patient_id = models.BigIntegerField()
    wallet_balance = models.DecimalField(max_digits=14, decimal_places=0, default=0)
    sms_opt_out = models.BooleanField(default=False)
    sms_consent = models.BooleanField(default=False)
    sms_consent_at = models.DateTimeField(null=True, blank=True)
    sms_consent_source = models.TextField(null=True, blank=True)
    sms_opt_out_at = models.DateTimeField(null=True, blank=True)
    data_retention_until = models.DateField(null=True, blank=True)
    is_active = models.BooleanField(default=True)
    enrolled_by = models.TextField(null=True, blank=True)
    enrolled_at = models.DateTimeField(auto_now_add=True)
    notes = models.TextField(null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        managed = False
        app_label = "clinical"
        db_table = '"clinical"."patient_links"'
        ordering = ["id"]

    def __str__(self):
        return f"PatientLink(id={self.id}, patient_id={self.patient_id})"


class VitalReading(models.Model):
    """
    clinical.vital_readings — vitals half of Observation canonical (ADR-0005).

    Columns from slice2:
      patient_link_id, type, value, unit, measured_at, source, notes, recorded_by
    """

    tenant_id = models.BigIntegerField(default=1)
    patient_link_id = models.BigIntegerField()
    type = models.TextField()
    value = models.FloatField()
    unit = models.TextField(null=True, blank=True)
    measured_at = models.DateTimeField()
    source = models.TextField(default="clinic", null=True, blank=True)
    notes = models.TextField(null=True, blank=True)
    recorded_by = models.TextField(null=True, blank=True)

    class Meta:
        managed = False
        app_label = "clinical"
        db_table = '"clinical"."vital_readings"'
        ordering = ["-measured_at"]

    def __str__(self):
        return (
            f"VitalReading(type={self.type}, value={self.value}, "
            f"patient_link_id={self.patient_link_id})"
        )


class Condition(models.Model):
    """
    clinical.conditions — disease-module catalog.

    Columns used here: id, tenant_id, name, code, is_active, is_chronic,
    display_order, description, icon, color.
    Slice2 schema: BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY.
    """

    tenant_id = models.BigIntegerField(default=1)
    name = models.TextField()
    code = models.TextField(null=True, blank=True)
    is_active = models.BooleanField(default=True)
    is_chronic = models.BooleanField(default=True)
    display_order = models.IntegerField(default=100)
    description = models.TextField(null=True, blank=True)
    icon = models.TextField(null=True, blank=True)
    color = models.TextField(null=True, blank=True)

    class Meta:
        managed = False
        app_label = "clinical"
        db_table = '"clinical"."conditions"'
        ordering = ["display_order"]

    def __str__(self):
        return f"Condition({self.code}, {self.name})"


class PatientCondition(models.Model):
    """
    clinical.patient_conditions — per-patient diagnosis.

    Slice2 columns: patient_link_id, condition_id, stage, onset_date,
    notes, is_active, diagnosed_at.
    condition_id FK → clinical.conditions — expressed as BigIntegerField
    (db_constraint=False) because composite FK across schemas.
    """

    tenant_id = models.BigIntegerField(default=1)
    # FK to clinical.patient_links — no ORM FK (composite cross-schema)
    patient_link_id = models.BigIntegerField()
    # FK to clinical.conditions — expressed as BigIntegerField to avoid
    # Django trying to enforce cross-schema FK constraints
    condition_id = models.BigIntegerField()
    stage = models.TextField(null=True, blank=True)
    onset_date = models.DateField(null=True, blank=True)
    notes = models.TextField(null=True, blank=True)
    is_active = models.BooleanField(default=True)
    diagnosed_at = models.DateTimeField()

    class Meta:
        managed = False
        app_label = "clinical"
        db_table = '"clinical"."patient_conditions"'
        ordering = ["diagnosed_at"]

    def __str__(self):
        return (
            f"PatientCondition(patient_link_id={self.patient_link_id}, "
            f"condition_id={self.condition_id}, is_active={self.is_active})"
        )


class PatientMedication(models.Model):
    """
    clinical.patient_medications — per-patient medication list.

    Slice2 columns: patient_link_id, drug_name, dose, schedule,
    start_date, refill_due_date, end_date, drug_class, is_active,
    notes, created_at.
    """

    tenant_id = models.BigIntegerField(default=1)
    patient_link_id = models.BigIntegerField()
    drug_name = models.TextField()
    dose = models.TextField(null=True, blank=True)
    schedule = models.TextField(null=True, blank=True)
    start_date = models.DateField(null=True, blank=True)
    refill_due_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)          # migration core.py additive col
    drug_class = models.TextField(null=True, blank=True)        # migration core.py additive col
    is_active = models.BooleanField(default=True)
    notes = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField()

    class Meta:
        managed = False
        app_label = "clinical"
        db_table = '"clinical"."patient_medications"'
        ordering = ["-created_at"]

    def __str__(self):
        return (
            f"PatientMedication(drug_name={self.drug_name}, "
            f"patient_link_id={self.patient_link_id}, is_active={self.is_active})"
        )


class ClinicalRule(models.Model):
    """
    clinical.clinical_rules — the If/Then rule catalog.

    trigger_json and action_params_json are JSONB in Postgres; Django returns
    them as Python dicts automatically via the JSONField bridge. We use
    JSONField here so Django handles serialisation correctly.

    Slice2 columns: rule_code, title, category, condition_code, trigger_json,
    human_if, recommendation, dosage_titration, monitoring, contraindications,
    evidence_level, action_type, action_params_json, severity, priority,
    source_ref, is_active, notes.
    """

    tenant_id = models.BigIntegerField(default=1)
    rule_code = models.TextField()
    title = models.TextField()
    category = models.TextField()
    condition_code = models.TextField(default="all")
    # JSONB — Django JSONField maps to JSONB in Postgres via psycopg
    trigger_json = models.JSONField(null=True, blank=True)
    human_if = models.TextField(null=True, blank=True)
    recommendation = models.TextField(null=True, blank=True)
    dosage_titration = models.TextField(null=True, blank=True)
    monitoring = models.TextField(null=True, blank=True)
    contraindications = models.TextField(null=True, blank=True)
    evidence_level = models.TextField(null=True, blank=True)
    action_type = models.TextField(default="educate")
    action_params_json = models.JSONField(null=True, blank=True)
    severity = models.TextField(default="info")
    priority = models.IntegerField(default=100)
    source_ref = models.TextField(null=True, blank=True)
    is_active = models.BooleanField(default=True)
    notes = models.TextField(null=True, blank=True)

    class Meta:
        managed = False
        app_label = "clinical"
        db_table = '"clinical"."clinical_rules"'
        ordering = ["priority", "id"]

    def __str__(self):
        return f"ClinicalRule({self.rule_code}, {self.title})"


class ClinicalIndicator(models.Model):
    """
    clinical.clinical_indicators — indicator metadata (thresholds/targets).
    Live source of truth for warn/danger thresholds used by the rule engine.

    Slice2 columns: key, label, unit, category, direction, warn, danger,
    target, goal_low, goal_high, conditions, risk_weight, is_vital,
    display_order, is_active, notes.
    """

    tenant_id = models.BigIntegerField(default=1)
    key = models.TextField()                         # vital_readings.type key
    label = models.TextField()
    unit = models.TextField(null=True, blank=True)
    category = models.TextField(default="other")    # glycemic|bp|lipid|kidney|anthro|other
    direction = models.TextField(default="high")    # high=worse when higher; low=worse when lower
    warn = models.FloatField(null=True, blank=True)
    danger = models.FloatField(null=True, blank=True)
    target = models.FloatField(null=True, blank=True)
    goal_low = models.FloatField(null=True, blank=True)
    goal_high = models.FloatField(null=True, blank=True)
    conditions = models.TextField(default="all")   # comma-separated condition codes
    risk_weight = models.IntegerField(default=1)
    is_vital = models.BooleanField(default=True)
    display_order = models.IntegerField(default=100)
    is_active = models.BooleanField(default=True)
    notes = models.TextField(null=True, blank=True)

    class Meta:
        managed = False
        app_label = "clinical"
        db_table = '"clinical"."clinical_indicators"'
        ordering = ["display_order"]

    def __str__(self):
        return f"ClinicalIndicator({self.key}, warn={self.warn}, danger={self.danger})"


class PatientFlag(models.Model):
    """
    clinical.patient_flags — per-patient categorical/boolean decision inputs.

    Slice2 columns: patient_link_id, flag_key, value, recorded_by, updated_at.
    Matches the fact bundle 'flag' dict in rule_engine.py.
    """

    tenant_id = models.BigIntegerField(default=1)
    patient_link_id = models.BigIntegerField()
    flag_key = models.TextField()
    value = models.TextField(null=True, blank=True)
    recorded_by = models.TextField(null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        managed = False
        app_label = "clinical"
        db_table = '"clinical"."patient_flags"'
        ordering = ["flag_key"]

    def __str__(self):
        return (
            f"PatientFlag(patient_link_id={self.patient_link_id}, "
            f"flag_key={self.flag_key}, value={self.value})"
        )
