"""
clinical models — managed=False (schema owned by SQL slices).

All clinical tables FK to clinical.patient_links(id) via patient_link_id.
Cross-schema FK to accounting.patients is expressed as BigIntegerField
(db_constraint=False) — the real composite FK lives in the SQL.

PatientLink: thin enrollment record (ADR-0007 §2.1 — no demographic mirror).
VitalReading: the vitals half of the canonical Observation (ADR-0005).
Condition: disease-module catalog (clinical.conditions).
PatientCondition: per-patient diagnosis (clinical.patient_conditions).
PatientMedication: per-patient medication list (clinical.patient_medications).
ClinicalRule: clinical_rules catalog — trigger_json DSL rows (JSONB in PG).
ClinicalIndicator: clinical_indicators — live threshold/target metadata.
PatientFlag: patient_flags — per-patient categorical/bool decision inputs.
"""
from django.db import models


class PatientLink(models.Model):
    """
    clinical.patient_links — enrollment record linking to accounting.patients.

    patient_id is a BigIntegerField (no ORM FK) because the real constraint
    is a composite FK across schemas, which Django cannot represent.
    """

    tenant_id = models.BigIntegerField(default=1)
    # Cross-schema FK expressed as plain int — DB enforces it
    patient_id = models.BigIntegerField()
    wallet_balance = models.DecimalField(max_digits=14, decimal_places=0, default=0)
    sms_opt_out = models.BooleanField(default=False)
    sms_consent = models.BooleanField(default=False)
    sms_consent_at = models.DateTimeField(null=True, blank=True)
    sms_consent_source = models.TextField(null=True, blank=True)
    sms_opt_out_at = models.DateTimeField(null=True, blank=True)
    data_retention_until = models.DateField(null=True, blank=True)
    is_active = models.BooleanField(default=True)
    enrolled_by = models.TextField(null=True, blank=True)
    enrolled_at = models.DateTimeField(auto_now_add=True)
    notes = models.TextField(null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        managed = False
        app_label = "clinical"
        db_table = '"clinical"."patient_links"'
        ordering = ["id"]

    def __str__(self):
        return f"PatientLink(id={self.id}, patient_id={self.patient_id})"


class VitalReading(models.Model):
    """
    clinical.vital_readings — vitals half of Observation canonical (ADR-0005).

    Columns from slice2:
      patient_link_id, type, value, unit, measured_at, source, notes, recorded_by
    slice4b adds:
      encounter_id (nullable FK → clinical.encounters)
    """

    tenant_id = models.BigIntegerField(default=1)
    patient_link_id = models.BigIntegerField()
    type = models.TextField()
    value = models.FloatField()
    unit = models.TextField(null=True, blank=True)
    measured_at = models.DateTimeField()
    source = models.TextField(default="clinic", null=True, blank=True)
    notes = models.TextField(null=True, blank=True)
    recorded_by = models.TextField(null=True, blank=True)
    # slice4b: nullable FK → encounters — the aggregate-root link for the
    # care-loop write path (a reading taken during a registered visit).
    encounter_id = models.BigIntegerField(null=True, blank=True)

    class Meta:
        managed = False
        app_label = "clinical"
        db_table = '"clinical"."vital_readings"'
        ordering = ["-measured_at"]

    def __str__(self):
        return (
            f"VitalReading(type={self.type}, value={self.value}, "
            f"patient_link_id={self.patient_link_id})"
        )


class Condition(models.Model):
    """
    clinical.conditions — disease-module catalog.

    Columns used here: id, tenant_id, name, code, is_active, is_chronic,
    display_order, description, icon, color.
    Slice2 schema: BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY.
    """

    tenant_id = models.BigIntegerField(default=1)
    name = models.TextField()
    code = models.TextField(null=True, blank=True)
    is_active = models.BooleanField(default=True)
    is_chronic = models.BooleanField(default=True)
    display_order = models.IntegerField(default=100)
    description = models.TextField(null=True, blank=True)
    icon = models.TextField(null=True, blank=True)
    color = models.TextField(null=True, blank=True)

    class Meta:
        managed = False
        app_label = "clinical"
        db_table = '"clinical"."conditions"'
        ordering = ["display_order"]

    def __str__(self):
        return f"Condition({self.code}, {self.name})"


class PatientCondition(models.Model):
    """
    clinical.patient_conditions — per-patient diagnosis.

    Slice2 columns: patient_link_id, condition_id, stage, onset_date,
    notes, is_active, diagnosed_at.
    condition_id FK → clinical.conditions — expressed as BigIntegerField
    (db_constraint=False) because composite FK across schemas.
    """

    tenant_id = models.BigIntegerField(default=1)
    # FK to clinical.patient_links — no ORM FK (composite cross-schema)
    patient_link_id = models.BigIntegerField()
    # FK to clinical.conditions — expressed as BigIntegerField to avoid
    # Django trying to enforce cross-schema FK constraints
    condition_id = models.BigIntegerField()
    stage = models.TextField(null=True, blank=True)
    onset_date = models.DateField(null=True, blank=True)
    notes = models.TextField(null=True, blank=True)
    is_active = models.BooleanField(default=True)
    diagnosed_at = models.DateTimeField()

    class Meta:
        managed = False
        app_label = "clinical"
        db_table = '"clinical"."patient_conditions"'
        ordering = ["diagnosed_at"]

    def __str__(self):
        return (
            f"PatientCondition(patient_link_id={self.patient_link_id}, "
            f"condition_id={self.condition_id}, is_active={self.is_active})"
        )


class PatientMedication(models.Model):
    """
    clinical.patient_medications — per-patient medication list.

    Slice2 columns: patient_link_id, drug_name, dose, schedule,
    start_date, refill_due_date, end_date, drug_class, is_active,
    notes, created_at.
    """

    tenant_id = models.BigIntegerField(default=1)
    patient_link_id = models.BigIntegerField()
    drug_name = models.TextField()
    dose = models.TextField(null=True, blank=True)
    schedule = models.TextField(null=True, blank=True)
    start_date = models.DateField(null=True, blank=True)
    refill_due_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)          # migration core.py additive col
    drug_class = models.TextField(null=True, blank=True)        # migration core.py additive col
    is_active = models.BooleanField(default=True)
    notes = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField()

    class Meta:
        managed = False
        app_label = "clinical"
        db_table = '"clinical"."patient_medications"'
        ordering = ["-created_at"]

    def __str__(self):
        return (
            f"PatientMedication(drug_name={self.drug_name}, "
            f"patient_link_id={self.patient_link_id}, is_active={self.is_active})"
        )


class ClinicalRule(models.Model):
    """
    clinical.clinical_rules — the If/Then rule catalog.

    trigger_json and action_params_json are JSONB in Postgres; Django returns
    them as Python dicts automatically via the JSONField bridge. We use
    JSONField here so Django handles serialisation correctly.

    Slice2 columns: rule_code, title, category, condition_code, trigger_json,
    human_if, recommendation, dosage_titration, monitoring, contraindications,
    evidence_level, action_type, action_params_json, severity, priority,
    source_ref, is_active, notes.
    """

    tenant_id = models.BigIntegerField(default=1)
    rule_code = models.TextField()
    title = models.TextField()
    category = models.TextField()
    condition_code = models.TextField(default="all")
    # JSONB — Django JSONField maps to JSONB in Postgres via psycopg
    trigger_json = models.JSONField(null=True, blank=True)
    human_if = models.TextField(null=True, blank=True)
    recommendation = models.TextField(null=True, blank=True)
    dosage_titration = models.TextField(null=True, blank=True)
    monitoring = models.TextField(null=True, blank=True)
    contraindications = models.TextField(null=True, blank=True)
    evidence_level = models.TextField(null=True, blank=True)
    action_type = models.TextField(default="educate")
    action_params_json = models.JSONField(null=True, blank=True)
    severity = models.TextField(default="info")
    priority = models.IntegerField(default=100)
    source_ref = models.TextField(null=True, blank=True)
    is_active = models.BooleanField(default=True)
    notes = models.TextField(null=True, blank=True)

    class Meta:
        managed = False
        app_label = "clinical"
        db_table = '"clinical"."clinical_rules"'
        ordering = ["priority", "id"]

    def __str__(self):
        return f"ClinicalRule({self.rule_code}, {self.title})"


class ClinicalIndicator(models.Model):
    """
    clinical.clinical_indicators — indicator metadata (thresholds/targets).
    Live source of truth for warn/danger thresholds used by the rule engine.

    Slice2 columns: key, label, unit, category, direction, warn, danger,
    target, goal_low, goal_high, conditions, risk_weight, is_vital,
    display_order, is_active, notes.
    """

    tenant_id = models.BigIntegerField(default=1)
    key = models.TextField()                         # vital_readings.type key
    label = models.TextField()
    unit = models.TextField(null=True, blank=True)
    category = models.TextField(default="other")    # glycemic|bp|lipid|kidney|anthro|other
    direction = models.TextField(default="high")    # high=worse when higher; low=worse when lower
    warn = models.FloatField(null=True, blank=True)
    danger = models.FloatField(null=True, blank=True)
    target = models.FloatField(null=True, blank=True)
    goal_low = models.FloatField(null=True, blank=True)
    goal_high = models.FloatField(null=True, blank=True)
    conditions = models.TextField(default="all")   # comma-separated condition codes
    risk_weight = models.IntegerField(default=1)
    is_vital = models.BooleanField(default=True)
    display_order = models.IntegerField(default=100)
    is_active = models.BooleanField(default=True)
    notes = models.TextField(null=True, blank=True)

    class Meta:
        managed = False
        app_label = "clinical"
        db_table = '"clinical"."clinical_indicators"'
        ordering = ["display_order"]

    def __str__(self):
        return f"ClinicalIndicator({self.key}, warn={self.warn}, danger={self.danger})"


class PatientFlag(models.Model):
    """
    clinical.patient_flags — per-patient categorical/boolean decision inputs.

    Slice2 columns: patient_link_id, flag_key, value, recorded_by, updated_at.
    Matches the fact bundle 'flag' dict in rule_engine.py.
    """

    tenant_id = models.BigIntegerField(default=1)
    patient_link_id = models.BigIntegerField()
    flag_key = models.TextField()
    value = models.TextField(null=True, blank=True)
    recorded_by = models.TextField(null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        managed = False
        app_label = "clinical"
        db_table = '"clinical"."patient_flags"'
        ordering = ["flag_key"]

    def __str__(self):
        return (
            f"PatientFlag(patient_link_id={self.patient_link_id}, "
            f"flag_key={self.flag_key}, value={self.value})"
        )


class FollowupTask(models.Model):
    """
    clinical.followup_tasks — follow-up worklist items.

    Slice2 columns (from schema_pg_slice2_clinical.sql lines 449-468):
      tenant_id, patient_link_id,
      due_date (DATE nullable), reason, detail,
      status CHECK('open'|'done'|'dismissed') DEFAULT 'open',
      assigned_to, call_log,
      source_rule (additive migration), source_event (additive migration),
      appointment_id (additive migration),
      fulfillment CHECK('in_person'|'remote') DEFAULT 'in_person' (additive migration),
      created_at TIMESTAMPTZ DEFAULT now(),
      resolved_at TIMESTAMPTZ nullable.
    """

    STATUS_OPEN = "open"
    STATUS_DONE = "done"
    STATUS_DISMISSED = "dismissed"

    FULFILLMENT_IN_PERSON = "in_person"
    FULFILLMENT_REMOTE = "remote"

    tenant_id = models.BigIntegerField(default=1)
    patient_link_id = models.BigIntegerField()
    due_date = models.DateField(null=True, blank=True)
    reason = models.TextField(null=True, blank=True)
    detail = models.TextField(null=True, blank=True)
    status = models.TextField(default="open")
    assigned_to = models.TextField(null=True, blank=True)
    call_log = models.TextField(null=True, blank=True)
    source_rule = models.TextField(null=True, blank=True)   # additive migration col
    source_event = models.TextField(null=True, blank=True)  # additive migration col
    appointment_id = models.BigIntegerField(null=True, blank=True)  # additive migration col
    fulfillment = models.TextField(default="in_person", null=True, blank=True)  # additive migration col
    created_at = models.DateTimeField()
    resolved_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        managed = False
        app_label = "clinical"
        db_table = '"clinical"."followup_tasks"'
        ordering = ["due_date", "id"]

    def __str__(self):
        return (
            f"FollowupTask(id={self.id}, patient_link_id={self.patient_link_id}, "
            f"status={self.status}, due_date={self.due_date})"
        )


class SuggestionLog(models.Model):
    """
    clinical.suggestion_log — physician accept/dismiss of clinical suggestions.

    Slice2 columns (from schema_pg_slice2_clinical.sql lines 475-491):
      tenant_id, patient_link_id, rule_code,
      suggestion_text, evidence_level,
      status CHECK('pending'|'accepted'|'dismissed') DEFAULT 'pending',
      acted_by, acted_at TIMESTAMPTZ nullable, note,
      created_at TIMESTAMPTZ DEFAULT now().
    UNIQUE(tenant_id, patient_link_id, rule_code) — one log per (patient, rule).
    Upsert semantics: UPDATE if row already exists for (patient_link_id, rule_code).
    """

    STATUS_PENDING = "pending"
    STATUS_ACCEPTED = "accepted"
    STATUS_DISMISSED = "dismissed"

    tenant_id = models.BigIntegerField(default=1)
    patient_link_id = models.BigIntegerField()
    rule_code = models.TextField()
    suggestion_text = models.TextField(null=True, blank=True)
    evidence_level = models.TextField(null=True, blank=True)
    status = models.TextField(default="pending")
    acted_by = models.TextField(null=True, blank=True)
    acted_at = models.DateTimeField(null=True, blank=True)
    note = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField()

    class Meta:
        managed = False
        app_label = "clinical"
        db_table = '"clinical"."suggestion_log"'
        ordering = ["-created_at"]
        # DB-enforced: UNIQUE(tenant_id, patient_link_id, rule_code)

    def __str__(self):
        return (
            f"SuggestionLog(patient_link_id={self.patient_link_id}, "
            f"rule_code={self.rule_code}, status={self.status})"
        )


class Observation(models.Model):
    """
    clinical.observations — canonical UNION VIEW of vital_readings + lab_results.

    ADR-0005: the single source-agnostic read path for the rule engine.
    This model is READ-ONLY (managed=False on a VIEW — never write, save, or delete).

    Columns (from the CREATE OR REPLACE VIEW in schema_pg_slice2_clinical.sql §6):
      source_table  : 'vital' | 'lab'
      source_id     : BIGINT — the PK of the originating row in its table
      tenant_id     : BIGINT
      patient_link_id : BIGINT
      obs_key       : TEXT — namespace-prefixed since slice4a: 'vital:<type>' OR 'lab:<COALESCE(test_key,test_name)>'
      test_name     : TEXT | NULL — original lab test_name (NULL for vitals)
      value         : REAL
      unit          : TEXT | NULL
      ref_low       : REAL | NULL — lab reference range low (NULL for vitals)
      ref_high      : REAL | NULL — lab reference range high (NULL for vitals)
      observed_at   : TIMESTAMPTZ — measured_at (vitals) or taken_at (labs)
      source        : TEXT | NULL — 'clinic' / 'lab' etc.
      recorded_by   : TEXT | NULL

    PRIMARY KEY NOTE: source_id is declared as primary_key=True so Django can
    build a model identity — BUT it is NOT globally unique across the UNION.
    A vital row with id=5 and a lab row with id=5 both map to source_id=5.
    This is acceptable because this model is used ONLY for read iteration
    (DISTINCT ON / order_by queries); it is never used for identity-map
    get()/update()/save() operations. Do not call .save() or .delete() on
    Observation instances.
    """

    source_table = models.TextField()           # 'vital' | 'lab'
    source_id = models.BigIntegerField(primary_key=True)  # NOT globally unique — see note above
    tenant_id = models.BigIntegerField(default=1)
    patient_link_id = models.BigIntegerField()
    obs_key = models.TextField()                # namespace-prefixed: 'vital:<type>' | 'lab:<key>' (slice4a)
    test_name = models.TextField(null=True, blank=True)
    value = models.FloatField(null=True, blank=True)
    unit = models.TextField(null=True, blank=True)
    ref_low = models.FloatField(null=True, blank=True)
    ref_high = models.FloatField(null=True, blank=True)
    observed_at = models.DateTimeField()
    source = models.TextField(null=True, blank=True)
    recorded_by = models.TextField(null=True, blank=True)

    class Meta:
        managed = False
        app_label = "clinical"
        db_table = '"clinical"."observations"'
        ordering = ["obs_key", "-observed_at"]

    def save(self, *args, **kwargs):
        raise NotImplementedError(
            "Observation is a read-only VIEW model. Do not write to it."
        )

    def delete(self, *args, **kwargs):
        raise NotImplementedError(
            "Observation is a read-only VIEW model. Do not write to it."
        )

    def __str__(self):
        return (
            f"Observation(source={self.source_table}, obs_key={self.obs_key}, "
            f"value={self.value}, patient_link_id={self.patient_link_id})"
        )


class Appointment(models.Model):
    """
    clinical.appointments — scheduled patient appointments.

    Base columns from schema_pg_slice2_clinical.sql §appointments:
      id, tenant_id, patient_link_id, scheduled_at TIMESTAMPTZ NOT NULL,
      appt_type TEXT, status TEXT CHECK('scheduled'|'done'|'no_show'|'cancelled'),
      recurrence_months INTEGER, parent_appointment_id BIGINT,
      reminder_sent BOOLEAN DEFAULT FALSE, notes TEXT,
      created_by TEXT, created_at TIMESTAMPTZ.

    Additive columns from schema_pg_slice4b_clinical_model.sql §6 (ALTER TABLE):
      doctor_id BIGINT (nullable; cross-schema FK → accounting.medical_staff, ON DELETE SET NULL)
      chief_complaint TEXT (nullable)

    FK conventions (managed=False — real FKs live in SQL):
      - patient_link_id: composite FK (tenant_id, patient_link_id) → clinical.patient_links
      - doctor_id: composite cross-schema FK (tenant_id, doctor_id) → accounting.medical_staff
      - parent_appointment_id: soft self-reference (nullable BIGINT, no ORM FK)
    """

    STATUS_SCHEDULED = "scheduled"
    STATUS_DONE = "done"
    STATUS_NO_SHOW = "no_show"
    STATUS_CANCELLED = "cancelled"

    STATUS_CHOICES = [
        (STATUS_SCHEDULED, "Scheduled"),
        (STATUS_DONE, "Done"),
        (STATUS_NO_SHOW, "No Show"),
        (STATUS_CANCELLED, "Cancelled"),
    ]

    tenant_id = models.BigIntegerField(default=1)
    patient_link_id = models.BigIntegerField()
    scheduled_at = models.DateTimeField()
    appt_type = models.TextField(null=True, blank=True)          # visit|lab|checkup
    status = models.TextField(default="scheduled")               # CHECK in DB
    recurrence_months = models.IntegerField(null=True, blank=True)
    # Soft self-reference (nullable BIGINT, no ORM FK — DB has no FK on this col)
    parent_appointment_id = models.BigIntegerField(null=True, blank=True)
    reminder_sent = models.BooleanField(default=False)
    notes = models.TextField(null=True, blank=True)
    created_by = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField()
    # slice4b additive columns
    # doctor_id: cross-schema FK (tenant_id, doctor_id) → accounting.medical_staff
    # db_constraint=False — the real composite FK lives in SQL
    doctor_id = models.BigIntegerField(null=True, blank=True)    # nullable; ON DELETE SET NULL
    chief_complaint = models.TextField(null=True, blank=True)

    class Meta:
        managed = False
        app_label = "clinical"
        db_table = '"clinical"."appointments"'
        ordering = ["scheduled_at"]

    def __str__(self):
        return (
            f"Appointment(id={self.id}, patient_link_id={self.patient_link_id}, "
            f"status={self.status}, scheduled_at={self.scheduled_at})"
        )


class LabResult(models.Model):
    """
    clinical.lab_results — lab test results (the lab half of the Observation canonical).

    Base columns from schema_pg_slice2_clinical.sql §lab_results:
      id, tenant_id, patient_link_id, test_name TEXT NOT NULL,
      test_key TEXT (nullable; soft FK to lab_test_catalog.test_key),
      value REAL, unit TEXT, ref_low REAL, ref_high REAL,
      taken_at TIMESTAMPTZ NOT NULL, notes TEXT, recorded_by TEXT.

    Additive column from schema_pg_slice4b_clinical_model.sql §3b (ALTER TABLE):
      encounter_id BIGINT (nullable; composite FK (tenant_id, encounter_id)
      → clinical.encounters(tenant_id, id) ON DELETE SET NULL)

    FK conventions (managed=False — real FKs live in SQL):
      - patient_link_id: composite FK (tenant_id, patient_link_id) → clinical.patient_links
      - encounter_id: composite FK (tenant_id, encounter_id) → clinical.encounters
      - test_key: soft reference to lab_test_catalog.test_key (nullable TEXT, no ORM FK)
    """

    tenant_id = models.BigIntegerField(default=1)
    patient_link_id = models.BigIntegerField()
    test_name = models.TextField()
    test_key = models.TextField(null=True, blank=True)           # soft ref to lab_test_catalog
    value = models.FloatField(null=True, blank=True)
    unit = models.TextField(null=True, blank=True)
    ref_low = models.FloatField(null=True, blank=True)
    ref_high = models.FloatField(null=True, blank=True)
    taken_at = models.DateTimeField()
    notes = models.TextField(null=True, blank=True)
    recorded_by = models.TextField(null=True, blank=True)
    # slice4b additive column — nullable composite FK → encounters
    encounter_id = models.BigIntegerField(null=True, blank=True)

    class Meta:
        managed = False
        app_label = "clinical"
        db_table = '"clinical"."lab_results"'
        ordering = ["-taken_at"]

    def __str__(self):
        return (
            f"LabResult(test_name={self.test_name}, value={self.value}, "
            f"patient_link_id={self.patient_link_id})"
        )


class Encounter(models.Model):
    """
    clinical.encounters — visit / clinical contact record (aggregate root for write path).

    Source: schema_pg_slice4b_clinical_model.sql §2.

    Columns:
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tenant_id BIGINT NOT NULL DEFAULT 1 (FK → platform.tenants),
      patient_link_id BIGINT NOT NULL (composite FK (tenant_id, patient_link_id)
        → clinical.patient_links),
      doctor_id BIGINT nullable (cross-schema composite FK (tenant_id, doctor_id)
        → accounting.medical_staff ON DELETE SET NULL),
      encounter_type TEXT NOT NULL DEFAULT 'visit'
        CHECK IN ('visit','follow_up','phone','remote'),
      encounter_at TIMESTAMPTZ NOT NULL,
      chief_complaint TEXT nullable,
      status TEXT NOT NULL DEFAULT 'open'
        CHECK IN ('open','completed','cancelled'),
      completed_at TIMESTAMPTZ nullable,
      summary_note TEXT nullable,
      appointment_id BIGINT nullable (composite FK (tenant_id, appointment_id)
        → clinical.appointments ON DELETE SET NULL),
      accounting_invoice_id BIGINT nullable (cross-schema composite FK DEFERRABLE
        → accounting.invoices ON DELETE SET NULL),
      created_by TEXT nullable,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT now() (auto-updated by DB trigger).

    UNIQUE(tenant_id, id) — for composite FK targeting by child tables.

    FK conventions (managed=False — real FKs live in SQL):
      - patient_link_id: composite FK → clinical.patient_links
      - doctor_id: cross-schema composite FK → accounting.medical_staff
      - appointment_id: composite FK → clinical.appointments
      - accounting_invoice_id: cross-schema composite FK (DEFERRABLE) → accounting.invoices

    This is a READ+WRITE model — it will be written in Step 10. No write logic here.
    """

    ENCOUNTER_TYPE_VISIT = "visit"
    ENCOUNTER_TYPE_FOLLOW_UP = "follow_up"
    ENCOUNTER_TYPE_PHONE = "phone"
    ENCOUNTER_TYPE_REMOTE = "remote"

    ENCOUNTER_TYPE_CHOICES = [
        (ENCOUNTER_TYPE_VISIT, "Visit"),
        (ENCOUNTER_TYPE_FOLLOW_UP, "Follow-up"),
        (ENCOUNTER_TYPE_PHONE, "Phone"),
        (ENCOUNTER_TYPE_REMOTE, "Remote"),
    ]

    STATUS_OPEN = "open"
    STATUS_COMPLETED = "completed"
    STATUS_CANCELLED = "cancelled"

    STATUS_CHOICES = [
        (STATUS_OPEN, "Open"),
        (STATUS_COMPLETED, "Completed"),
        (STATUS_CANCELLED, "Cancelled"),
    ]

    tenant_id = models.BigIntegerField(default=1)
    patient_link_id = models.BigIntegerField()
    # doctor_id: cross-schema FK (tenant_id, doctor_id) → accounting.medical_staff
    # db_constraint not expressed in ORM — real composite FK lives in SQL
    doctor_id = models.BigIntegerField(null=True, blank=True)
    encounter_type = models.TextField(default="visit")           # CHECK enforced by DB
    encounter_at = models.DateTimeField()
    chief_complaint = models.TextField(null=True, blank=True)
    status = models.TextField(default="open")                    # CHECK enforced by DB
    completed_at = models.DateTimeField(null=True, blank=True)
    summary_note = models.TextField(null=True, blank=True)
    # appointment_id: composite FK (tenant_id, appointment_id) → clinical.appointments
    appointment_id = models.BigIntegerField(null=True, blank=True)
    # accounting_invoice_id: cross-schema composite FK DEFERRABLE → accounting.invoices
    # nullable snapshot — never a real accounting write; just an id reference
    accounting_invoice_id = models.BigIntegerField(null=True, blank=True)
    created_by = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField()
    # updated_at is maintained by DB trigger trg_encounters_updated_at (slice4b)
    # auto_now=False — we don't want Django to override the DB trigger on every save
    updated_at = models.DateTimeField()

    class Meta:
        managed = False
        app_label = "clinical"
        db_table = '"clinical"."encounters"'
        ordering = ["-encounter_at"]

    def __str__(self):
        return (
            f"Encounter(id={self.id}, patient_link_id={self.patient_link_id}, "
            f"type={self.encounter_type}, status={self.status})"
        )


class Prescription(models.Model):
    """
    clinical.prescriptions — free-form or insurance prescription header.

    Base columns (schema_pg_slice2_clinical.sql §prescriptions, lines 552-568):
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tenant_id BIGINT NOT NULL DEFAULT 1 (FK → platform.tenants),
      patient_link_id BIGINT NOT NULL (composite FK (tenant_id, patient_link_id)
        → clinical.patient_links),
      kind TEXT NOT NULL,
      items JSONB nullable (legacy denormalized snapshot),
      mode TEXT DEFAULT 'free'  — free|insurance,
      insurer TEXT nullable,
      portal_rx_id TEXT nullable,
      prescriber_user_id BIGINT nullable (logical FK to platform.users),
      followup_task_id BIGINT nullable,
      issued_at TIMESTAMPTZ NOT NULL DEFAULT now().

    Additive columns from schema_pg_slice4b_clinical_model.sql §3d (ALTER TABLE):
      encounter_id BIGINT nullable (composite FK (tenant_id, encounter_id)
        → clinical.encounters ON DELETE SET NULL).

    Additive constraint from schema_pg_slice4b_clinical_model.sql §1:
      UNIQUE(tenant_id, id) — prerequisite for the composite FK from
      prescription_items → prescriptions.

    FK conventions (managed=False — real FKs live in SQL):
      - patient_link_id: composite FK → clinical.patient_links
      - encounter_id: composite FK → clinical.encounters (nullable, ON DELETE SET NULL)
      - prescriber_user_id: logical cross-schema FK to platform.users (BigIntegerField)
      - followup_task_id: logical FK to clinical.followup_tasks (BigIntegerField)
    """

    MODE_FREE = "free"
    MODE_INSURANCE = "insurance"

    MODE_CHOICES = [
        (MODE_FREE, "Free"),
        (MODE_INSURANCE, "Insurance"),
    ]

    tenant_id = models.BigIntegerField(default=1)
    patient_link_id = models.BigIntegerField()
    kind = models.TextField()
    # items: JSONB legacy denormalized snapshot — nullable; PrescriptionItem rows
    # carry the structured form of the same data
    items = models.JSONField(null=True, blank=True)
    mode = models.TextField(default="free")                         # CHECK in DB (free|insurance)
    insurer = models.TextField(null=True, blank=True)
    portal_rx_id = models.TextField(null=True, blank=True)
    # prescriber_user_id: logical cross-schema FK → platform.users
    # db_constraint=False — the real FK is not yet enforced in SQL
    prescriber_user_id = models.BigIntegerField(null=True, blank=True)
    # followup_task_id: logical FK → clinical.followup_tasks
    followup_task_id = models.BigIntegerField(null=True, blank=True)
    issued_at = models.DateTimeField()
    # slice4b additive column — nullable composite FK → encounters (ON DELETE SET NULL)
    encounter_id = models.BigIntegerField(null=True, blank=True)

    class Meta:
        managed = False
        app_label = "clinical"
        db_table = '"clinical"."prescriptions"'
        ordering = ["-issued_at"]

    def __str__(self):
        return (
            f"Prescription(id={self.id}, patient_link_id={self.patient_link_id}, "
            f"kind={self.kind!r}, mode={self.mode})"
        )


class PrescriptionItem(models.Model):
    """
    clinical.prescription_items — structured line-items of a prescription.

    Created in schema_pg_slice4b_clinical_model.sql §5 (lines 284-320).

    Columns:
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tenant_id BIGINT NOT NULL DEFAULT 1 (FK → platform.tenants),
      prescription_id BIGINT NOT NULL (composite FK (tenant_id, prescription_id)
        → clinical.prescriptions (tenant_id, id) ON DELETE CASCADE),
      drug_name TEXT NOT NULL,
      drug_class TEXT nullable (soft ref to drug_classes.class_key — no FK enforced),
      dose_value NUMERIC(10,3) nullable → DecimalField,
      dose_unit TEXT nullable,
      frequency TEXT nullable CHECK IN allowed set,
      route TEXT nullable CHECK IN allowed set,
      quantity INTEGER nullable CHECK > 0,
      duration_days INTEGER nullable CHECK > 0,
      instructions TEXT nullable.

    FK conventions (managed=False — real FKs live in SQL):
      - prescription_id: composite FK (tenant_id, prescription_id) → prescriptions
        ON DELETE CASCADE.  ORM sees it as BigIntegerField (db_constraint=False).
      - drug_class: soft TEXT reference to drug_classes.class_key (no FK enforced).
    """

    FREQUENCY_CHOICES = [
        ("od", "Once daily"),
        ("bid", "Twice daily"),
        ("tid", "Three times daily"),
        ("qid", "Four times daily"),
        ("qod", "Every other day"),
        ("weekly", "Weekly"),
        ("monthly", "Monthly"),
        ("prn", "As needed"),
        ("with_meal", "With meal"),
        ("bedtime", "At bedtime"),
        ("other", "Other"),
    ]

    ROUTE_CHOICES = [
        ("oral", "Oral"),
        ("sublingual", "Sublingual"),
        ("sc", "Subcutaneous"),
        ("im", "Intramuscular"),
        ("iv", "Intravenous"),
        ("topical", "Topical"),
        ("inhaled", "Inhaled"),
        ("other", "Other"),
    ]

    ALLOWED_FREQUENCIES = frozenset(v for v, _ in FREQUENCY_CHOICES)
    ALLOWED_ROUTES = frozenset(v for v, _ in ROUTE_CHOICES)

    tenant_id = models.BigIntegerField(default=1)
    # FK to prescriptions — composite (tenant_id, prescription_id); DB CASCADE
    prescription_id = models.BigIntegerField()
    drug_name = models.TextField()
    # drug_class: soft reference to drug_classes.class_key (nullable, no ORM FK)
    drug_class = models.TextField(null=True, blank=True)
    # dose_value: NUMERIC(10,3) — use DecimalField for precision
    dose_value = models.DecimalField(
        max_digits=13, decimal_places=3, null=True, blank=True
    )
    dose_unit = models.TextField(null=True, blank=True)
    frequency = models.TextField(
        null=True, blank=True, choices=FREQUENCY_CHOICES
    )                                                               # CHECK enforced by DB
    route = models.TextField(
        null=True, blank=True, choices=ROUTE_CHOICES
    )                                                               # CHECK enforced by DB
    quantity = models.IntegerField(null=True, blank=True)          # CHECK > 0 in DB
    duration_days = models.IntegerField(null=True, blank=True)     # CHECK > 0 in DB
    instructions = models.TextField(null=True, blank=True)

    class Meta:
        managed = False
        app_label = "clinical"
        db_table = '"clinical"."prescription_items"'
        ordering = ["id"]

    def __str__(self):
        return (
            f"PrescriptionItem(drug_name={self.drug_name!r}, "
            f"prescription_id={self.prescription_id}, "
            f"dose_value={self.dose_value} {self.dose_unit or ''})"
        )


class DoctorVisitLog(models.Model):
    """
    clinical.doctor_visit_log — physician visit-queue state tracker.

    Boundary ledger: accounting_invoice_id is a snapshot cross-schema reference
    (FK enforced by slice4 SQL; never written from clinical).  The queue state
    (waiting → in_progress → done) lives ONLY here — accounting is read-only.

    Schema (schema_pg_slice2_clinical.sql §doctor_visit_log):
      id, tenant_id, accounting_invoice_id (NOT NULL, snapshot),
      UNIQUE(tenant_id, accounting_invoice_id),
      patient_link_id (nullable, composite FK → patient_links),
      patient_uuid UUID (snapshot; ADR-0007 §2.4 — uuid not national_id),
      full_name TEXT (snapshot), work_date DATE,
      status TEXT DEFAULT 'waiting' CHECK IN ('waiting','in_progress','done'),
      started_at TIMESTAMPTZ, done_at TIMESTAMPTZ,
      physician_notes TEXT, done_by TEXT, created_at TIMESTAMPTZ DEFAULT now().

    FK conventions (managed=False — real FK lives in slice4 SQL):
      - accounting_invoice_id: cross-schema snapshot; BigIntegerField(db_constraint=False).
      - patient_link_id: composite FK (tenant_id, patient_link_id) → clinical.patient_links;
        expressed as BigIntegerField (nullable — invoice may arrive before enrollment).
    """

    STATUS_WAITING = "waiting"
    STATUS_IN_PROGRESS = "in_progress"
    STATUS_DONE = "done"

    STATUS_CHOICES = [
        (STATUS_WAITING, "Waiting"),
        (STATUS_IN_PROGRESS, "In Progress"),
        (STATUS_DONE, "Done"),
    ]

    tenant_id = models.BigIntegerField(default=1)
    # Cross-schema snapshot reference — NOT a real ORM FK (managed=False + cross-schema).
    # The real composite FK (tenant_id, accounting_invoice_id) → accounting.invoices
    # is declared in schema_pg_slice4_boundary.sql (fk_doctor_visit_log_acct).
    accounting_invoice_id = models.BigIntegerField()
    # Nullable: patient may not be enrolled yet when the invoice first appears.
    # Composite FK (tenant_id, patient_link_id) → clinical.patient_links (DB enforces).
    patient_link_id = models.BigIntegerField(null=True, blank=True)
    # patient_uuid: ADR-0007 §2.4 snapshot — uuid (not national_id)
    patient_uuid = models.UUIDField(null=True, blank=True)
    full_name = models.TextField()
    work_date = models.DateField()
    status = models.TextField(default="waiting")   # CHECK enforced by DB
    started_at = models.DateTimeField(null=True, blank=True)
    done_at = models.DateTimeField(null=True, blank=True)
    physician_notes = models.TextField(null=True, blank=True)
    done_by = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        managed = False
        app_label = "clinical"
        db_table = '"clinical"."doctor_visit_log"'
        ordering = ["work_date", "id"]
        # DB-enforced: UNIQUE(tenant_id, accounting_invoice_id)

    def __str__(self):
        return (
            f"DoctorVisitLog(invoice={self.accounting_invoice_id}, "
            f"status={self.status}, work_date={self.work_date})"
        )


class EngagementEvent(models.Model):
    """
    clinical.engagement_events — manager-editable event→channel routing table.

    Each row describes one type of patient outreach event: what channel to use
    (sms|worklist|both|off), the SMS template, cooldown, and source_action that
    feeds it.  The engagement dispatcher reads this table at dispatch time.

    Schema (schema_pg_slice2_clinical.sql §engagement_events):
      id, tenant_id, event_key TEXT NOT NULL, label TEXT NOT NULL,
      category TEXT DEFAULT 'clinical' CHECK IN ('operational','clinical','marketing'),
      channel TEXT DEFAULT 'worklist' CHECK IN ('sms','worklist','both','off'),
      sms_template TEXT, lead_days INTEGER DEFAULT 0,
      cooldown_days INTEGER DEFAULT 30, source_action TEXT,
      priority INTEGER DEFAULT 100,
      event_type TEXT (additive migration),
      is_custom BOOLEAN DEFAULT FALSE (additive migration),
      is_active BOOLEAN DEFAULT TRUE, notes TEXT.
      UNIQUE(tenant_id, event_key).

    FK conventions (managed=False — real FKs live in SQL):
      - tenant_id: FK → platform.tenants (expressed as BigIntegerField).
    CHECK constraints (category, channel) are enforced by the DB; Django
    choices are listed here for documentation, not DB-level enforcement.
    """

    CATEGORY_OPERATIONAL = "operational"
    CATEGORY_CLINICAL = "clinical"
    CATEGORY_MARKETING = "marketing"

    CATEGORY_CHOICES = [
        (CATEGORY_OPERATIONAL, "Operational"),
        (CATEGORY_CLINICAL, "Clinical"),
        (CATEGORY_MARKETING, "Marketing"),
    ]

    CHANNEL_SMS = "sms"
    CHANNEL_WORKLIST = "worklist"
    CHANNEL_BOTH = "both"
    CHANNEL_OFF = "off"

    CHANNEL_CHOICES = [
        (CHANNEL_SMS, "SMS"),
        (CHANNEL_WORKLIST, "Worklist"),
        (CHANNEL_BOTH, "Both"),
        (CHANNEL_OFF, "Off"),
    ]

    tenant_id = models.BigIntegerField(default=1)
    event_key = models.TextField()
    label = models.TextField()
    # CHECK(category IN ('operational','clinical','marketing')) enforced by DB
    category = models.TextField(default="clinical", choices=CATEGORY_CHOICES)
    # CHECK(channel IN ('sms','worklist','both','off')) enforced by DB
    channel = models.TextField(default="worklist", choices=CHANNEL_CHOICES)
    sms_template = models.TextField(null=True, blank=True)
    lead_days = models.IntegerField(default=0)
    cooldown_days = models.IntegerField(default=30)
    source_action = models.TextField(null=True, blank=True)
    priority = models.IntegerField(default=100)
    # additive migration columns (core.py _ensure_column)
    event_type = models.TextField(null=True, blank=True)
    is_custom = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    notes = models.TextField(null=True, blank=True)

    class Meta:
        managed = False
        app_label = "clinical"
        db_table = '"clinical"."engagement_events"'
        ordering = ["priority", "id"]
        # DB-enforced: UNIQUE(tenant_id, event_key)

    def __str__(self):
        return (
            f"EngagementEvent(event_key={self.event_key!r}, "
            f"channel={self.channel}, tenant_id={self.tenant_id})"
        )


class EngagementDispatch(models.Model):
    """
    clinical.engagement_dispatch — idempotency/cooldown ledger.

    One row per (tenant, patient, event, period_key, channel) — the 5-column
    UNIQUE constraint is the hard idempotency guarantee that Step 18's dispatch
    logic relies on.  A second attempt for the same bucket raises IntegrityError
    which the dispatcher treats as "already sent".

    period_key is a TEXT bucket key (e.g. 'hba1c-2026-Q2', 'visit-2026-07-15')
    — not a DATE. ref_id is the sms_messages.id or followup_tasks.id that was
    created for this dispatch.

    Schema (schema_pg_slice2_clinical.sql §engagement_dispatch):
      id, tenant_id, patient_link_id (composite FK → patient_links),
      event_key TEXT NOT NULL, period_key TEXT NOT NULL,
      channel TEXT NOT NULL (sms|worklist),
      ref_id BIGINT (sms_messages.id or followup_tasks.id),
      status TEXT DEFAULT 'done', created_at TIMESTAMPTZ DEFAULT now().
      UNIQUE(tenant_id, patient_link_id, event_key, period_key, channel).

    FK conventions (managed=False — real FKs live in SQL):
      - patient_link_id: composite FK (tenant_id, patient_link_id) → patient_links.
      - event_key: composite FK (tenant_id, event_key) → engagement_events
        (slice2b fk_engagement_dispatch_event_key — ON DELETE RESTRICT).
        A dispatch row CANNOT be inserted unless the matching engagement_events
        row already exists for that tenant.
      - ref_id: logical reference; no ORM FK.
    """

    tenant_id = models.BigIntegerField(default=1)
    # composite FK (tenant_id, patient_link_id) → clinical.patient_links — DB enforces
    patient_link_id = models.BigIntegerField()
    event_key = models.TextField()
    period_key = models.TextField()                     # dedupe bucket — TEXT, not DATE
    channel = models.TextField()                        # sms|worklist — CHECK in DB
    # logical ref: sms_messages.id or followup_tasks.id (nullable)
    ref_id = models.BigIntegerField(null=True, blank=True)
    status = models.TextField(default="done")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        managed = False
        app_label = "clinical"
        db_table = '"clinical"."engagement_dispatch"'
        ordering = ["-created_at"]
        # DB-enforced: UNIQUE(tenant_id, patient_link_id, event_key, period_key, channel)

    def __str__(self):
        return (
            f"EngagementDispatch(patient_link_id={self.patient_link_id}, "
            f"event_key={self.event_key!r}, period_key={self.period_key!r}, "
            f"channel={self.channel}, status={self.status})"
        )


class EngagementApproval(models.Model):
    """
    clinical.engagement_approvals — physician approval queue for outreach.

    Every SMS-channel engagement event must be approved by a manager before
    the provider sends it (Step 18). This table IS the hard gate.

    Schema (schema_pg_slice2_clinical.sql §engagement_approvals):
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tenant_id BIGINT NOT NULL DEFAULT 1 REFERENCES platform.tenants(id),
      patient_link_id BIGINT NOT NULL (composite FK → clinical.patient_links),
      event_key TEXT NOT NULL,
      channel TEXT,
      due_date DATE,
      message TEXT,
      offer TEXT (Phase-8 pricing reserve),
      status TEXT DEFAULT 'pending',
      period_key TEXT,
      appointment_id BIGINT (nullable, logical FK to appointments),
      decided_by TEXT,
      decided_at TIMESTAMPTZ,
      sent_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now().
      UNIQUE(tenant_id, patient_link_id, event_key, period_key).

    Status constants:
      STATUS_PENDING  = 'pending'   — awaiting manager decision
      STATUS_APPROVED = 'approved'  — manager approved; eligible for Step-18 send
      STATUS_REJECTED = 'rejected'  — manager rejected; will not be sent
      STATUS_SENT     = 'sent'      — Step 18 will add this (sent_at populated)

    State machine (Step 17):
      pending → approved (approve)
      pending → rejected (reject)
      approved → sent    (Step 18 only — not implemented here)

    FK conventions (managed=False — real FKs live in SQL):
      - tenant_id: FK → platform.tenants.
      - patient_link_id: composite FK (tenant_id, patient_link_id) → patient_links.
      - appointment_id: logical nullable FK → clinical.appointments (no ORM FK).
    """

    STATUS_PENDING = "pending"
    STATUS_APPROVED = "approved"
    STATUS_REJECTED = "rejected"
    STATUS_SENT = "sent"   # Step 18 will transition approved → sent after actual send

    STATUS_CHOICES = [
        (STATUS_PENDING, "Pending"),
        (STATUS_APPROVED, "Approved"),
        (STATUS_REJECTED, "Rejected"),
        (STATUS_SENT, "Sent"),
    ]

    tenant_id = models.BigIntegerField(default=1)
    # composite FK (tenant_id, patient_link_id) → clinical.patient_links — DB enforces
    patient_link_id = models.BigIntegerField()
    event_key = models.TextField()
    channel = models.TextField(null=True, blank=True)   # sms | worklist | both (Step 18 sends sms)
    due_date = models.DateField(null=True, blank=True)  # calendar date YYYY-MM-DD
    message = models.TextField(null=True, blank=True)   # rendered SMS body
    offer = models.TextField(null=True, blank=True)     # Phase-8 pricing reserve
    status = models.TextField(default="pending")        # CHECK would be nice; enforced by service
    period_key = models.TextField(null=True, blank=True)  # dedup bucket (same as dispatch)
    # appointment_id: logical nullable FK → clinical.appointments (no ORM FK)
    appointment_id = models.BigIntegerField(null=True, blank=True)
    decided_by = models.TextField(null=True, blank=True)   # username of deciding manager
    decided_at = models.DateTimeField(null=True, blank=True)
    sent_at = models.DateTimeField(null=True, blank=True)   # Step 18 populates this
    created_at = models.DateTimeField()

    class Meta:
        managed = False
        app_label = "clinical"
        db_table = '"clinical"."engagement_approvals"'
        ordering = ["due_date", "-created_at"]
        # DB-enforced: UNIQUE(tenant_id, patient_link_id, event_key, period_key)

    def __str__(self):
        return (
            f"EngagementApproval(id={self.id}, patient_link_id={self.patient_link_id}, "
            f"event_key={self.event_key!r}, period_key={self.period_key!r}, "
            f"status={self.status})"
        )


class DdiPair(models.Model):
    """
    clinical.ddi_pairs — Drug-Drug Interaction catalog (slice8).

    Each row is a known pharmacologic class-pair interaction, curated by the
    clinical pharmacist. class_a < class_b (canonical order — DB CHECK enforced)
    so lookup is order-independent: always canonicalize with tuple(sorted(...)).

    Columns (schema_pg_slice8_ddi.sql):
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      tenant_id BIGINT NOT NULL DEFAULT 1 (FK → platform.tenants),
      class_a TEXT NOT NULL,
      class_b TEXT NOT NULL,
      severity TEXT NOT NULL CHECK IN ('contraindicated','major','moderate','minor'),
      message_fa TEXT NOT NULL — Persian clinical message (verbatim from pharmacist),
      evidence TEXT nullable — citation / reference,
      is_active BOOLEAN NOT NULL DEFAULT TRUE — manager can deactivate a pair,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now().
      CHECK (class_a < class_b) — canonical order, enforced by DB.
      UNIQUE(tenant_id, class_a, class_b).

    This is a SUGGESTION-ONLY surface: every alert from ddi_alerts() carries
    suggestion_only=True. The physician decides; the engine suggests.

    FK conventions (managed=False — real FKs live in SQL):
      - tenant_id: FK → platform.tenants (expressed as BigIntegerField).
    """

    SEVERITY_CONTRAINDICATED = "contraindicated"
    SEVERITY_MAJOR = "major"
    SEVERITY_MODERATE = "moderate"
    SEVERITY_MINOR = "minor"

    SEVERITY_CHOICES = [
        (SEVERITY_CONTRAINDICATED, "Contraindicated"),
        (SEVERITY_MAJOR, "Major"),
        (SEVERITY_MODERATE, "Moderate"),
        (SEVERITY_MINOR, "Minor"),
    ]

    # Severity rank for sorting (lower = more severe / higher priority)
    SEVERITY_RANK: dict = {
        SEVERITY_CONTRAINDICATED: 0,
        SEVERITY_MAJOR: 1,
        SEVERITY_MODERATE: 2,
        SEVERITY_MINOR: 3,
    }

    tenant_id = models.BigIntegerField(default=1)
    class_a = models.TextField()    # canonical: always < class_b (DB CHECK)
    class_b = models.TextField()    # canonical: always > class_a (DB CHECK)
    severity = models.TextField(choices=SEVERITY_CHOICES)   # CHECK enforced by DB
    message_fa = models.TextField()                          # verbatim from pharmacist
    evidence = models.TextField(null=True, blank=True)       # citation / reference
    is_active = models.BooleanField(default=True)            # manager-editable
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        managed = False
        app_label = "clinical"
        db_table = '"clinical"."ddi_pairs"'
        ordering = ["class_a", "class_b"]
        # DB-enforced: UNIQUE(tenant_id, class_a, class_b)
        # DB-enforced: CHECK (class_a < class_b)

    def __str__(self):
        return (
            f"DdiPair({self.class_a}+{self.class_b}, "
            f"severity={self.severity}, tenant_id={self.tenant_id})"
        )


class ActivityLog(models.Model):
    """
    clinical.activity_logs — append-only audit trail.

    Schema confirmed from schema_pg_slice2_clinical.sql §5b:
      id, tenant_id, user_id (cross-schema FK → platform.users, nullable),
      username, action_type, action_category, description,
      target_table, target_id, patient_link_id (nullable),
      created_at TIMESTAMPTZ DEFAULT now().

    managed=False: schema owned by the SQL slices.
    Append-only at DB level: REVOKE UPDATE/DELETE FROM clinical_app + platform_app
    is applied in the slice SQL. The ORM helper (audit.log_activity) only INSERTs.
    """

    tenant_id = models.BigIntegerField(default=1)
    # Cross-schema FK → platform.users (composite; no ORM FK, DB enforces it)
    user_id = models.BigIntegerField(null=True, blank=True)
    username = models.TextField(null=True, blank=True)
    action_type = models.TextField()
    action_category = models.TextField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    target_table = models.TextField(null=True, blank=True)
    target_id = models.BigIntegerField(null=True, blank=True)
    # nullable — some events are not per-patient (e.g. login)
    patient_link_id = models.BigIntegerField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        managed = False
        app_label = "clinical"
        db_table = '"clinical"."activity_logs"'
        ordering = ["-created_at"]

    def __str__(self):
        return (
            f"ActivityLog(action_type={self.action_type}, "
            f"user_id={self.user_id}, tenant_id={self.tenant_id})"
        )
