"""Canonical default catalogs ported from ``specialist_clinic``.

These rows are operational defaults, not medical truth.  They are inserted with
``update_or_create`` by ``seed_record_catalogs`` so each tenant owns an editable
copy.  Clinical decision thresholds remain in ``clinical_indicators``; lab
reference ranges below are presentation/entry metadata only.
"""
from __future__ import annotations

FLAG_CATALOG = [('ascvd',
  'سابقهٔ ASCVD (بیماری قلبی-عروقی آترواسکلروتیک)',
  'bool',
  None,
  'cardiac',
  'disease',
  10),
 ('cvd_high_risk',
  'ریسک بسیار بالای قلبی-عروقی (≥۵۵ سال + ≥۲ ریسک‌فاکتور)',
  'bool',
  None,
  'cardiac',
  'disease',
  20),
 ('hf', 'نارسایی قلب (HF)', 'bool', None, 'cardiac', 'disease', 30),
 ('hf_type',
  'نوع نارسایی قلب',
  'enum',
  'HFrEF|EF کاهش‌یافته,HFpEF|EF حفظ‌شده,unknown|نامشخص',
  'cardiac',
  'disease',
  40),
 ('hf_symptomatic', 'نارسایی قلبِ علامت‌دار', 'bool', None, 'cardiac', 'disease', 50),
 ('ckd_stage_g',
  'مرحلهٔ CKD بر اساس eGFR',
  'enum',
  'G1|G1 (≥۹۰),G2|G2 (۶۰–۸۹),G3a|G3a (۴۵–۵۹),G3b|G3b (۳۰–۴۴),G4|G4 (۱۵–۲۹),G5|G5 (<۱۵)',
  'renal',
  'disease',
  60),
 ('ckd_stage_a',
  'مرحلهٔ آلبومینوری',
  'enum',
  'A1|A1 (<۳۰),A2|A2 (۳۰–۲۹۹),A3|A3 (≥۳۰۰)',
  'renal',
  'disease',
  70),
 ('hypo_risk',
  'ریسک هیپوگلیسمی',
  'enum',
  'low|پایین,atrisk|در معرض,high|بالا',
  'risk',
  'disease',
  80),
 ('masld', 'کبد چربِ متابولیک (MASLD)', 'bool', None, 'hepatic', 'disease', 90),
 ('mash_biopsy', 'MASH اثبات‌شده / ریسک بالای فیبروز', 'bool', None, 'hepatic', 'disease', 100),
 ('pregnancy', 'بارداری', 'bool', None, 'repro', 'disease', 110),
 ('childbearing_no_contraception', 'توان بارداری بدون پیشگیری', 'bool', None, 'repro', 'disease', 120),
 ('smoking',
  'مصرف دخانیات/ویپ',
  'enum',
  'never|هرگز,former|ترک‌کرده,current|فعلی,vape|ویپ',
  'lifestyle',
  'lifestyle',
  130),
 ('frailty',
  'وضعیت سلامت/فراژیلیتی (سالمند)',
  'enum',
  'robust|سالم,intermediate|میانی,complex|پیچیده/فراژیل',
  'functional',
  'general',
  140),
 ('metabolic_surgery', 'سابقهٔ جراحی متابولیک', 'bool', None, 'history', 'disease', 150),
 ('monofilament',
  'مونوفیلامان ۱۰گرمی (حس محافظتی پا)',
  'enum',
  'normal|طبیعی,impaired|مختل,not_done|انجام‌نشده',
  'exam',
  'exam',
  160),
 ('eye_exam_date', 'آخرین معاینهٔ چشم (ته‌چشم گشاد)', 'date', None, 'exam', 'exam', 170),
 ('foot_exam_date', 'آخرین معاینهٔ جامع پا', 'date', None, 'exam', 'exam', 180)]

DRUG_CLASSES = [('metformin', 'متفورمین', True, 10),
 ('sglt2i', 'مهارکنندهٔ SGLT2', True, 20),
 ('glp1_ra', 'آگونیست GLP-1', True, 30),
 ('dual_gip_glp1', 'آگونیست دوگانهٔ GIP/GLP-1 (تیرزپاتاید)', True, 40),
 ('dpp4i', 'مهارکنندهٔ DPP-4', True, 50),
 ('tzd', 'پیوگلیتازون (TZD)', True, 60),
 ('su', 'سولفونیل‌اوره', True, 70),
 ('meglitinide', 'مگلیتینید', True, 80),
 ('insulin_basal', 'انسولین پایه', True, 90),
 ('insulin_bolus', 'انسولین پراندیال (بولوس)', True, 100),
 ('acei', 'مهارکنندهٔ ACE', False, 110),
 ('arb', 'ARB', False, 120),
 ('ccb', 'کلسیم‌بلاکر', False, 130),
 ('thiazide', 'دیورتیک تیازیدی', False, 140),
 ('statin', 'استاتین', False, 150),
 ('ezetimibe', 'ازتیمایب', False, 160),
 ('finerenone', 'فینرنون (nsMRA)', False, 170),
 ('aspirin', 'آسپرین', False, 180),
 ('beta_blocker', 'بتابلاکر', False, 190),
 ('loop_diuretic', 'دیورتیک لوپ', False, 200),
 ('fibrate', 'فیبرات', False, 210),
 ('mra', 'آنتاگونیست گیرنده مینرالوکورتیکوئید', False, 220),
 ('thyroid_agent', 'داروی تیروئید/لووتیروکسین', False, 230),
 ('antithyroid', 'ضدتیروئید', False, 240),
 ('other', 'سایر', False, 999)]

LAB_TESTS = [('fbs', 'قند خون ناشتا (FBS)', 'mg/dL', 70, 99, 'glycemic', 10),
 ('bs_2hpp', 'قند ۲ ساعت پس از غذا (2hpp)', 'mg/dL', 70, 140, 'glycemic', 15),
 ('bs_random', 'قند خون تصادفی', 'mg/dL', 70, 199, 'glycemic', 18),
 ('hba1c', 'هموگلوبین A1c', '%', 4.0, 5.6, 'glycemic', 20),
 ('ogtt_2h', 'تست تحمل گلوکز ۲ ساعته', 'mg/dL', 70, 139, 'glycemic', 25),
 ('insulin_fasting', 'انسولین ناشتا', 'µIU/mL', 2.6, 24.9, 'glycemic', 28),
 ('chol_total', 'کلسترول تام', 'mg/dL', None, 200, 'lipid', 30),
 ('ldl', 'LDL کلسترول', 'mg/dL', None, 100, 'lipid', 32),
 ('hdl', 'HDL کلسترول', 'mg/dL', 40, None, 'lipid', 34),
 ('triglyceride', 'تری‌گلیسرید', 'mg/dL', None, 150, 'lipid', 36),
 ('vldl', 'VLDL کلسترول', 'mg/dL', 5, 40, 'lipid', 38),
 ('creatinine', 'کراتینین سرم', 'mg/dL', 0.6, 1.3, 'kidney', 40),
 ('urea', 'اوره (BUN)', 'mg/dL', 15, 45, 'kidney', 42),
 ('bun', 'نیتروژن اورهٔ خون (BUN)', 'mg/dL', 7, 20, 'kidney', 43),
 ('egfr', 'eGFR (تخمین فیلتراسیون کلیه)', 'mL/min/1.73m²', 90, None, 'kidney', 44),
 ('uacr', 'نسبت آلبومین به کراتینین ادرار (UACR)', 'mg/g', None, 30, 'kidney', 46),
 ('uric_acid', 'اسید اوریک', 'mg/dL', 3.5, 7.2, 'kidney', 48),
 ('sodium', 'سدیم (Na)', 'mEq/L', 135, 145, 'electrolyte', 50),
 ('potassium', 'پتاسیم (K)', 'mEq/L', 3.5, 5.1, 'electrolyte', 52),
 ('chloride', 'کلر (Cl)', 'mEq/L', 98, 107, 'electrolyte', 54),
 ('calcium', 'کلسیم تام', 'mg/dL', 8.6, 10.2, 'electrolyte', 56),
 ('phosphorus', 'فسفر', 'mg/dL', 2.5, 4.5, 'electrolyte', 58),
 ('magnesium', 'منیزیم', 'mg/dL', 1.7, 2.2, 'electrolyte', 59),
 ('ast', 'AST (SGOT)', 'U/L', None, 40, 'hepatic', 60),
 ('alt', 'ALT (SGPT)', 'U/L', None, 41, 'hepatic', 62),
 ('alp', 'آلکالن فسفاتاز (ALP)', 'U/L', 46, 116, 'hepatic', 64),
 ('ggt', 'GGT', 'U/L', None, 55, 'hepatic', 65),
 ('bil_total', 'بیلی‌روبین تام', 'mg/dL', 0.1, 1.2, 'hepatic', 66),
 ('albumin', 'آلبومین سرم', 'g/dL', 3.5, 5.2, 'hepatic', 68),
 ('tsh', 'TSH', 'mIU/L', 0.4, 4.0, 'thyroid', 70),
 ('t4', 'تیروکسین تام (T4)', 'µg/dL', 4.5, 12.0, 'thyroid', 72),
 ('ft4', 'T4 آزاد (Free T4)', 'ng/dL', 0.8, 1.8, 'thyroid', 73),
 ('t3', 'تری‌یدوتیرونین (T3)', 'ng/dL', 80, 200, 'thyroid', 74),
 ('anti_tpo', 'آنتی‌بادی ضد TPO', 'IU/mL', None, 34, 'thyroid', 76),
 ('wbc', 'گلبول سفید (WBC)', '10³/µL', 4.0, 10.0, 'cbc', 80),
 ('rbc', 'گلبول قرمز (RBC)', '10⁶/µL', 4.2, 5.9, 'cbc', 82),
 ('hgb', 'هموگلوبین (Hgb)', 'g/dL', 12.0, 17.0, 'cbc', 84),
 ('hct', 'هماتوکریت (Hct)', '%', 36, 50, 'cbc', 86),
 ('mcv', 'MCV', 'fL', 80, 100, 'cbc', 88),
 ('plt', 'پلاکت (PLT)', '10³/µL', 150, 450, 'cbc', 90),
 ('vit_d', 'ویتامین D (25-OH)', 'ng/mL', 30, 100, 'vitamin', 100),
 ('vit_b12', 'ویتامین B12', 'pg/mL', 200, 900, 'vitamin', 102),
 ('ferritin', 'فریتین', 'ng/mL', 20, 250, 'vitamin', 104),
 ('crp', 'CRP', 'mg/L', None, 5, 'inflammation', 110),
 ('esr', 'ESR (سرعت رسوب)', 'mm/hr', None, 20, 'inflammation', 112),
 ('hs_crp', 'hs-CRP', 'mg/L', None, 3, 'inflammation', 114)]

CONDITION_LAB_TESTS = {'diabetes': ['hba1c',
              'fbs',
              'bs_2hpp',
              'ldl',
              'hdl',
              'triglyceride',
              'chol_total',
              'creatinine',
              'egfr',
              'uacr',
              'ast',
              'alt',
              'potassium'],
 'hypertension': ['creatinine',
                  'egfr',
                  'potassium',
                  'sodium',
                  'uacr',
                  'ldl',
                  'hdl',
                  'triglyceride',
                  'chol_total',
                  'uric_acid'],
 'hyperlipidemia': ['chol_total', 'ldl', 'hdl', 'triglyceride', 'vldl', 'ast', 'alt', 'fbs', 'hba1c'],
 'ckd': ['creatinine', 'egfr', 'uacr', 'urea', 'potassium', 'sodium', 'calcium', 'phosphorus', 'hgb', 'hct', 'albumin'],
 'thyroid': ['tsh', 't4', 'ft4', 't3', 'anti_tpo']}

DRUG_CATALOG = [('متفورمین', 'metformin', ['500mg', '750mg', '1000mg']),
 ('امپاگلیفلوزین', 'sglt2i', ['10mg', '25mg']),
 ('داپاگلیفلوزین', 'sglt2i', ['5mg', '10mg']),
 ('کاناگلیفلوزین', 'sglt2i', ['100mg', '300mg']),
 ('لیراگلوتاید', 'glp1_ra', ['0.6mg', '1.2mg', '1.8mg']),
 ('سماگلوتاید', 'glp1_ra', ['0.25mg', '0.5mg', '1mg']),
 ('دولاگلوتاید', 'glp1_ra', ['0.75mg', '1.5mg']),
 ('تیرزپاتاید', 'dual_gip_glp1', ['2.5mg', '5mg', '7.5mg', '10mg']),
 ('سیتاگلیپتین', 'dpp4i', ['50mg', '100mg']),
 ('لیناگلیپتین', 'dpp4i', ['5mg']),
 ('ویلداگلیپتین', 'dpp4i', ['50mg']),
 ('پیوگلیتازون', 'tzd', ['15mg', '30mg', '45mg']),
 ('گلی‌بنکلامید (گلی‌بوراید)', 'su', ['2.5mg', '5mg']),
 ('گلی‌کلازید', 'su', ['30mg', '60mg', '80mg']),
 ('گلی‌مپراید', 'su', ['1mg', '2mg', '3mg', '4mg']),
 ('رپاگلیناید', 'meglitinide', ['0.5mg', '1mg', '2mg']),
 ('انسولین گلارژین', 'insulin_basal', ['10U', '20U', '30U']),
 ('انسولین دتمیر', 'insulin_basal', ['10U', '20U']),
 ('انسولین NPH', 'insulin_basal', ['10U', '20U']),
 ('انسولین آسپارت', 'insulin_bolus', ['4U', '6U', '8U']),
 ('انسولین لیسپرو', 'insulin_bolus', ['4U', '6U', '8U']),
 ('انسولین رگولار', 'insulin_bolus', ['4U', '6U', '8U']),
 ('لوزارتان', 'arb', ['25mg', '50mg', '100mg']),
 ('والزارتان', 'arb', ['80mg', '160mg', '320mg']),
 ('تلمیزارتان', 'arb', ['40mg', '80mg']),
 ('کاپتوپریل', 'acei', ['25mg', '50mg']),
 ('انالاپریل', 'acei', ['5mg', '10mg', '20mg']),
 ('لیزینوپریل', 'acei', ['5mg', '10mg', '20mg']),
 ('پریندوپریل', 'acei', ['4mg', '8mg']),
 ('آملودیپین', 'ccb', ['5mg', '10mg']),
 ('نیفدیپین', 'ccb', ['20mg', '40mg']),
 ('دیلتیازم', 'ccb', ['60mg', '90mg', '120mg']),
 ('هیدروکلروتیازید', 'thiazide', ['12.5mg', '25mg']),
 ('اینداپامید', 'thiazide', ['1.5mg', '2.5mg']),
 ('آتنولول', 'beta_blocker', ['25mg', '50mg', '100mg']),
 ('متوپرولول', 'beta_blocker', ['25mg', '50mg', '100mg']),
 ('کارودیلول', 'beta_blocker', ['6.25mg', '12.5mg', '25mg']),
 ('بیزوپرولول', 'beta_blocker', ['2.5mg', '5mg', '10mg']),
 ('اسپیرونولاکتون', 'mra', ['25mg', '50mg', '100mg']),
 ('فوروزماید', 'loop_diuretic', ['20mg', '40mg']),
 ('فینرنون', 'finerenone', ['10mg', '20mg']),
 ('آتورواستاتین', 'statin', ['10mg', '20mg', '40mg', '80mg']),
 ('روزوواستاتین', 'statin', ['5mg', '10mg', '20mg', '40mg']),
 ('سیمواستاتین', 'statin', ['10mg', '20mg', '40mg']),
 ('لوواستاتین', 'statin', ['20mg', '40mg']),
 ('ازتیمایب', 'ezetimibe', ['10mg']),
 ('جم‌فیبروزیل', 'fibrate', ['600mg']),
 ('فنوفیبرات', 'fibrate', ['145mg', '160mg', '200mg']),
 ('آسپرین', 'aspirin', ['80mg', '100mg']),
 ('لووتیروکسین', 'thyroid_agent', ['25µg', '50µg', '75µg', '100µg', '150µg']),
 ('متی‌مازول', 'antithyroid', ['5mg', '10mg']),
 ('پروپیل‌تیواوراسیل (PTU)', 'antithyroid', ['50mg', '100mg'])]

ALLOWED_REFILL_INTERVALS = frozenset({15, 30, 60, 90})
NOTE_KINDS = frozenset({"symptom", "exam", "lifestyle", "general"})
FLAG_TYPES = frozenset({"bool", "enum", "date", "text"})
RECORD_SECTIONS = frozenset({"lifestyle", "exam", "disease", "general"})
MEDICATION_EVENT_TYPES = frozenset({"start", "stop", "dose_change"})
