# Generated by Django 5.2.15 on 2026-06-09 01:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalIndicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.TextField()),
                ('name_fa', models.TextField()),
                ('unit', models.TextField(blank=True, default='')),
                ('warn_low', models.FloatField(blank=True, null=True)),
                ('warn_high', models.FloatField(blank=True, null=True)),
                ('danger_low', models.FloatField(blank=True, null=True)),
                ('danger_high', models.FloatField(blank=True, null=True)),
                ('target_text', models.TextField(blank=True, default='')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.clinic')),
            ],
            options={
                'db_table': 'clinical_indicator',
            },
        ),
        migrations.CreateModel(
            name='ClinicalRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.TextField()),
                ('title', models.TextField()),
                ('category', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('info', 'info'), ('suggestion', 'suggestion'), ('warning', 'warning'), ('red_flag', 'red_flag')], default='suggestion', max_length=16)),
                ('trigger_json', models.JSONField(default=dict)),
                ('message_fa', models.TextField(blank=True, default='')),
                ('source_ref', models.TextField(blank=True, default='', help_text='ADA citation')),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.clinic')),
            ],
            options={
                'db_table': 'clinical_rule',
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.TextField()),
                ('name_fa', models.TextField()),
                ('name_en', models.TextField(blank=True, default='')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.clinic')),
            ],
            options={
                'db_table': 'condition',
            },
        ),
        migrations.CreateModel(
            name='DrugClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.TextField()),
                ('name_fa', models.TextField()),
                ('name_en', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.clinic')),
            ],
            options={
                'db_table': 'drug_class',
            },
        ),
        migrations.CreateModel(
            name='FlagCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.TextField()),
                ('label_fa', models.TextField()),
                ('severity', models.TextField(blank=True, default='')),
                ('color', models.TextField(blank=True, default='')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.clinic')),
            ],
            options={
                'db_table': 'flag_catalog',
            },
        ),
        migrations.CreateModel(
            name='FollowupTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_key', models.TextField()),
                ('title', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'open'), ('done', 'done'), ('snoozed', 'snoozed'), ('dismissed', 'dismissed')], default='open', max_length=16)),
                ('source_rule', models.TextField(blank=True, default='')),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='patients.patient')),
            ],
            options={
                'db_table': 'followup_task',
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_name', models.TextField()),
                ('value', models.TextField()),
                ('unit', models.TextField(blank=True, default='')),
                ('reference_range', models.TextField(blank=True, default='')),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='patients.patient')),
            ],
            options={
                'db_table': 'lab_result',
            },
        ),
        migrations.CreateModel(
            name='PatientCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('status', models.TextField(blank=True, default='active')),
                ('notes', models.TextField(blank=True, default='')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.clinic')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='chronic.condition')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_condition',
            },
        ),
        migrations.CreateModel(
            name='PatientFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('raised_at', models.DateTimeField()),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.clinic')),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='chronic.flagcatalog')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_flag',
            },
        ),
        migrations.CreateModel(
            name='PatientMedication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('dose', models.TextField(blank=True, default='')),
                ('frequency', models.TextField(blank=True, default='')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.clinic')),
                ('drug_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='chronic.drugclass')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='patients.patient')),
            ],
            options={
                'db_table': 'patient_medication',
            },
        ),
        migrations.CreateModel(
            name='MedicationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.TextField()),
                ('detail', models.TextField(blank=True, default='')),
                ('occurred_at', models.DateTimeField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_events', to='patients.patient')),
                ('medication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='chronic.patientmedication')),
            ],
            options={
                'db_table': 'medication_event',
            },
        ),
        migrations.CreateModel(
            name='SuggestionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_code', models.TextField(blank=True, default='')),
                ('severity', models.TextField(blank=True, default='')),
                ('message_fa', models.TextField()),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.appuser')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='patients.patient')),
            ],
            options={
                'db_table': 'suggestion_log',
            },
        ),
        migrations.CreateModel(
            name='VitalReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicator_key', models.TextField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('measured_at', models.DateTimeField()),
                ('source', models.TextField(blank=True, default='')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.clinic')),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='chronic.clinicalindicator')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='patients.patient')),
            ],
            options={
                'db_table': 'vital_reading',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('credit', 'credit'), ('debit', 'debit')], max_length=8)),
                ('amount', models.BigIntegerField()),
                ('balance_after', models.BigIntegerField()),
                ('reason', models.TextField(blank=True, default='')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.appuser')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='patients.patient')),
            ],
            options={
                'db_table': 'wallet_transaction',
            },
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('substance', models.TextField()),
                ('reaction', models.TextField(blank=True, default='')),
                ('severity', models.TextField(blank=True, default='')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patients.patient')),
            ],
            options={
                'db_table': 'allergy',
                'indexes': [models.Index(fields=['clinic', 'patient'], name='allergy_clinic__677afd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'scheduled'), ('done', 'done'), ('cancelled', 'cancelled'), ('no_show', 'no_show')], default='scheduled', max_length=16)),
                ('reason', models.TextField(blank=True, default='')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.clinic')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identity.appuser')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
            options={
                'db_table': 'appointment',
                'indexes': [models.Index(fields=['clinic', 'scheduled_at', 'status'], name='appointment_clinic__fc6a4a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CareProtocol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, default='')),
                ('item_key', models.TextField()),
                ('interval_months', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='identity.clinic')),
            ],
            options={
                'db_table': 'care_protocol',
                'indexes': [models.Index(fields=['clinic', 'item_key'], name='care_protoc_clinic__0dae4e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='clinicalindicator',
            index=models.Index(fields=['clinic', 'key'], name='clinical_in_clinic__263634_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalrule',
            index=models.Index(fields=['clinic', 'code'], name='clinical_ru_clinic__9216e8_idx'),
        ),
        migrations.AddIndex(
            model_name='condition',
            index=models.Index(fields=['clinic', 'code'], name='condition_clinic__f050e5_idx'),
        ),
        migrations.AddIndex(
            model_name='drugclass',
            index=models.Index(fields=['clinic', 'code'], name='drug_class_clinic__10889c_idx'),
        ),
        migrations.AddIndex(
            model_name='flagcatalog',
            index=models.Index(fields=['clinic', 'code'], name='flag_catalo_clinic__2078b2_idx'),
        ),
        migrations.AddIndex(
            model_name='followuptask',
            index=models.Index(fields=['clinic', 'status', 'due_date'], name='followup_ta_clinic__856d23_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['clinic', 'patient', '-taken_at'], name='lab_result_clinic__bd389b_idx'),
        ),
        migrations.AddIndex(
            model_name='patientcondition',
            index=models.Index(fields=['clinic', 'patient'], name='patient_con_clinic__ac46c9_idx'),
        ),
        migrations.AddIndex(
            model_name='patientflag',
            index=models.Index(fields=['clinic', 'patient', 'is_active'], name='patient_fla_clinic__005f7b_idx'),
        ),
        migrations.AddIndex(
            model_name='patientmedication',
            index=models.Index(fields=['clinic', 'patient', 'is_active'], name='patient_med_clinic__150e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationevent',
            index=models.Index(fields=['clinic', 'patient', 'occurred_at'], name='medication__clinic__6e172d_idx'),
        ),
        migrations.AddIndex(
            model_name='suggestionlog',
            index=models.Index(fields=['clinic', 'patient', '-created_at'], name='suggestion__clinic__024261_idx'),
        ),
        migrations.AddIndex(
            model_name='vitalreading',
            index=models.Index(fields=['clinic', 'patient', 'indicator_key', '-measured_at'], name='vital_readi_clinic__e665f0_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['clinic', 'patient', '-created_at'], name='wallet_tran_clinic__1e3a72_idx'),
        ),
    ]
