# Generated by Django 5.2.15 on 2026-06-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientflag',
            name='value',
            field=models.TextField(blank=True, default=''),
        ),
    ]
